Compact syntax for event lists
OpenRCT2/OpenRCT2 pull request #12973
Opened 2020-09-19 16:46 UTC by AaronVanGeffen

Currently, the window event list struct only has one (default) constructor, which leads to a bunch of null-pointers having to be set for most windows. It's not obvious which events they represent, which leaves these lists hard to maintain. Unfortunately, we cannot use named initialisers. Therefore, I propose a replacement set of definitions for the event lists using functions, giving them a syntax [similar to OpenLoco](https://github.com/OpenLoco/OpenLoco/blob/9b419912746c1b4930b1165e6dd4c149aeb48704/src/OpenLoco/Windows/Options.cpp#L633-L643).

I generated all of this using [a Python script](https://gist.github.com/AaronVanGeffen/110509418eca7bd22f6fbfb93c1406d3), which hopefully reduces the chance of errors. From brief testing on my end, all appears to work correctly. However, we should test this properly before merging.

2020-09-19 19:24 UTC, ZehMatt commented
Since you already touch quite a bit of the code would be nice to have them in PascalCase/camelCase where appropriate.

2020-09-19 19:39 UTC, AaronVanGeffen commented
I agree that would be nice, but I think that is really something for another PR. Preferably, we would rename the event functions into namespaces at the same time.

2020-09-19 20:39 UTC, ZehMatt commented
We can probably avoid explicit initialization with something like this: https://godbolt.org/z/PqaKPf , what do you think about that?

2020-09-20 10:51 UTC, AaronVanGeffen commented
I think it would be great if we can avoid explicitly calling an initialisation function. Your snippet looks like a great start in this respect. However, I am not sure I can adapt it directly. The problem I'm seeing is that the event handlers are stored as a pointer:
```cpp
struct rct_window
{
    rct_window_event_list* event_handlers;
```

Currently the event lists are passed as follows:
```
        window = window_create_auto_pos(windowWidth, 157, &window_guest_overview_events, WC_PEEP, WF_RESIZABLE);
```

I am wondering where the constructor (below) would be called here. Can we avoid making the assignment more explicit than this?
```cpp
    rct_window_event_list(auto fn)
    {
        fn(*this);
    }
```

2020-09-20 11:16 UTC, Broxzier requested changes
Left a few comments on removed EOLs, this happened automatically by your editor, I presume. `insert_final_newline` is set in our `.editorconfig` file, so your editor seems to ignore this.

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/Cheats.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/ClearScenery.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/CustomCurrency.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/DebugPaint.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/DemolishRidePrompt.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/Dropdown.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/EditorBottomToolbar.cpp
> +}
EOL

2020-09-20 11:16 UTC, Broxzier commented on src/openrct2-ui/windows/EditorInventionsList.cpp
> +#pragma endregion
EOL

2020-09-20 11:28 UTC, AaronVanGeffen commented
@Broxzier Ah, you're right, I hadn't noticed. This is entirely due to my Python script omitting them in its output — an oversight. I will amend. (It's a pity `clang-format` doesn't tackle this.)

2020-09-20 11:37 UTC, ZehMatt commented
> I think it would be great if we can avoid explicitly calling an initialisation function. Your snippet looks like a great start in this respect. However, I am not sure I can adapt it directly. The problem I'm seeing is that the event handlers are stored as a pointer:
> 
> ```c++
> struct rct_window
> {
>     rct_window_event_list* event_handlers;
> ```
> 
> Currently the event lists are passed as follows:
> 
> ```
>         window = window_create_auto_pos(windowWidth, 157, &window_guest_overview_events, WC_PEEP, WF_RESIZABLE);
> ```
> 
> I am wondering where the constructor (below) would be called here. Can we avoid making the assignment more explicit than this?
> 
> ```c++
>     rct_window_event_list(auto fn)
>     {
>         fn(*this);
>     }
> ```

The construction should happen at the beginning of the application start, static initialization happens via a list the compiler constructed and iterates thru the constructors before any code is usually called, so that should be fine.

2020-09-28 17:28 UTC, AaronVanGeffen commented
@ZehMatt Unfortunately, it seems your example only works if C++20 concepts are available. When I change to C++17 in Godbolt, it no longer compiles:

```
error: use of ‘auto’ in parameter declaration only available with ‘-fconcepts-ts’ [-Werror]
  245 |     rct_window_event_list(auto fn)
      |                           ^~~~
```

Any ideas?

2020-09-28 17:41 UTC, ZehMatt commented
> @ZehMatt Unfortunately, it seems your example only works if C++20 concepts are available. When I change to C++17 in Godbolt, it no longer compiles:
> 
> ```
> error: use of ‘auto’ in parameter declaration only available with ‘-fconcepts-ts’ [-Werror]
>   245 |     rct_window_event_list(auto fn)
>       |                           ^~~~
> ```
> 
> Any ideas?

https://godbolt.org/z/Gv7Gn6 😏

2020-09-28 18:02 UTC, AaronVanGeffen commented
I think I've got it. Even more impressive diffstat now :+1:

2020-09-28 18:34 UTC, ZehMatt approved these changes

2020-09-28 18:36 UTC, merged