Fix #4022: Mac cursor offset on launch
OpenRCT2/OpenRCT2 pull request #13095
Opened 2020-10-04 06:54 UTC by aidan-waite

I'm not sure this is the best approach for fixing this bug, but I'll explain my thought process and reproduction steps and I look forward to any feedback, input or suggestions.

### Reproducing the Bug

**Steps**

1. Launch the game
2. Fullscreen game
3. Close game
4. Relaunch game

**Expected**

Game should launch fullscreen and cursor should work as expected.

**Actual**

Game launches windowed as large as it can, and the cursor is off vertically as described in the original issue

### Process

After some experimentation and discussion in the Discord channel, it seems like there is an SDL2 bug with Mac OSX. SetFullscreenMode is called during UiContext's startup flow. Not calling it removes the cursor offset. We still need this function to work on Mac normally since it gets called when the user changes from fullscreen to windowed while playing. By changing only the startup flow and only for Mac OSX, the original issue is fixed without affecting any other platforms.

### Next steps

A better fix would involve a deeper understanding of why exactly the bug occurs and what part SDL2 plays.

2020-10-05 10:10 UTC, AaronVanGeffen commented
Thanks for the patch. Nowadays, the macOS window manager can take games into a dedicated 'fullscreen' space — but that's not what SDL2 is doing. Perhaps we should consider disabling the option to take the game into fullscreen on macOS altogether until this is fixed.

I will test the patch later; I am unable to do so at the moment.

2020-10-05 12:43 UTC, AaronVanGeffen requested changes
This works okay, in that it has the intended effect. However, because the config is not updated, the options window will still show 'Fullscreen' whilst the game is actually running in 'Windowed' mode.

If the game is forced into windowed mode, the config should be updated to reflect this.

2020-10-05 14:24 UTC, aidan-waite commented
> Thanks for the patch. Nowadays, the macOS window manager can take games into a dedicated 'fullscreen' space — but that's not what SDL2 is doing. Perhaps we should consider disabling the option to take the game into fullscreen on macOS altogether until this is fixed.
> 
> I will test the patch later; I am unable to do so at the moment.

Thanks for the review! Is macOS window manager an Open RCT2 thing or a macOS system thing? I'm not 100% sure what you mean by this, it sounds like maybe macOS isn't making the game window fullscreen when SDL2 tells it to?

> This works okay, in that it has the intended effect. However, because the config is not updated, the options window will still show 'Fullscreen' whilst the game is actually running in 'Windowed' mode.
> 
> If the game is forced into windowed mode, the config should be updated to reflect this.

Excellent point! I will fix this 👍

2020-10-05 14:34 UTC, AaronVanGeffen commented
> Thanks for the review! Is macOS window manager an Open RCT2 thing or a macOS system thing? I'm not 100% sure what you mean by this, it sounds like maybe macOS isn't making the game window fullscreen when SDL2 tells it to?

Yes, I was referring to the system window manager. OpenRCT2 doesn't interact with it directly. As you surmise, that's SDL2's job.

> Excellent point! I will fix this +1

Cheers!

2020-10-10 12:17 UTC, aidan-waite commented
> > Thanks for the review! Is macOS window manager an Open RCT2 thing or a macOS system thing? I'm not 100% sure what you mean by this, it sounds like maybe macOS isn't making the game window fullscreen when SDL2 tells it to?
> 
> Yes, I was referring to the system window manager. OpenRCT2 doesn't interact with it directly. As you surmise, that's SDL2's job.
> 
> > Excellent point! I will fix this +1
> 
> Cheers!

I've updated the config to reflect the enforcing of windowed mode on Mac on launch. It appears to now work correctly with the game objects menu. Please take another look when you get a chance 👍

2020-10-13 01:11 UTC, tupaschoal commented
@AaronVanGeffen how does this solution look to you now?

2020-10-15 15:08 UTC, AaronVanGeffen approved these changes
This is working properly now. Could you amend the changelog as well? (You might need to rebase your branch on top of develop to prevent conflicts in the changelog.)

2020-10-17 08:16 UTC, aidan-waite commented
Alright baby's (my) first rebase may or may not have been executed correctly (going to guess not).

2020-10-17 08:20 UTC, AaronVanGeffen commented
No, it looks like something went wrong indeed. Did you follow the instructions on the wiki?

2020-10-17 08:23 UTC, aidan-waite commented
> No, it looks like something went wrong indeed. Did you follow the [instructions on the wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2)?

I did not... Is there a good way to undo what I've done so I can take another crack at it?

2020-10-17 08:31 UTC, AaronVanGeffen commented
Find the last good version with `git reflog` and reset to it using `git reset --hard <commit hash>`

2020-10-17 09:29 UTC, AaronVanGeffen commented
Looks like you managed to rebase properly this time. However, it seems your upstream remote was outdated when rebased, so the conflict hasn't been resolved yet.

2020-10-17 09:31 UTC, aidan-waite commented
I appreciate the help! I think it should be all set now 👍  Happy to tweak further if it's not quite there yet

2020-10-17 09:34 UTC, AaronVanGeffen commented
Is looking good now. Ready to be merged once CI passes.

2020-10-17 09:57 UTC, merged