Fix #13427. Show # of people for newly created Go-Karts
OpenRCT2/OpenRCT2 pull request #13457
Opened 2020-11-25 18:20 UTC by ffrogman

Fix #13427. This was caused in the fix for issue #12497 0f78d452.

race_winner is null when the ride is first constructed. The fix for issue #12497 accidentally changed the logic here in an attempt to prevent a duplicate check. This resulted in "Race won by" displaying any time a ride switches from closed to open (not just the first time). This message remained until the ride actually started. For example it would jump up to say "7 people on the ride" immediately even if peeps are entering the ride slowly.

In vanilla for a ride that changed from closed to open the message says "0 people on the ride" and counts as peeps enter the ride. I tested and this fix seems to behave the same as vanilla.

2020-11-25 19:28 UTC, duncanspumpkin approved these changes

2020-11-26 12:15 UTC, Gymnasiast requested changes
Could you add a changelog entry?
`- Fix: [#13427] Newly created Go-Karts show "Race won by <blank>".`

2020-11-26 16:57 UTC, duncanspumpkin commented
Sorry could you move the fix so that the fixes are grouped together in order of number.

2020-11-26 18:04 UTC, duncanspumpkin approved these changes

2020-11-26 18:04 UTC, merged