Add stubbed Vehicle test
OpenRCT2/OpenRCT2 pull request #14104
Opened 2021-02-15 20:49 UTC by janisozaur

Allows for testing `Vehicle.cpp` code in isolation

2021-02-15 20:52 UTC, janisozaur commented on test/tests/CMakeLists.txt
> +        #"${ROOT_DIR}/src/openrct2/audio/Audio.cpp"
These were temporaries I tried using initially, to figure out how far can I reduce the necessary data

2021-02-15 20:54 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +static Vehicle* vehicle_create_car(
Copied verbatim from `Ride.cpp`, but including that file in the new target pulls a whole lot of other dependencies. I haven't really paid much attention to what it does, might be simplified

2021-02-15 20:55 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +    [[maybe_unused]] Vehicle v{};
Dummy test to show a Vehicle can be created

2021-02-15 20:55 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +    v.Update();
... and updated

2021-02-15 20:56 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +    Vehicle* v = cable_lift_segment_create(r, 0, 0, 0, 0, 0, 0, true);
Semi-random cable lift test, as it required pulling in a new file into the target

2021-02-15 20:57 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +    vehicle_create_car(0, 0, 0, 0, {}, &rd, &te);
There is some minimal configuration necessary to call this function, otherwise it could segfault

2021-02-15 20:57 UTC, IntelOrca requested changes
If you want to add tests for vehicle, please find a way that doesn't involve adding `#ifdef` to the main sources.

The tests should just link libopenrct2, I can't see any value in trying to compile sources stand alone from the rest of the project.

2021-02-15 21:00 UTC, janisozaur commented on test/tests/VehicleTest.cpp
> +    EXPECT_EQ(_goto_callsites, expected_results);
I find this the most exciting part of this whole PR. I've added a temporary call to a function `hit_goto_callsite` provided just above this test, which I can use to ensure all the callsites I'm interested in are hit. Once I'm happy with the quality of the tests, the next step would be gathering checksums of all affected objects after the test is done and removing the calls to `hit_goto_callsite`

2021-03-01 21:45 UTC, janisozaur commented
@IntelOrca the reason to not bother with libopenrct2 is the hardcoding of loading of various files that I don't want to bother with:

https://github.com/OpenRCT2/OpenRCT2/blob/c98746c910eea2c159837e939ccee20be6db1a90/src/openrct2/ride/Ride.cpp#L217-L229

I just want to test various parts of `Vehicle::Update`

2021-03-01 21:55 UTC, IntelOrca commented
Source files are not expected to be compiled / linked in isolation from the other source files. That is what the directories themselves are for; libsawyer, libopenrct2, libopenrct2g, libopenrct2ui, openrct2 etc. Each one of those would have a separate unit test folder linking that lib.

2021-03-01 22:09 UTC, janisozaur commented
If we had those, that would be preferred solution, yes. But the only actual split we have so far is `libopenrct2` and its clients; pretty much an all-or-nothing type of deal.

2021-03-01 22:19 UTC, IntelOrca commented
@janisozaur I am currently looking at libsawyer. libopenrct2g is something I would like but haven't got round to yet. The unit tests should just link with libopenrct2 for the time being, once they are split up, the unit test can be changed to link with the smaller lib.

2021-03-01 22:47 UTC, janisozaur commented
Sounds nice. Do you have any ETA on that or progress track/design somewhere?

2021-03-01 22:58 UTC, IntelOrca commented
@janisozaur at the moment it is just a private repo, still trying to figure out how to get cmake find_package working.

2022-10-29 15:54 UTC, rik-smeets commented
I'm closing this PR due to inactivity, feel free to reopen if you like to continue working on it.

2022-10-29 15:54 UTC, closed without merging