Part of #12100: Use ScreenLine on gfx_draw_line_software
OpenRCT2/OpenRCT2 pull request #14277
Opened 2021-03-08 23:26 UTC by frutiemax

2021-03-09 02:25 UTC, ZehMatt requested changes

2021-03-09 02:25 UTC, ZehMatt commented on src/openrct2/drawing/Line.cpp
> +    gfx_draw_line_software(dpi, line.GetX1(), line.GetY1(), line.GetX2(), line.GetY2(), colour);
This should be the other way around, the new function should not call the deprecated variant.

2021-03-12 02:27 UTC, tupaschoal approved these changes

2021-03-13 07:30 UTC, ZehMatt approved these changes

2021-03-13 15:52 UTC, merged