Allow early scenario completion in network play
OpenRCT2/OpenRCT2 pull request #14297
Opened 2021-03-12 15:06 UTC by MaximilianBottin

Fixes #14296

This Commit fixes the issues by sending the current config for the allow early scenario completion and having the clients use this sent value to compare against instead of their own configuration.

This approach has two issues though. 
First of all if the host changes the setting mid-game the clients won't recognize the change and thus a desync will occur.
   (Maybe it could be possible to always send the current setting through the network when the host changes it)
Second, the Clients are still able to change their allow early scenario completion setting, but it won't have any effect in multiplayer which can be confusing so maybe the option to change it during multiplayer should be disabled (would also fix the issue I mentioned above)

2021-03-12 16:39 UTC, duncanspumpkin commented
You need to add a game action / modify an existing game action to handle changes that happen mid-game.

2021-03-12 16:56 UTC, MaximilianBottin commented
Thanks, I'll look into that and add it to my commit

2021-03-13 17:36 UTC, Gymnasiast commented on src/openrct2/scenario/Scenario.cpp
> +bool Objective::AllowEarlyCompletion() const
Doesn't belong in the objective struct. Please turn this into a regular function.

2021-03-17 17:49 UTC, Gymnasiast commented on src/openrct2/scenario/Scenario.h
> +bool allowEarlyCompletion();
```suggestion
bool AllowEarlyCompletion();
```

2021-03-17 17:50 UTC, Gymnasiast requested changes
Looks good to me, please address the line note and bump the network version and this can be merged AFAIC.

2021-03-18 19:29 UTC, Gymnasiast approved these changes

2021-03-18 19:30 UTC, merged