Fix #8601
OpenRCT2/OpenRCT2 pull request #15135
Opened 2021-07-30 17:48 UTC by duncanspumpkin

2021-07-30 18:57 UTC, AaronVanGeffen commented
Out of curiosity, why does applying that flag to those particular three objects affect the supports drawing?

2021-07-30 19:40 UTC, Gymnasiast requested changes
This is not a bug. All vanilla base blocks allow supports on top, and so I fixed ToonTowner’s base blocks to also allow them. The bug is that TT forgot to set that flag on his objects in the first place.

2021-07-30 19:51 UTC, duncanspumpkin commented
The community clearly wants this fix reverted.

2021-07-30 19:52 UTC, duncanspumpkin commented
> Out of curiosity, why does applying that flag to those particular three objects affect the supports drawing?

People use those particular objects as support blockers. This is the flag that controls blocking supports.

2021-07-30 20:01 UTC, Gymnasiast commented
> The community clearly wants this fix reverted.

I know of exactly one user who has asked us for this. On the original issue, **nobody** else has chimed in. That’s a far cry from “the community” “clearly” wanting this fix reverted.

> People use those particular objects as support blockers. This is the flag that controls blocking supports.

Which is an ill-advised thing to do. You can’t use the vanilla base blocks as support blockers, so anyone who uses a custom base block as one is just asking for trouble.

2021-07-31 12:05 UTC, Gymnasiast commented on src/openrct2/object/SmallSceneryObject.cpp
> +    // ToonTowner's base blocks. Make put them in the Walls and Roofs group.
```suggestion
    // ToonTowner's base blocks. Put them in the Walls and Roofs group.
```

2021-07-31 12:10 UTC, merged