Fix: #15197 Construction window not being closed when a ride gets demolished
OpenRCT2/OpenRCT2 pull request #15198
Opened 2021-08-10 18:21 UTC by ZehMatt

That condition made no sense, when the ride is gone no construction can happen.

Closes #15197

2021-08-10 19:12 UTC, Broxzier requested changes
While these changes look good, this doesn't fix #115197. That issue is about removing a flat ride from construction window while in entrance/exit-placement mode, then being stuck on that part.

2021-08-10 19:42 UTC, ZehMatt commented
> While these changes look good, this doesn't fix #15197. That issue is about removing a flat ride from construction window while in entrance/exit-placement mode, then being stuck on that part.

Well without a ride the construction is impossible, this fixes that.

2021-08-29 18:29 UTC, Broxzier approved these changes

2021-08-29 20:19 UTC, Gymnasiast commented on distribution/changelog.txt
> +- Fix: [#15199] Construction window not being closed when a ride gets demolished.
```suggestion
- Fix: [#15199] Construction window is not closed when a ride gets demolished.
```

2021-08-29 20:20 UTC, Gymnasiast approved these changes

2021-08-29 20:20 UTC, merged