Remove scenario ticks and adjust export/import
OpenRCT2/OpenRCT2 pull request #15429
Opened 2021-09-17 22:48 UTC by ZehMatt

Another NSF backport, this one might break replays.

2021-09-17 23:06 UTC, ZehMatt commented on src/openrct2/rct2/S6Importer.cpp
> +    void ConvertScenarioTicks()
Stray change

2021-09-18 19:23 UTC, duncanspumpkin approved these changes
All looks fine to me. Await @Gymnasiast  review prior to merge.

2021-09-18 20:11 UTC, Gymnasiast commented
Would like to test a few things, e.g. stuff like https://github.com/OpenRCT2/OpenRCT2/issues/14734.

2021-09-18 20:13 UTC, ZehMatt commented
> Would like to test a few things, e.g. stuff like #14734.

There are three things to watch out for with this PR
1. Guest time in park
2. Staff hire time
3. Litter creation time, this influences the park rating and is somewhat hard to test I guess.

But given the guest and staff times seemed fine at my end I guess litter will be also.

2021-09-18 20:16 UTC, Gymnasiast commented
I don’t see code to properly import litter creation time in S6Importer, though. Is that intentional?

2021-09-18 20:18 UTC, ZehMatt commented
> I don’t see code to properly import litter creation time in S6Importer, though. Is that intentional?

Nope it seems I forgot that one even tho I know I must do it, nice catch.

2021-09-18 21:20 UTC, Gymnasiast requested changes
Does not work correctly. The mechanics in this save all have a hire date of June, yr 528 instead of March, yr 1.

[Pakhuis - Derde Alter Ego - fixedMR.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/7190657/Pakhuis.-.Derde.Alter.Ego.-.fixedMR.sv6.zip)

2021-09-18 23:08 UTC, ZehMatt commented
HireDate is used as an absolute time for  {MONTHYEAR} unlike guests which use a relative time, it should be good now.

2021-09-23 08:03 UTC, Gymnasiast commented on src/openrct2/rct2/S6Importer.cpp
> +    // Previously gScenarioTicks was used as a time point now its gCurrentTicks.
```suggestion
    // Previously gScenarioTicks was used as a time point, now it’s gCurrentTicks.
```

2021-09-23 08:03 UTC, Gymnasiast commented on src/openrct2/rct2/S6Importer.cpp
> +    // scenario tick must add account for the distance between the two.
```suggestion
    // scenario tick must account for the difference between the two.
```

2021-09-23 08:05 UTC, Gymnasiast approved these changes
Still a bit apprehensive (if this breaks, it will be in subtle and hard-to-detect ways), but I haven’t found any more bugs.

2021-09-23 19:08 UTC, merged