Fix #15274: Scenario description missing when loading a park from a save file
OpenRCT2/OpenRCT2 pull request #15516
Opened 2021-10-02 18:12 UTC by CookiePLMonster

Saved games do not have a valid info chunk, so scenario names/descriptions did not load.

![image](https://user-images.githubusercontent.com/7947461/135727527-6c1b344b-b430-4020-80eb-9298c02fd657.png)

2021-10-02 21:25 UTC, Broxzier requested changes

2021-10-02 21:25 UTC, Broxzier commented on distribution/changelog.txt
> +- Fix: [#15274] Scenario description missing when loading a park from a save file.
Since this bug is not present in the last release, this changelog entry is not needed.

2021-10-02 22:36 UTC, Broxzier reviewed
Unfortunately, this does not seem to fix the issue with this test save I had lying around, also from Crazy Castle. [test-save.zip](https://github.com/OpenRCT2/OpenRCT2/files/7272339/test-save.zip)

Edit: Seems that this one is broken on release too.

2021-10-03 09:17 UTC, CookiePLMonster commented
> Unfortunately, this does not seem to fix the issue with this test save I had lying around, also from Crazy Castle. [test-save.zip](https://github.com/OpenRCT2/OpenRCT2/files/7272339/test-save.zip)

With this save, both `_s6.info.details` and `_s6.scenario_description` are empty, so I'm not sure if anything can be done about it.

2021-10-03 09:46 UTC, Broxzier approved these changes
Tested it with some more saved games, and seems to fix things nicely.

2021-10-03 18:57 UTC, merged

2021-10-04 23:24 UTC, tupaschoal commented
Should this have warranted a changelog entry? Or was introduced in the current version being developed?

2021-10-05 07:00 UTC, Gymnasiast commented
@tupaschoal https://github.com/OpenRCT2/OpenRCT2/pull/15516#discussion_r720730735