Fix #15843; Tile Inspector resizes too small.
OpenRCT2/OpenRCT2 pull request #15860
Opened 2021-11-05 02:16 UTC by rendello

Fix for #15843.

Tile inspector could be resized too small when something was selected. Turns out, `window_tile_inspector_resize()` was needlessly replacing `w->min_height` on every call. Removing this reset (and the `w->min_width` reset for good measure) allows the window's properly computed size to be used.

This replacement had been here since before the file was moved to the current directory in 2017. It's possible I'm being naive here, but it seems to be the way.

2021-11-06 15:24 UTC, Broxzier requested changes
Tested and works as expected. Please add a changelog entry for this fix.

2021-11-06 17:12 UTC, rendello commented
Botched that, please ignore.

2021-11-06 17:50 UTC, Broxzier approved these changes

2021-11-07 11:06 UTC, tupaschoal commented on distribution/changelog.txt
> +- Fix [#15843] Tile Inspector can be resized too small.
```suggestion
- Fix: [#15843] Tile Inspector can be resized too small.
```

2021-11-07 11:24 UTC, merged