Don't load non rct2 assets
OpenRCT2/OpenRCT2 pull request #16077
Opened 2021-11-30 07:58 UTC by duncanspumpkin

We were mistakenly loading rct1 surfaces and sides when loading rct2 parks leading to a confusing ui.

2021-11-30 10:44 UTC, Gymnasiast requested changes
No, this is NOT a mistake. We added the RCT1 sides to SV6 files years ago, and the surfaces one year ago. So they _have_ to be loaded. Otherwise this is going to break thousands of SV6 files created with OpenRCT2 in the past years.

2021-11-30 13:05 UTC, Gymnasiast commented
Shooting the messenger now, are we? Try loading this park on develop and on this PR: [Pickle Park-savetest.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/7625905/Pickle.Park-savetest.sv6.zip)

How it looks on develop:
![](https://media.discordapp.net/attachments/264137540670324737/915226357083045958/develop.png)

How it looks with this PR:
![afbeelding](https://user-images.githubusercontent.com/1478678/144052529-b09c262a-3d27-4677-95a6-c5976f07a05e.png)

2021-11-30 13:09 UTC, pizza2004 commented
> We added the RCT1 sides to SV6 files years ago (#7010), and the surfaces one year ago. So they _have_ to be loaded.

Couldn't you just add a check to see if they're saved in the SV6 file and if not just not load them as defaults?

2021-11-30 13:10 UTC, Gymnasiast commented
> > We added the RCT1 sides to SV6 files years ago (#7010), and the surfaces one year ago. So they _have_ to be loaded.
> 
> Couldn't you just add a check to see if they're saved in the SV6 file and if not just not load them as defaults?

That would work, but it’s not what this PR currently does.

2021-11-30 18:38 UTC, Gymnasiast requested changes
The modified version does not work correctly:

![afbeelding](https://user-images.githubusercontent.com/1478678/144107340-88cc8ffd-3082-4619-8f63-a93839283e0c.png)

Oddly, it seems to add the red roof tiles (a terrain surface) as an edge style. Perhaps it’s going past the end of an array?

2021-12-01 07:51 UTC, duncanspumpkin commented
Okay think thats it fixed 
![image](https://user-images.githubusercontent.com/1277401/144193354-f5faa17c-d610-4a3c-b40f-a1ed611352d1.png)
obviously doesn't look correct on mine since i don't have RCT1 linked but its showing as the brick edge.

2021-12-01 08:04 UTC, duncanspumpkin commented
Hmm looks like there are still a few places with hardcoded offsets:
```
static uint32_t get_surface_image(
    const paint_session* session, ObjectEntryIndex index, int32_t offset, uint8_t rotation, int32_t grassLength, bool grid,
    bool underground)
{
    // Provide fallback for RCT1 surfaces if the user does have RCT1 linked.
    if (!is_csg_loaded() && index >= TERRAIN_RCT2_COUNT)
    {
        if (index == TERRAIN_ROOF_GREY)
            index = TERRAIN_ROCK;
        else
            index = TERRAIN_DIRT;
    }
```

2021-12-01 16:27 UTC, Gymnasiast commented
> Hmm looks like there are still a few places with hardcoded offsets:

We should be able to get of those once I implement the "no csg" fallback.

2021-12-02 19:29 UTC, Gymnasiast commented
Ok, I just tested with a few more SV4 files and hybrid SV6 files.

It looks a bit messy that the selection of land types varies for every hybrid save. The order can also be odd:

![afbeelding](https://user-images.githubusercontent.com/1478678/144489610-ec4e3143-7dc9-41c6-9d51-eb798385ba63.png)

What I would propose as a solution is this: check if the file uses any RCT1 land texture. If it does, load all of them, and in the same order as we do currently. If none of used, only load the RCT2 textures.

2021-12-04 16:43 UTC, duncanspumpkin commented
> Ok, I just tested with a few more SV4 files and hybrid SV6 files.
> 
> It looks a bit messy that the selection of land types varies for every hybrid save. The order can also be odd:
> 
> ![afbeelding](https://user-images.githubusercontent.com/1478678/144489610-ec4e3143-7dc9-41c6-9d51-eb798385ba63.png)
> 
> What I would propose as a solution is this: check if the file uses any RCT1 land texture. If it does, load all of them, and in the same order as we do currently. If none of used, only load the RCT2 textures.

Can you try the latest version it now looks at all the tiles if there are any rct1 land or edges it will load all rct1 land and edges into the file. Saves having to recompute the index as well.

2021-12-04 22:27 UTC, pizza2004 commented on src/openrct2/rct2/S6Importer.cpp
> +            // Find and if any rct1 terrain surfaces or edges have been used
```suggestion
            // Find if any rct1 terrain surfaces or edges have been used
```

2021-12-05 15:39 UTC, Gymnasiast commented on src/openrct2/rct2/S6Importer.cpp
> +                _terrainSurfaceEntries.AddRange(OpenRCT2HybridTerrainEdges);
```suggestion
                _terrainEdgeEntries.AddRange(OpenRCT2HybridTerrainEdges);
```

2021-12-05 16:08 UTC, merged

2022-01-26 21:19 UTC, dannystrayer commented
After this fix, how are we to obtain the RCT1 sides? The castle and urban sides as well as others don't show up in object selection now. I can't figure out how to add those textures to my park

2022-01-26 23:35 UTC, Gymnasiast commented
> After this fix, how are we to obtain the RCT1 sides? The castle and urban sides as well as others don't show up in object selection now. I can't figure out how to add those textures to my park

If they don’t show up in your Object Selection window, then you should probably check if your filters are set correctly. There is a button for those in the top right of the Object Selection window.

2022-01-26 23:39 UTC, dannystrayer commented
> > After this fix, how are we to obtain the RCT1 sides? The castle and urban sides as well as others don't show up in object selection now. I can't figure out how to add those textures to my park
> 
> If they don’t show up in your Object Selection window, then you should probably check if your filters are set correctly. There is a button for those in the top right of the Object Selection window.

Silly mistake! You are correct. Apparently I had LL and CF checked off. Thanks!