Make Looping Coaster draw missing sprites from LIM Launched Coaster
OpenRCT2/OpenRCT2 pull request #16097
Opened 2021-12-03 00:07 UTC by karst

Makes the Looping Coaster draw missing track pieces from the LIM Launch Coaster.

I have been told replacing return nullptr; to return get_track_paint_function_lim_launched_rc would have also done the job, but this seems pretty clear to me and it works!

2021-12-03 07:42 UTC, duncanspumpkin commented
can you address the formatting issues.

2021-12-03 10:33 UTC, Gymnasiast requested changes
> I have been told replacing return nullptr; to return get_track_paint_function_lim_launched_rc would have also done the job, but this seems pretty clear to me and it works!

I still think that’s the best way to go, because it means that, if we added another element to the LIM coaster, the Looping RC will also be able to draw it without having to update LoopingRollerCoaster.cpp. This is why I asked you to do it this way.

2021-12-03 11:29 UTC, karst commented
I for now added the lines like this. Formatting should be correct now (I used tabs instead of spacebars).
This code is consistent to what I found in other 
Can't seem to get the cpp files (like the LIM Launched Coaster itself)

Could not get the adviced line of code to work, as I got the following error. Otherwise I had done it like such.
![image](https://user-images.githubusercontent.com/1516893/144594946-7d5b1921-fe11-401b-9135-ad705bc73f07.png)

For reference:
![image](https://user-images.githubusercontent.com/1516893/144595298-09408bee-68fd-4724-b2d9-bbe130fe94c4.png)

2021-12-03 13:38 UTC, ZehMatt commented on src/openrct2/ride/coaster/LoopingRollerCoaster.cpp
> +            return get_track_paint_function_lim_launched_rc(trackType);
Don't invoke the function, this is supposed to return the function address.

2021-12-03 23:46 UTC, karst commented
> > I have been told replacing return nullptr; to return get_track_paint_function_lim_launched_rc would have also done the job, but this seems pretty clear to me and it works!
> 
> I still think that’s the best way to go, because it means that, if we added another element to the LIM coaster, the Looping RC will also be able to draw it without having to update LoopingRollerCoaster.cpp. This is why I asked you to do it this way.

@Gymnasiast Got it to work in the singular line. :)

2021-12-04 11:10 UTC, Gymnasiast commented
Good, can you also amend the `ExtraTrackPieces` in `LoopingRollerCoaster.h`? That would, people who enable cheats can easily build the elements you added?

2021-12-04 19:41 UTC, karst commented
There we go!

2021-12-05 12:26 UTC, Gymnasiast commented on src/openrct2/ride/coaster/meta/LoopingRollerCoaster.h
> +    SET_FIELD(ExtraTrackPieces, (1ULL << TRACK_SLOPE_VERTICAL) | (1ULL << TRACK_TWIST) | (1ULL << TRACK_CORKSCREW) | (1ULL << TRACK_CURVE_VERTICAL) | (1ULL << TRACK_QUARTER_LOOP) ),
```suggestion
    SET_FIELD(ExtraTrackPieces, (1ULL << TRACK_SLOPE_VERTICAL) | (1ULL << TRACK_TWIST) | (1ULL << TRACK_CORKSCREW) | (1ULL << TRACK_CURVE_VERTICAL) | (1ULL << TRACK_QUARTER_LOOP)),
```

2021-12-05 12:27 UTC, merged