Convert Finances window to new window system
OpenRCT2/OpenRCT2 pull request #16149
Opened 2021-12-07 19:38 UTC by Iikorni

This is my first contribution, so sorry if it's a bit all over the place. I tried to model this refactor after `Cheats.cpp`, so some of the layout might be a bit off.

Closes #13773.

2021-12-11 09:14 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +static rct_widget window_finances_cash_widgets[] =
stick to the old naming it was the most correct following the coding style. This comment goes for all of the static local globals.

2021-12-11 09:15 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +}
include a new line.

2021-12-11 09:19 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +static FinancesWindow* FocusOrCreateFinancesWindow()
I don't really see the point of this function. Is this the style from another window?

2021-12-11 09:24 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +        SetPage(WINDOW_FINANCES_PAGE_SUMMARY);
_lastPaintedMonth should be set to `std::numeric_limits<int32_t>::max()` to force it to be recalculated on first draw.

2021-12-11 09:28 UTC, duncanspumpkin commented
In future try avoid making modifications to the logic whilst you are doing these refactors to class as it makes reviewing much harder. Just do a follow on pr.

2021-12-11 09:32 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +        auto ft = Formatter::Common();
Can you add a comment that this is setting loan widgets format arguments.

As this is done via a global it is very important that nothing else uses the global format arguments until the drawing is complete.

2021-12-11 09:34 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +        if (page == WINDOW_FINANCES_PAGE_SUMMARY)
return early so this isn't all indented.

2021-12-11 09:45 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +    void InitializeScrollPosition(rct_widgetindex widgetIndex, int32_t scrollId)
spelling mistake `InitialiseScrollPosition`

2021-12-11 09:48 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +        int32_t i;
Move this to the for loop as its only used there.

2021-12-11 09:48 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Finances.cpp
> +        rct_widget* dropdownWidget;
no need to declare this early.

2021-12-11 09:49 UTC, duncanspumpkin requested changes
Some minor comments but all looks about there.

2022-02-24 09:17 UTC, Broxzier commented
@Iikorni Are you planning to continue working on this, and would you like some help?

2022-03-01 18:58 UTC, Iikorni commented
@Broxzier My apologies for the late reply - I am still working on this, I just have been far too busy at work to devote the time necessary to fix this up. It will be done soon, hopefully.

2022-03-01 21:19 UTC, Broxzier commented
No worries! If you are getting stuck or need some help, just ask either here or on Discord.

2022-04-15 16:40 UTC, Iikorni commented
I am indeed working on finishing this up now, and it should be done within the next couple of days. Sorry that it's taken so long!

2022-05-04 02:45 UTC, tupaschoal commented
@Iikorni sorry it took us a while, can you go over the line notes that Duncan made and mark them as resolved if you followed exactly the suggestion laid out there?

That makes it easier for us to know where to follow up from.
Thanks!

2022-05-05 06:30 UTC, duncanspumpkin approved these changes

2022-05-05 06:31 UTC, merged