rename VAR_CF
OpenRCT2/OpenRCT2 pull request #16216
Opened 2021-12-13 07:08 UTC by spacek531

2021-12-13 08:23 UTC, duncanspumpkin requested changes
Again doesn't make sense what does seat rotation have to do with brake speed

2021-12-13 08:39 UTC, spacek531 commented
I have no idea but that's the minigolf shadow realm code. Whatever it's trying to read, it's probably not really rotation.

2021-12-13 22:12 UTC, duncanspumpkin commented on src/openrct2/ride/Vehicle.cpp
> +    brake_speed = tileElement->AsTrack()->GetSeatRotation() << 1;
![image](https://user-images.githubusercontent.com/1277401/145897177-982c6c49-3978-46a2-b022-dde42b857a7c.png)
Looks like this was wrong it should have been:
```
brake_speed = tileElement->AsTrack()->GetBrakeBoosterSpeed();
```

2021-12-13 22:13 UTC, duncanspumpkin commented
Make my change and then that is all users of CF being correct and related to brake booster speed. Also you will need to bump the network version when you make my change.

2021-12-14 07:25 UTC, merged

2021-12-14 13:07 UTC, ZehMatt commented on src/openrct2/ParkFile.cpp
> +        cs.ReadWrite(entity.brake_speed);
In the future use
```PascalCase``` for public variable names