rename VAR_C4
OpenRCT2/OpenRCT2 pull request #16217
Opened 2021-12-13 07:23 UTC by spacek531

2021-12-13 08:22 UTC, duncanspumpkin requested changes
This one clearly does not make sense. What on earth does direction < 200 mean

2021-12-13 09:07 UTC, spacek531 commented
Looking at it further, it appears it has one alternate use for the following specific cases:
- unsticking go karts colliding while changing lanes while MovingToEndOfStation
- unsticking boats that have become stuck in each other while TravellingBoat

So I would say it is also CollisionDetectionTimer

2021-12-14 07:35 UTC, duncanspumpkin commented
If its used for two purposes then I'd prefer a union for those two purposes.

2022-02-19 10:01 UTC, spacek531 commented
I have rebased to the current develop. Is there anything else that needs to be done before this can be merged?

2022-02-19 13:21 UTC, duncanspumpkin commented on src/openrct2/rct2/RCT2.h
> +        uint8_t CollisionDetectionDirection; // 0xC4
Readd the union here

2022-02-19 13:22 UTC, duncanspumpkin commented on src/openrct2/ride/Vehicle.h
> +        uint8_t CollisionDetectionDirection;
Rename back to DodgemsCollisionDirection so we know its only used for dodgems.

2022-02-19 13:23 UTC, duncanspumpkin commented on src/openrct2/ride/Vehicle.cpp
> +    stream << CollisionDetectionDirection;
As the majority of users will be the timer switch all the things not dodgem related to use the CollisionDetectionTimer

2022-02-21 07:49 UTC, duncanspumpkin approved these changes

2022-02-22 23:14 UTC, merged