Refactor window to class: TrackDesignPlace
OpenRCT2/OpenRCT2 pull request #16669
Opened 2022-02-15 11:04 UTC by 94794

Should do #13811.

2022-02-16 02:39 UTC, tupaschoal reviewed
Hello @94794 and welcome to the project!
It seems like there is a merge conflict with one of the files you touched. Can you sort it out so we can get on with the reviewing?
If you need help, let us know here or over on our Discord server.

2022-02-16 16:57 UTC, 94794 commented
Sorry for the mess, accidentally merged the develop into the fix branch.

Should be ready now.

2022-02-25 07:32 UTC, duncanspumpkin commented on src/openrct2-ui/windows/TrackDesignPlace.cpp
> +        window = WindowCreate<TrackDesignPlaceWindow>(WC_TRACK_DESIGN_PLACE, WW, WH, 0);
There is a `WindowFocusOrCreate` that you can use to handle the window_bring_to_front_by_class all as a oner.

2022-02-25 07:36 UTC, duncanspumpkin commented on src/openrct2-ui/windows/TrackDesignPlace.cpp
> +    _trackDesign = TrackDesignImport(tdFileRef->path);
the trackdesign should become owned by the window. I suggest you add a public method to the window called `Initialise(std::unique_ptr<TrackDesign>&& trackDesign)` and you move the loaded track design into the window.

2022-02-25 07:40 UTC, duncanspumpkin commented on src/openrct2-ui/windows/TrackDesignPlace.cpp
> -static void WindowTrackPlaceInvalidate(rct_window* w)
This has gone missing. It should become `OnPrepareDraw`

2022-02-25 07:49 UTC, duncanspumpkin commented on src/openrct2-ui/windows/TrackDesignPlace.cpp
> +static CoordsXYZ _windowTrackPlaceLastValid;
In general we are wanting to move all of these static variables into the window. You will need to modify the functions that use these directly from other places e.g. `TrackPlaceClearProvisionalTemporarily` and `TrackPlaceRestoreProvisional` make it so those functions find the track window with `window_find_by_class` and then call a public function.

```cpp
void TrackPlaceClearProvisionalTemporarily(){
    auto* trackPlaceWnd = static_cast<TrackDesignPlaceWindow*>(window_find_by_class(WC_TRACK_DESIGN_PLACE));
    if (trackPlaceWnd != nullptr){
        trackPlaceWnd->TrackPlaceClearProvisionalTemporarily();
    }
}

2022-02-25 07:51 UTC, duncanspumpkin commented on src/openrct2-ui/windows/TrackDesignPlace.cpp
> +    void WindowTrackPlaceDrawMiniPreview(TrackDesign* td6)
For all of the methods that are now part of the class you should drop the `WindowTrackPlace`

2022-02-25 07:52 UTC, duncanspumpkin requested changes
Sorry it took a while to get around to reviewing. This all looks fine but a few little changes to be made.

2022-03-05 14:35 UTC, 94794 commented
Should be ok now.

2022-03-05 14:52 UTC, duncanspumpkin commented
I've squashed this down and rebased it so that its easier to understand.

2022-03-05 15:06 UTC, duncanspumpkin commented
I had a little play about with this and it all seems to work.

2022-03-05 15:06 UTC, duncanspumpkin approved these changes

2022-03-05 15:26 UTC, merged