Fix crash where peeps enter through extra ride entrances
OpenRCT2/OpenRCT2 pull request #16727
Opened 2022-02-27 05:05 UTC by csm10495

This should fix #16170 and #16177. 

WIth this change the peep gets on the ride... and exits after over as expected. No crash. :)

2022-02-27 18:02 UTC, csm10495 commented
I think cheats were still used to add the extra entrances. Once they were added the game could crash if guests used them at certain times.

This change fixes that crash.

I'm still not 100% sure how they added multiple entrances. I just debugged from the given save file.

2022-02-27 18:20 UTC, ZehMatt commented
They probably used the Tile Inspector to copy the element. And no this probably doesn't make them usable.

2022-02-27 18:22 UTC, csm10495 commented
100% sure guests used at least one of them. Before this change, it would crash when a guest used it at a certain time.

2022-02-27 18:43 UTC, ZehMatt commented
I'm not sure that this is the right way to fix it, anyway @duncanspumpkin self requested a review he knows this part of the code a lot better.

2022-02-27 19:39 UTC, Broxzier commented
Rides can only have one functional entrance and exit per station. I assume that this bug occurred because a guest happened to bump into the non-usable one and decided to enter the ride then. A proper way of handling this is to check if the entrance used matches the coordinates and direction of the station entrance that the ride expects.

2022-02-28 00:44 UTC, csm10495 commented
The ride state for this guest (without this PR changes):
![image](https://user-images.githubusercontent.com/5749838/155907335-f2235724-81d7-4e50-bd85-37a89cdf89bb.png)

So we're walking then we're queuing, then we're queuing in front, then we enter... then somehow go back and forth between queuing in front and entering..

Maybe we should make it so they can only queue (and queue front) if in the correct queue. I'm not that familiar with the code... how / where could we check for that?

2022-03-06 00:32 UTC, csm10495 commented
@duncanspumpkin any guidance here?

2022-03-06 07:59 UTC, duncanspumpkin commented
In what situation do you see this as being valid. We added the assert because the state is clearly not meant to become possible. All you are doing is overriding the assert which is not a clever idea. The issue is upstream of this. When you are inEntrance the next state you are meant to go to is `FreeVehicleCheck` by leaving the entrance without doing the vehicle check you are causing invalid state to be now passed into the next bit of code that handles entering a vehicle. From a quick look you will: mess up the ride profit as they wont pay for entrance; potentially void the peep if the vehicle is already occupied; potentially corrupt the ride peeps.

 The only logical solution here is that if the peep is `InEntrance` at this point then its to always go to the `FreeVehicleCheck` not to skip that state and go straight to `LeaveEntrance`. And if you are doing that then the assert is no longer needed.

2022-03-06 08:01 UTC, duncanspumpkin requested changes

2022-03-06 08:01 UTC, duncanspumpkin commented on src/openrct2/entity/Guest.cpp
>      Guard::Assert(RideSubState == PeepRideSubState::LeaveEntrance, "Peep ridesubstate should be LeaveEntrance");
remove

2022-03-06 08:01 UTC, duncanspumpkin commented on src/openrct2/entity/Guest.cpp
> +    else if (RideSubState == PeepRideSubState::InEntrance)
remove else not related to the above.

2022-03-06 08:01 UTC, duncanspumpkin commented on src/openrct2/entity/Guest.cpp
> +        RideSubState = PeepRideSubState::LeaveEntrance;
This is unsafe should perform `FreeVehicleCheck` then immediately return from this function.

2022-03-11 03:11 UTC, csm10495 commented
@duncanspumpkin , mind checking once more? I think I did what you asked. Thanks again.

2022-03-11 05:45 UTC, duncanspumpkin commented on src/openrct2/entity/Guest.cpp
>      Guard::Assert(RideSubState == PeepRideSubState::LeaveEntrance, "Peep ridesubstate should be LeaveEntrance");
You can remove this assert now.

2022-03-11 10:30 UTC, duncanspumpkin commented
Remove the assert and bump the network version and this is good to go.

2022-03-11 10:36 UTC, Legotown55 commented
How do you add second entrance to a ride

2022-03-11 10:40 UTC, Broxzier commented
@Legotown55 please keep questions and unrelated comments to discussions and our Discord server.

2022-03-12 03:59 UTC, csm10495 commented
@duncanspumpkin done. One more check time hopefully. Thanks!

2022-03-12 06:29 UTC, duncanspumpkin approved these changes

2022-03-13 23:58 UTC, csm10495 commented
@duncanspumpkin can you merge this?

2022-03-14 06:21 UTC, duncanspumpkin commented
I was waiting on a different pr to be merged first. Could you rebase as the other pr is now merged

2022-03-15 02:38 UTC, csm10495 commented
Sorry I didn't know that you were waiting on another pr. I've rebased this to latest develop.

2022-03-15 06:39 UTC, merged