Reducing allocations in image table
OpenRCT2/OpenRCT2 pull request #16798
Opened 2022-03-15 08:34 UTC by duncanspumpkin

Aim of this PR is to change the ImageTable so that it works as follows:

1. An ImageTable will either own image data or reference data allocated to g1/g2/csg.
2. All owned image data will be allocated in one contiguous block.

A follow on PR will rework the spritesheet so that it is read as one image instead of multiple images forcing one palette across the whole image.

As it currently stands an ImageTable always owns its data but this is duplicating data if it references g1/g2/csg. In addition all data owned is in separate allocations leading to fragmentation and multiple users of `new` / `delete`.

2022-03-15 19:53 UTC, duncanspumpkin commented on src/openrct2/object/ImageTable.cpp
> +            _entries.push_back(std::move(g1Element));
Can preallocate to numImages

2022-03-16 21:35 UTC, Gymnasiast requested changes
This code crashes on my system (Ubuntu 20.04):

```
Thread 1 "openrct2" received signal SIGSEGV, Segmentation fault.
0x0000555556220e5b in DrawRLESpriteMinify<1, 0> (dpi=..., args=...)
    at /home/michael/Code/OpenRCT2/OpenRCT2/src/openrct2/drawing/Drawing.Sprite.RLE.cpp:113
113	        uint16_t lineOffset = src0[y * 2] | (src0[y * 2 + 1] << 8);
(gdb) bt full
#0  0x0000555556220e5b in DrawRLESpriteMinify<1, 0> (dpi=..., args=...)
    at /home/michael/Code/OpenRCT2/OpenRCT2/src/openrct2/drawing/Drawing.Sprite.RLE.cpp:113
        y = 0
        lineOffset = 0
        nextRun = 0x5555559bf863
     <std::_Optional_payload<PaletteMap, true, true, true>::_Optional_payload_base<PaletteMap>(std::in_place_t, PaletteMap&&)+39> "\220\311\303\363\017\036\372UH\211\345SH\203\354\030H\211}\350H\211u\340H\213]\350H\213E\340H\211\307\350\237\377\377\377H\211\306H\211\337\350\246\377\377\377\220H\203\304\030[]\303\363\017\036\372UH\211\345H\211}\370H\213E\370]\303\363\017\036\372UH\211\345SH\203\354\030H\211}\350H\211u\340H\213E\340H\211\307\350\315\377\377\377H\211\303H\213E\350H\211\307\350H\004"
        dstLineStart = 0x7fffffffd020 "\206\"K\315\377\177"
        isEndOfLine = 85
        i = 0
        src0 = 0xffff4e94a4a7 <error: Cannot access memory at address 0xffff4e94a4a7>
        dst0 = 0x55555d2522b0 ""
        srcX = 0
        srcY = 0
        width = 56
        height = 25
--Type <RET> for more, q to quit, c to continue without paging--
        zoom = 1
        dstLineWidth = 56
#1  0x000055555621d92e in DrawRLESprite<1> (dpi=..., args=...)
    at /home/michael/Code/OpenRCT2/OpenRCT2/src/openrct2/drawing/Drawing.Sprite.RLE.cpp:193
        __PRETTY_FUNCTION__ = "void DrawRLESprite(rct_drawpixelinfo&, const DrawSpriteArgs&) [with unsigned char TBlendOp = 1]"
        zoom_level = 0 '\000'
#2  0x000055555621d59a in gfx_rle_sprite_to_buffer (dpi=..., args=...)
    at /home/michael/Code/OpenRCT2/OpenRCT2/src/openrct2/drawing/Drawing.Sprite.RLE.cpp:235
No locals.
#3  0x00005555559be1f3 in gfx_sprite_to_buffer (dpi=..., args=...)
    at /home/michael/Code/OpenRCT2/OpenRCT2/src/openrct2/drawing/Drawing.Sprite.cpp:585
No locals.
```

2022-03-16 22:20 UTC, duncanspumpkin commented
#16806 can go in before this whilst i work at ironing out any bugs.

2022-03-16 22:23 UTC, duncanspumpkin commented
> This code crashes on my system (Ubuntu 20.04):

It would help if i didn't destroy zoom references. Doh!

2022-11-04 07:24 UTC, duncanspumpkin commented
Closing as I basically decided that this was a much more complex problem.

2022-11-04 07:24 UTC, closed without merging