Add ability for plugins to access ride's chain lift speed
OpenRCT2/OpenRCT2 pull request #16800
Opened 2022-03-16 00:31 UTC by csm10495

2022-03-16 06:52 UTC, Broxzier requested changes

2022-03-16 06:52 UTC, Broxzier commented on distribution/openrct2.d.ts
> +        lift_hill_speed: number;
Please change this to use camel Case for variables. This also applies to the rest.

2022-03-16 06:52 UTC, Broxzier commented on src/openrct2/scripting/bindings/ride/ScRide.cpp
> +    uint8_t ScRide::lift_hill_speed_get() const
```suggestion
    uint8_t ScRide::liftHillSpeed_get() const
```

2022-03-17 00:40 UTC, csm10495 commented
@Broxzier I updated the PR thanks.

2022-03-20 15:00 UTC, Broxzier reviewed
I've rebased this PR, added a changelog entry and incremented the API version. Found one more thing to improve on, since the numbers did not match when the game was set to use the metric system.

2022-03-20 15:20 UTC, merged

2022-03-20 21:24 UTC, Broxzier commented
@csm10495 I noticed that you worked directly on the `develop` branch for this PR. While that works, it makes it more difficult for you to manage your branches, especially now that it has been merged. It's best if you reset your branch to match the OpenRCT2 repository, and that you work on feature branches for future PRs.