Add parameters to accept for StaffFireAction
OpenRCT2/OpenRCT2 pull request #16816
Opened 2022-03-18 02:54 UTC by csm10495

Without this, plugins can call stafffire, but they can't set whom to fire.

2022-03-18 07:27 UTC, duncanspumpkin commented
Could you bump the plug-in api version

2022-03-18 09:26 UTC, IntelOrca requested changes

2022-03-18 09:26 UTC, IntelOrca commented on src/openrct2/actions/StaffFireAction.cpp
> +    visitor.Visit("spriteId", _spriteId);
```suggestion
    visitor.Visit("id", _spriteId);
```

2022-03-19 00:50 UTC, csm10495 commented
Updated. Thanks folks.

2022-03-19 07:55 UTC, duncanspumpkin approved these changes

2022-03-20 10:19 UTC, tupaschoal reviewed
Ok to merge this @IntelOrca ?

2022-03-20 10:54 UTC, IntelOrca approved these changes

2022-03-20 11:59 UTC, merged