Ride operating settings can be set via text input
OpenRCT2/OpenRCT2 pull request #17107
Opened 2022-04-30 14:33 UTC by rik-smeets

Both minimum and maximum wait time and operating settings for flat rides can now be set via text input.

2022-04-30 21:42 UTC, frutiemax commented on src/openrct2-ui/windows/Ride.cpp
> +    uint8_t upper_bound = 250;
Why 250? Can you use an existing constant or create one so it is more verbose?

2022-04-30 21:42 UTC, frutiemax commented on src/openrct2-ui/windows/Ride.cpp
> +    uint8_t maxValue = gCheatsUnlockOperatingLimits ? 255 : operatingSettings.MaxValue;
255, would use a constant also there to be more verbose.

2022-04-30 21:42 UTC, frutiemax commented on src/openrct2-ui/windows/Ride.cpp
> +        uint8_t maxValue = gCheatsUnlockOperatingLimits ? 255 : operatingSettings.MaxValue;
constant

2022-04-30 21:42 UTC, frutiemax commented on src/openrct2-ui/windows/Ride.cpp
> +            uint16_t upper_bound = 250;
constant

2022-06-10 01:27 UTC, tupaschoal reviewed
Can you please fix merge conflicts and also add screenshots of before/after?

2022-06-11 06:11 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Ride.cpp
> +            WindowRideOperatingTweakWindow(w, *ride);
I don't quite see why you have used the suffix Window. That would imply that its creating a special operating tweak window but this is just opening the standard text input window.

2022-06-11 06:14 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Ride.cpp
> +            uint16_t lower_bound = 0;
Snake case should not be used. It is only in old code that hasn't been refactored.

2022-06-11 06:15 UTC, duncanspumpkin commented on src/openrct2-ui/windows/Ride.cpp
> +            uint16_t lower_bound = 0;
Try keep the two branches as similar as possible in terms of layout, variable name, etc.

2022-06-11 06:16 UTC, duncanspumpkin commented
> Can you please fix merge conflicts and also add screenshots of before/after?

As it's just adding some text input window i don't see the need for screenshots.

2022-07-04 21:05 UTC, Gymnasiast commented
LGTM. Could you rebase? Make sure to get the changelog right, as we released v0.4.1 in the meantime.

2022-07-05 17:20 UTC, rik-smeets commented
Done, I also fixed the changelog :).

2022-07-10 10:52 UTC, Gymnasiast requested changes
OK, I finally got around to testing this.

- The old value is not entered in the input box (it does so for e.g. setting prices)
- It doesn’t allow setting the number of rotations for a Twist
- It doesn’t allow setting the time limit for Dodgems

2022-07-27 21:13 UTC, Gymnasiast approved these changes

2022-07-27 21:14 UTC, Gymnasiast commented
While solving point 1, I noticed why you didn’t do point 2. I think there is too much special code to handle the Twist anyway, so that is better left for another PR.

2022-07-27 21:39 UTC, merged

2022-07-28 09:02 UTC, rik-smeets commented
Thanks for completing this PR @Gymnasiast , I didn't get around to it yet due to vacation.