Proposal improvement for water & shorelines in map generation
OpenRCT2/OpenRCT2 pull request #17242
Opened 2022-05-20 04:14 UTC by krrg

The current shorelines created by the map generator can be a bit strange in appearance because the water "overfills" up to the height of the surrounding land. A more natural appearance is to have the shore slope down towards the water, thus always having bodies of water appear _below_ the height surrounding land. This sloped down shoreline appearance is used in (from what I can tell) all the original scenarios as well as TTD/OpenTTD.

My proposed solution: at the step of map generation where each tile is being filled with water, if a tile is selected to be filled with water, then move its base height down a level and fill the water up 1 less than what it would do previously. Because this adjustment creates a sheer cliff, run the map smoothing algorithm again to create a smoothed out natural looking shoreline.

**Current Shoreline Behavior:**
![image](https://user-images.githubusercontent.com/8496492/169448523-c73c33ed-bec8-4213-aefb-878d855d02c0.png)

**New Shoreline Behavior:**
![image](https://user-images.githubusercontent.com/8496492/169448623-89f01ef8-3199-4cb5-8352-41475d1dd6ec.png)

Any feedback or thoughts on how this might be done better is very welcome!

2022-05-20 09:00 UTC, IntelOrca approved these changes

2022-05-20 10:04 UTC, Broxzier requested changes
Nice change, I think this could use a changelog entry.

2022-05-21 07:10 UTC, krrg commented
After doing some additional testing, I've discovered a minor flaw in this approach. When we raise the water and then run the smoothing function again, the smoother will raise land up above the water level, but will still leave the water "underground". So raising the water needs to be the last step as the smoothing function can't be run after the water has been raised.

So, I think what I'll need to do is first identify all the candidate tiles that we expect to put water on, then lower them down, then run the smoothing to create the right slopes, _then_ rescan all the tiles looking for candidate water pieces and finally raise the water level up as appropriate. A few more steps, but doable enough. I'll go ahead and get that worked out and push an update.

2022-05-21 09:50 UTC, Broxzier commented
I think you can simply lower the surface tiles that are below the water level right after calling `mapgen_set_height`, but before smoothing it the first time. Smoothing the map afterwards does not flatten any surfaces.

2022-05-21 09:58 UTC, Broxzier commented
Just tested it locally. Passing the mapgen settings (or even just the water height) to `mapgen_set_height`, and adding this bit right after setting the base height creates the desired shores:

```cpp
if (surfaceElement->base_height > 2 && surfaceElement->base_height <= settings->water_level)
    surfaceElement->base_height -= 2;
```

2022-05-21 18:24 UTC, krrg commented
I like that approach; simple and straightforward, plus it avoids having `mapgen_set_water_level` do "more" than it probably should. I've gone ahead and updated with those changes :+1:

2022-05-21 18:37 UTC, Broxzier approved these changes

2022-05-22 06:05 UTC, merged

2022-05-25 00:30 UTC, krrg commented
Whoops :) https://github.com/OpenRCT2/OpenRCT2/pull/17280