Fix upper_case_banners options
OpenRCT2/OpenRCT2 pull request #17417
Opened 2022-06-20 14:03 UTC by Artemyanen

One liner for #17380
Option `upper_case_banners` used couple of places to calculate new width for scrolling text:

- https://github.com/OpenRCT2/OpenRCT2/blob/269673e3aa40923337f2cde1d7744a5cf5fc0615/src/openrct2/paint/tile_element/Paint.Banner.cpp#L55
- https://github.com/OpenRCT2/OpenRCT2/blob/37c0fffb9902d12814b51e3166191bdd2a5267e0/src/openrct2/paint/tile_element/Paint.Entrance.cpp#L64
- https://github.com/OpenRCT2/OpenRCT2/blob/e78c29ea5c5b2f301ae8d7d1518c11d01174b516/src/openrct2/paint/tile_element/Paint.Wall.cpp#L198
- https://github.com/OpenRCT2/OpenRCT2/blob/fc2ed95641eca0ce60e0a0ae596983f120edea1c/src/openrct2/paint/tile_element/Paint.LargeScenery.cpp#L319

Method `scrolling_text_invalidate()` is invoked in multiple actions to re-create string for sprite:
- [ParkSetNameAction.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2/actions/ParkSetNameAction.cpp)
- [BannerSetNameAction.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2/actions/BannerSetNameAction.cpp)
- [SignSetNameAction.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/c0474d2d276c15243c6a4cd0d902c26f54385fbc/src/openrct2/actions/SignSetNameAction.cpp)
- [RideSetNameAction.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/c0474d2d276c15243c6a4cd0d902c26f54385fbc/src/openrct2/actions/RideSetNameAction.cpp)

But scrolling text is not invalidated on `upper_case_banners` option change.
This fix should add this behavior to checkbox click.

2022-06-20 22:25 UTC, Gymnasiast commented
This does not seem to be a solution for #17380. But it might be one for https://github.com/OpenRCT2/OpenRCT2/issues/15787.

2022-06-21 10:12 UTC, Artemyanen commented
Although the quality of GIFs is not the best here you can see some testing of this fix. @Gymnasiast 

Before:
- Create 2 banners with `upper_case_banners` off
- Turn `upper_case_banners` on
-> Text doesn't become upper case
- Create one more banner with `upper_case_banners` on
-> Banner created with lower case text
- Toggle  `upper_case_banners` on/off multiple times
-> Banner text case doesn't change
![before](https://user-images.githubusercontent.com/27143015/174774502-d3f995db-00c4-4885-8f0e-00b690263df7.gif)

After:
- Create 2 banners with `upper_case_banners` off
- Turn `upper_case_banners` on
-> Text changes to upper case
- Turn `upper_case_banners` off
-> Text changes to lower case
- Create one more banner
-> Created with upper/lower depending on `upper_case_banners` option
![after](https://user-images.githubusercontent.com/27143015/174774538-b49d2466-cd8a-4c82-abf1-d8e3037d87b4.gif)

2022-06-21 10:18 UTC, Artemyanen commented
So I'd say it's resolving both of these issues.
Before the fix, when color was changed the sprite was invalidated and re-drawn correctly (from lower to upper or vice versa).
After the fix the case is going to be displayed correctly at all times, so color change will just change the color.
So it should fix #17380 too.

cc @Gymnasiast

2022-06-21 11:26 UTC, Broxzier requested changes
LGTM, please add a changelog entry mentioning both issues.

2022-06-21 18:36 UTC, Gymnasiast commented
Ok, I checked that issue a bit more and concluded that colour has nothing to do with it, and that #17380 is nothing more than a vague duplicate of #15787.

2022-06-21 18:37 UTC, merged