#17735 Track elements are listed twice when building backwards
OpenRCT2/OpenRCT2 pull request #17772
Opened 2022-08-10 16:16 UTC by jazzysoggy

#17735

Issue: Track elements are listed twice when building backwards starting from an upside element

Fix: Instead of checking whether bank has the value TRACK_BANK_UPSIDE_DOWN, instead check bank_start, as bank is not guaranteed to be bank_start.

2022-08-16 19:46 UTC, Broxzier requested changes

2022-08-16 19:46 UTC, Broxzier commented on distribution/changelog.txt
>  - Fix: [#17639] When building upside down, the special elements list contains many items twice (original bug).
Just add the issue number to this one, it's the same bug.
```suggestion
- Fix: [#17639, 17735] When building upside down, the special elements list contains many items twice (original bug).
```

2022-08-16 19:46 UTC, Broxzier commented on distribution/changelog.txt
> +- Fix: [#17735] When building from an upside down element, the special elements list contains many items twice.
Remove this line.

2022-08-16 23:50 UTC, jazzysoggy commented on distribution/changelog.txt
> +- Fix: [#17735] When building from an upside down element, the special elements list contains many items twice.
Removed extra line

2022-09-06 21:17 UTC, Broxzier approved these changes

2022-09-06 21:21 UTC, merged