Fix guests leaving queue if other guest rejoins it from entrance building
OpenRCT2/OpenRCT2 pull request #17788
Opened 2022-08-12 07:00 UTC by rik-smeets

If another guest returns to the queue from the entrance building, guests arriving at the entrance building through the queue could decide to leave it.

**Before:**
![OpenRCT2 Guests leaving queue at entrance](https://user-images.githubusercontent.com/30838294/184301351-74a698ae-8791-47dd-80b5-52dc8b15f6be.gif)

**After:**
![OpenRCT2 Guests not leaving queue at entrance](https://user-images.githubusercontent.com/30838294/184301361-b41dc5c6-fd8e-4e40-b2b0-63e9971f9e7c.gif)

2022-08-12 07:47 UTC, Broxzier commented
Thus may also fix the issue where a rude gets multiple queues.

2022-08-17 16:45 UTC, Broxzier requested changes
Changes look good, but since this affects entities, the network version has to be updated.

2022-08-22 17:55 UTC, rik-smeets commented
@Broxzier Network version has been updated. Some of my other PR's have updated versions too, so let's see which one is first to be completed...

2022-08-28 09:40 UTC, rik-smeets commented
> This may also fix the issue where a rude gets multiple queues.

Just tested that and unfortunately, it does not.

2022-08-28 18:17 UTC, Broxzier commented
> Alright, thanks for testing this too!

2022-08-28 18:17 UTC, Broxzier approved these changes

2022-08-29 18:57 UTC, merged