Allow Active Tab of a Custom Window To Be Changed Through Script
OpenRCT2/OpenRCT2 pull request #17887
Opened 2022-08-23 19:11 UTC by jazzysoggy

#17868

Enhancement: Active Tab of a Custom Window can now be changed through a new function named ``tabIndex_set``

2022-08-24 09:03 UTC, IntelOrca commented on src/openrct2-ui/scripting/ScWindow.hpp
> +        void tabIndex_set(size_t tab) const
```suggestion
        void tabIndex_set(int32_t tab) const
```

2022-08-24 18:57 UTC, Basssiiie commented
You'll need to register the setter [here](https://github.com/OpenRCT2/OpenRCT2/blob/344cb6e25ada5656143d9051a04f081370978c75/src/openrct2-ui/scripting/ScWindow.hpp#L339) as well, otherwise it won't work. You have tested it, right?

Oh and the plugin API version needs to be incremented as well. :)

2022-08-24 20:25 UTC, IntelOrca approved these changes

2022-08-24 20:27 UTC, IntelOrca requested changes
As @Basssiiie pointed out, you need to register the setter

2022-08-24 23:38 UTC, jazzysoggy commented
@Basssiiie It's not tested since I don't really know how to use the Plugin API. So I'm not sure if it works the way it should

2022-08-25 19:32 UTC, Sadret commented
Seems to work fine, but the game crashes when an invalid tab index is provided. Make sure to validate the input.

2022-08-25 20:21 UTC, jazzysoggy commented
Added a validation check for tab index

2022-08-27 18:29 UTC, IntelOrca approved these changes

2022-08-31 21:12 UTC, Gymnasiast commented on distribution/changelog.txt
> +- Improved: [#17868] [Plugin] You can now change active tab of a custom window programmatically
```suggestion
- Improved: [#17868] [Plugin] You can now change active tab of a custom window programmatically.
```

2022-08-31 21:13 UTC, merged

2022-09-05 18:06 UTC, Sadret commented
I'm on current develop (97bc2b5) and this does not seem to work.

2022-09-05 19:33 UTC, Gymnasiast commented
@Sadret Please create an issue for that.