Steep track peices for log flumes
OpenRCT2/OpenRCT2 pull request #17997
Opened 2022-09-09 23:42 UTC by karst

I was thinking for a little while how to add these as this is a feature people have been looking for for quite a bit so I decided to get a start on this make the first few sprites and then pressure myself to make more pieces by having a PR open for it. 

This is basically the idea.
![image](https://user-images.githubusercontent.com/1516893/189458507-bc211729-c4fa-4ca1-8ded-25acb17ec6cb.png)
ᶜᵒⁿᶜᵉᵖᵗ ᵃʳᵗ

To get this working I am photoshopping the Splash Boats flume to fit retrofit on the log flume. 

To Do List
----------
- [x] Make pieces for SW-NE (Can I get the other set working by just mirroring them?)
- [ ] Make pieces for NW-SE
- [ ] Make pieces for NE-SW 
- [ ] Make pieces for SE-NW
- [ ] Get pieces working in game
- [ ] Check bounding boxes
- [ ] Add pieces to extra track pieces in meta file (unless someone manages to update the log flume's sprites to fit on 60 degree 
- [ ] Add changelog entry

If I am forgetting anything let me know, if you want to help me out with any of this tag me on discord (especially if someone would like to see if they can add more sprites to the vehicles).

2022-09-10 04:14 UTC, karst commented
Vanilla g1 palette isn't working correctly in g2. I believe #16538 is gonna be necessary to get the sprites to match perfectly.

2022-09-10 04:37 UTC, spacek531 commented
If you save the sprites as 8-bit using that branch it isn't necessary to be merged, simply annoying

2022-10-05 21:36 UTC, Gymnasiast commented
Any news on this?

2022-10-06 01:05 UTC, karst commented
Yea i wanted to pick this up soon, i need to recover from jetlag first tho :)

2022-10-11 19:21 UTC, karst commented
Okay, I have got everything functional in game now.
![image](https://i.gyazo.com/3e317833be30528c26c6a7c8dea3621c.gif)

Enough work for today, up next are bounding boxes, supports, pixel fixes and shading fixes.

2022-10-25 22:08 UTC, karst commented
After hours of testing I have finally completed the first permanent piece. The rest should be straight forward after this but I am gonna have to recreate the from scratch. 
https://i.gyazo.com/92322a0d70dfc8fa4ca3c430a0f1c537.gif

In the end I have completed the edit in about 5 minutes so it's gonna take me a day off sometime to get all these textures to work and look properly.

2022-10-27 14:55 UTC, karst commented
There of the four angles are now complete. I have tried fixing shading, as there's a lot of ugly vanilla shading, but this definitely looks a lot better.
**PICS!!!**
![NWSE Front](https://user-images.githubusercontent.com/1516893/198323358-a8933761-35c0-4efb-8873-a35a8767b46d.png)

![NESW Front](https://user-images.githubusercontent.com/1516893/198323494-68c11d58-170d-41a1-b41f-fc00b91dc96e.png)

![NESW Back](https://user-images.githubusercontent.com/1516893/198323664-d4353236-7df3-49e5-8457-5d39731adb65.png)

Please ignore the supports! I haven't worked at all on these yet.

2022-11-06 00:04 UTC, karst commented
Getting near to finishing, all that's left to do is bounding boxes.

2022-11-06 01:48 UTC, karst commented
Sadly the supports on the back do not correctly, I left it like this if someone wants to fix that in the future (Rik perhaps). It's a bug that also occurs on something like the Dinghy slide. 
![image](https://user-images.githubusercontent.com/1516893/200150291-df70ecc8-d758-4e0f-8b75-9e55ee2097f5.png)

Let me know if there's anything I missed that needs fixing.

2022-11-06 10:30 UTC, 733737 commented
will the custom log be added to the game, that way we could enable steep hills without cheats...

2022-11-06 22:54 UTC, karst commented
![image](https://user-images.githubusercontent.com/1516893/200199738-d9c3b51c-d718-455c-ba65-f63242b63130.png)
![image](https://user-images.githubusercontent.com/1516893/200199744-89448ea7-6dbd-4326-89e3-362952acd712.png)
![image](https://user-images.githubusercontent.com/1516893/200199755-3036d5a6-bfc8-4d37-a38b-6a5d58abc577.png)
![image](https://user-images.githubusercontent.com/1516893/200199759-1fdb0726-7b23-4855-bdbc-8e196f635ed8.png)
@Basssiiie  I have made the flume 2 px smaller at the back as requested. I have also fixed some more shading/line up issues. And no I have not been able to adjust the angle for obvious reasons 😬

2022-11-10 21:13 UTC, Gymnasiast commented on src/openrct2/ride/water/meta/LogFlume.h
> +    SET_FIELD(Heights, { 10, 24, 7, 9, }),
Why was this changed?

2022-11-10 21:28 UTC, Gymnasiast requested changes
There are a few stray pixels here.
![afbeelding](https://user-images.githubusercontent.com/1478678/201208825-f7cd7732-4c3b-4eb1-8608-df71d56e1850.png)

The far side has orange colouring here on the steep sections, even though the rest of it does not:
![afbeelding](https://user-images.githubusercontent.com/1478678/201209078-c649f9d7-85c7-446f-900c-a6d37ab99d76.png)

To a lesser extent, this also happens from another viewpoint:
![afbeelding](https://user-images.githubusercontent.com/1478678/201209125-8c2bc9b7-36cb-4be8-824e-a1154dafe31e.png)

And we’ll have to find some sort of solution for this (I know it’s not technically caused by this PR):
![afbeelding](https://user-images.githubusercontent.com/1478678/201209550-c4bd1b4a-0859-411d-abe6-9c370a2972e2.png)

2022-11-10 22:24 UTC, karst commented
I have addressed the top three, including this ugly mess
![image](https://user-images.githubusercontent.com/1516893/201218725-b6162653-06c5-4be4-8c2c-0f703cca046f.png)
(I sent that one to the fitness so it could get a bit more muscle)

I think the bottom one should be addressed another time in a seperate PR. I will check if there's been a bug report for it and if not report it.

2022-11-12 17:58 UTC, Gymnasiast requested changes
Still a few stray pixels here:

![afbeelding](https://user-images.githubusercontent.com/1478678/201488128-1863f919-c471-4902-9406-84e705eb4880.png)

2022-11-12 18:00 UTC, Basssiiie commented
This blue seems off as well, if it hasn't been fixed already.

![image](https://user-images.githubusercontent.com/20048660/201488195-93d6c84f-75a3-4bfc-a853-9da00cbed2c0.png)

2022-11-12 19:45 UTC, karst commented
@Basssiiie that now looks like this 
![image](https://user-images.githubusercontent.com/1516893/201491830-592bb076-acfc-4ec5-854c-8c7fc65739d6.png)
Which stil isn't perfectd but it's miles better than what it was.
I will now work on that singular pixel Michael pointed out

2022-11-12 19:56 UTC, karst commented
Anything else that needs patching?
![image](https://user-images.githubusercontent.com/1516893/201492211-07cd4fdd-9dac-4c67-aa89-583e24ca6780.png)
![image](https://user-images.githubusercontent.com/1516893/201492215-f17e4e98-030b-4919-a2e1-93afad650ca9.png)
![image](https://user-images.githubusercontent.com/1516893/201492220-2b78b960-f704-476f-8263-fd4c70a2e9e6.png)
![image](https://user-images.githubusercontent.com/1516893/201492228-81062eeb-9613-4e19-86fb-1e475b8814e6.png)

2022-11-12 21:23 UTC, Basssiiie approved these changes

2022-11-12 22:30 UTC, Gymnasiast commented
There was a second pixel in my screenshot that still has to be addressed. It’s not quite as easy to spot, though:

![afbeelding](https://user-images.githubusercontent.com/1478678/201497063-c08ee645-8f74-4372-ad1d-fc57d8024ae9.png)

2022-11-12 22:31 UTC, karst commented
OH THERE. Damn that blends in with grass and a half

2022-11-12 22:35 UTC, karst commented
My 30 seconds are up

2022-11-16 15:38 UTC, karst commented
@rik-smeets There's two cases where there's slight glitching with vehicles. I cannot seem to patch these myself. 
One is at the bottom (60-25) on the back (nwse). I feel this issue is because the sprite is too thin, not because of bounding boxes. The other is at the front (60 down) at nwse, but it seems like the bounding boxes of this direction are broken in general.

Lastly there's a glitch with supports displaying behind the track rather than on top of it which I cant seem to fix either.

Other than that this PR should be good to go and these fixes might be a better fit for a different general fix.

2022-11-19 17:18 UTC, karst commented
I think I could patch the issue with the back NWSE by making the butt a pixel thicker. 
Other two issues are reported bugs #18613 and #18630, which have nothing to do with this PR sadly.

2022-11-19 20:43 UTC, karst commented
I suppose since there's no official vehicle out for the flume yet it might be smarter to look into that poking out with the official model instead? Something Realsteel could look into perhaps?

2022-11-20 18:09 UTC, Realsteel89 commented
> 

this boat was my very first attempt and i made a big mistake. i assumed that the line has a water volume which it doesn't have and i didn't implement the boat on the line like in the picture but underneath. This is also the reason why it glitches through the track (blue line).

![98ed3c77ef9a89a6442abf8c99b32405](https://user-images.githubusercontent.com/77458610/202918249-4f2d103f-3301-4f48-bdee-b138ea55ccad.png)
![f0fb233ad584963cd1a2b162e0a60956](https://user-images.githubusercontent.com/77458610/202918256-74c7fd00-49f0-479c-808c-6ce68cc892be.png)

now i did an better version with the new renderer from x71 and it looked correct on the track
![image](https://user-images.githubusercontent.com/77458610/202918317-c74087ca-451a-4ab3-ab6c-96f0d04cc2b1.png)

![image](https://user-images.githubusercontent.com/77458610/202918340-91766d1c-a710-4cc8-8c90-ce7294e0b0a7.png)
![rn_image_picker_lib_temp_43d49afe-ed4b-45fa-922c-cea2e44c7b82](https://user-images.githubusercontent.com/77458610/202918355-f4a99e5d-5783-4584-afed-9ea4480a1f38.jpg)
![rn_image_picker_lib_temp_a7e9d2c1-44e8-450c-9620-89d80d51aef2](https://user-images.githubusercontent.com/77458610/202918363-d7d8bbee-e7e0-4169-81c7-4ca00814b092.jpg)

And yes i had the track version only with the small glitch on the track but I think this has already been fixed.

I can't release the new boot because the turntable doesn't work yet and object versioning doesn't exist. I could only release it for testing but then you would have to delete it afterwards.

2022-12-06 09:18 UTC, karst commented
Wouldn't it be smart to up the save version by one so someone in a future pr or this PR could implement previous parks to have the sprites render invisible? I think the steep pieces on log flumes is one of the most used things that doesn't have sprites for it.
If it's below the new version when importing a park the sprites would be made invisible with the tile inspector automatically, while the new version and up wouldn't do that.

2022-12-08 19:00 UTC, Gymnasiast commented on src/openrct2/park/ParkFile.cpp
> +                                // Lots of Log Flumes exist where the downward slopes are simulated by using other track
Note to self: remove this text, it’s been moved to the function in question.

2022-12-08 19:04 UTC, Gymnasiast approved these changes
LGTM, asking @rik-smeets to take it for a test.

2022-12-09 18:54 UTC, rik-smeets commented
From this angle, there seems to be a slight mismatch in the transition between the steep and sloped track pieces:
![image](https://user-images.githubusercontent.com/30838294/206773638-c0367781-cdfa-4dc3-a47c-8b80d3c7601d.png)

This isn't visible from the other angle:
![image](https://user-images.githubusercontent.com/30838294/206773962-b02dfdf2-d03c-44f8-befb-3faa618b17f6.png)

Could you see if you could fix that, @karst? Other than that, LGTM. Very nice addition!

2022-12-09 19:04 UTC, Gymnasiast commented
@karst Do not commit or push anything to the branch until you’ve checked with me, otherwise it’s going to get very messy ;)

2022-12-09 19:46 UTC, karst commented
Ah, i did already try slope it better than originally, but I'll look into it one more time then. Expect tomorrow or the day after

2022-12-10 12:38 UTC, karst commented
![image](https://user-images.githubusercontent.com/1516893/206855514-d48a7f2a-c7de-44e1-81f5-c4df5a09c33a.png)
I tried my hardest improving the transition. I hope this is good enough

2022-12-10 15:14 UTC, rik-smeets commented
Looks good to me @karst, thanks! Will you coordinate with @Gymnasiast to add it to this PR?

2022-12-10 15:14 UTC, rik-smeets approved these changes

2022-12-10 15:32 UTC, Legotown55 commented
When will this be murged it to the game

2022-12-11 14:20 UTC, merged