Fix #18035: Favorited servers don't get their online status updated.
OpenRCT2/OpenRCT2 pull request #18056
Opened 2022-09-19 10:36 UTC by beam41

From fetching flow, list will always have favorited servers but no code to update those entries only append.
This code updates those favorited servers in the list with new data from internet by matching address.
This will fix list having 2 duplicate servers too. (one favorited and one not)

2022-09-21 23:50 UTC, IntelOrca approved these changes

2022-09-22 17:12 UTC, Gymnasiast requested changes
This needs a changelog entry:

`Fix: [#18035] Favourited servers don’t get their online status updated.`

I also have two minor corrections for the comments.

2022-09-22 17:12 UTC, Gymnasiast commented on src/openrct2/network/ServerList.cpp
> +            // keep favorites
```suggestion
            // Keep favourites
```

2022-09-22 17:12 UTC, Gymnasiast commented on src/openrct2-ui/windows/ServerList.cpp
> +                _serverList.WriteFavourites(); // update favourites in case favourited server info changes.
```suggestion
                _serverList.WriteFavourites(); // Update favourites in case favourited server info changes
```

2022-09-23 20:50 UTC, Gymnasiast approved these changes

2022-09-23 20:51 UTC, merged