Add RMC sounds, audio objects and asset packs
OpenRCT2/OpenRCT2 pull request #18312
Opened 2022-10-12 22:18 UTC by IntelOrca

2022-10-15 01:02 UTC, karst commented
The RMC track friction is not using the correct pitch, it should have the same values as the B&M track friction sound.
[auraspecs.rmctest.zip](https://github.com/OpenRCT2/OpenRCT2/files/9790849/auraspecs.rmctest.zip)
Use the following assetpack on current develop version to check the difference. 
At current commit the sound of RMC track friction sounds like mosquito which is sounds quite annoying, while in the assetpack above it sounds more roaring and epic.

I have made a PR on the objects directory to change the sounds to use the correct track friction see right here https://github.com/OpenRCT2/objects/pull/220
Once this is merged the objects repo will need a new release and that should be pushed with this PR.

Lastly the DefaultObjects need to be updated.
In `.h` that is `extern const std::string_view DefaultSelectedObjects[106];` (instead of `103`)
And under `// Music` in `.cpp` you need to add `openrct2.music.acid`, `openrct2.music.dodgems` and `openrct2.music.galaxy`  at line 116.
The three above should also be inserted to `RCT12.cpp` at line 735

That's all I have currently found.

2022-10-25 12:29 UTC, karst commented
The only thing I am currently concerned with still is that the music files will be dropped in the build twice rather than the alternative style being able to pull the music from a music object file. Music files are already pretty big as they are and to have them duplicated is kind of a waste of space.
Artifact to show: [OpenRCT2 OpenMusic Objects.zip](https://github.com/OpenRCT2/OpenRCT2/files/9860202/OpenRCT2.OpenMusic.Objects.4.zip)

2022-11-08 18:09 UTC, Gymnasiast commented on src/openrct2-ui/CMakeLists.txt
> +    # download opensfx and openmsx
This only adds downloads to the macOS bundle.

I tried adding counterparts for Linux to `<root>/CMakeLists.txt`, but I’m running into problems there - it seems that merging three `object` folders does not work as intended.

2022-11-08 18:16 UTC, Gymnasiast requested changes
Tested this out. The asset download does not seem to work, but installing them manually, I get the lovely Hbyrid RC sounds. So we just have to sort out that bit, I imagine.

2022-11-08 19:18 UTC, IntelOrca commented
> Tested this out. The asset download does not seem to work, but installing them manually, I get the lovely Hbyrid RC sounds. So we just have to sort out that bit, I imagine.

try now

2022-11-10 21:45 UTC, Gymnasiast approved these changes

2022-11-10 22:51 UTC, karst commented
Changelog entry would probably look best like this:
```
- Feature: [#18312, objects#220, OpenSFX#13] New sound effects for the Hybrid RC & Single Rail RC.
- Feature: [objects#221] Adopt two of Couger's jungle walls as official objects.
- Feature: [OpenSFX#11, OpenMusic#19] Official replacement assetpacks for sound effects & music. 
- Feature: [OpenMusic#14, OpenMusic#15, OpenMusic#18] New music is now available: Galaxy style, Acid style, Dodgems style.
```

2022-11-12 13:02 UTC, merged