Fix #17067 :  Random Staff Patrol Area clicks
OpenRCT2/OpenRCT2 pull request #18329
Opened 2022-10-13 06:49 UTC by raacker

Clicking the tile with Global Patrol area enabled still fires OnToolDrag but the problem is that PatrolAreaWindow tool is not fully initialized with other attributes especially gMapSelectPositionA, B.

To avoid the uninitialized call behavior, add a None enum which only sets when the tool is ready to act.

2022-10-14 01:37 UTC, raacker commented
@Gymnasiast Hi, just a quick question. It seems like I cannot link the issue myself when I open the PR. Is it because I have to create a branch from the issue page? Just asking because I saw you linking the issues to my PRs.

2022-10-14 11:24 UTC, Gymnasiast commented
I don’t think regular users can do that, only maintainers.

2022-10-14 12:58 UTC, rik-smeets commented
I think you can do it by typing `Resolves #[issue number]`  in the original post. `Fixes` instead of resolves probably works too.

2022-10-14 13:13 UTC, James103 commented
> I think you can do it by typing `Resolves #[issue number]` in the original post. `Fixes` instead of resolves probably works too.

Same with the keyword `Closes`.

2022-10-14 13:30 UTC, tupaschoal commented
It's actually confusing, the keywords guarantee the issue will be closed upon merging, but it won't show up automatically on "linked issues", as far as I remember

2022-10-14 13:52 UTC, rik-smeets commented
> It's actually confusing, the keywords guarantee the issue will be closed upon merging, but it won't show up automatically on "linked issues", as far as I remember

Pretty sure it does, for example see [this old PR of mine](https://github.com/OpenRCT2/OpenRCT2/pull/16730) (I wasn't a team member back then). As you can see the issue was linked, and the only time it was mentioned was in my PR description.

2022-10-14 15:00 UTC, IntelOrca commented
This PR needs both a network and plugin version increment. But I am not sure this is the right way to fix the issue yet, I will need to look at what the issue more.

2022-10-14 15:09 UTC, raacker commented
@rik-smeets Oh yeah I think your PR proves that. I will try adding Resolves or Closes next time. Thanks!

2022-10-14 15:13 UTC, raacker commented
> This PR needs both a network and plugin version increment. But I am not sure this is the right way to fix the issue yet, I will need to look at what the issue more.

Thanks for reviewing. A quick note. When I tested this behavior on the vanilla version it definitely should not fire OnMouseDrag or OnMouseDown on the PatrolArea action, but just find a closest staff and open the PatrolArea action window. I noticed that OpenRCT2's default _mode is "Set" and it enables uninitialized Area Process as a result.

2022-10-29 13:20 UTC, tupaschoal commented
> This PR needs both a network and plugin version increment. But I am not sure this is the right way to fix the issue yet, I will need to look at what the issue more.

Hi @IntelOrca , did you have time to loook into it again?

2022-10-30 22:02 UTC, IntelOrca commented
@tupaschoal sorry, I have not had time yet

2022-11-04 15:39 UTC, IntelOrca commented
I have invested the issue, and it is related to how the mouse input is handled. This change works around the issue by changing the game actions, it would be better to fix the issue in the UI layer.

I think this is the right fix:
```diff
diff --git a/src/openrct2-ui/input/MouseInput.cpp b/src/openrct2-ui/input/MouseInput.cpp
index ca24cab8f..7e0b56eb6 100644
--- a/src/openrct2-ui/input/MouseInput.cpp
+++ b/src/openrct2-ui/input/MouseInput.cpp
@@ -375,6 +375,9 @@ static void GameHandleInputMouse(const ScreenCoordsXY& screenCoords, MouseState
                         break;
                     }
 
+                    if (!input_test_flag(INPUT_FLAG_4))
+                        break;
+
                     if (w->classification != _dragWidget.window_classification || w->number != _dragWidget.window_number
                         || !(_inputFlags & INPUT_FLAG_TOOL_ACTIVE))
                     {
@@ -1040,8 +1043,8 @@ static void InputWidgetLeft(const ScreenCoordsXY& screenCoords, rct_window* w, W
                 w = window_find_by_number(gCurrentToolWidget.window_classification, gCurrentToolWidget.window_number);
                 if (w != nullptr)
                 {
+                    input_set_flag(INPUT_FLAG_4, true);
                     window_event_tool_down_call(w, gCurrentToolWidget.widget_index, screenCoords);
-                    _inputFlags |= INPUT_FLAG_4;
                 }
             }
             break;
diff --git a/src/openrct2/interface/Window.cpp b/src/openrct2/interface/Window.cpp
index 01bf1f4e0..dc62bac00 100644
--- a/src/openrct2/interface/Window.cpp
+++ b/src/openrct2/interface/Window.cpp
@@ -1361,6 +1361,7 @@ bool tool_set(const rct_window& w, WidgetIndex widgetIndex, Tool tool)
     }
 
     input_set_flag(INPUT_FLAG_TOOL_ACTIVE, true);
+    input_set_flag(INPUT_FLAG_4, false);
     input_set_flag(INPUT_FLAG_6, false);
     gCurrentToolId = tool;
     gCurrentToolWidget.window_classification = w.classification;
```

2022-11-04 15:40 UTC, IntelOrca requested changes
I have invested the issue, and it is related to how the mouse input is handled. This change works around the issue by changing the game actions, it would be better to fix the issue in the UI layer.

The problem is that the find staff tool opens up the patrol area window which then changes the tool before the left mouse button is released. Thus, the next mouse move input redirects now to the new patrol area tool causing the patrol area to actually update. I think to fix this, the input state needs to be reset when the tool changes so that it requires a new mouse down event to trigger the next drag update for the tool.

This change fixes the issue:
```diff
diff --git a/src/openrct2-ui/input/MouseInput.cpp b/src/openrct2-ui/input/MouseInput.cpp
index ca24cab8f..7e0b56eb6 100644
--- a/src/openrct2-ui/input/MouseInput.cpp
+++ b/src/openrct2-ui/input/MouseInput.cpp
@@ -375,6 +375,9 @@ static void GameHandleInputMouse(const ScreenCoordsXY& screenCoords, MouseState
                         break;
                     }
 
+                    if (!input_test_flag(INPUT_FLAG_4))
+                        break;
+
                     if (w->classification != _dragWidget.window_classification || w->number != _dragWidget.window_number
                         || !(_inputFlags & INPUT_FLAG_TOOL_ACTIVE))
                     {
@@ -1040,8 +1043,8 @@ static void InputWidgetLeft(const ScreenCoordsXY& screenCoords, rct_window* w, W
                 w = window_find_by_number(gCurrentToolWidget.window_classification, gCurrentToolWidget.window_number);
                 if (w != nullptr)
                 {
+                    input_set_flag(INPUT_FLAG_4, true);
                     window_event_tool_down_call(w, gCurrentToolWidget.widget_index, screenCoords);
-                    _inputFlags |= INPUT_FLAG_4;
                 }
             }
             break;
diff --git a/src/openrct2/interface/Window.cpp b/src/openrct2/interface/Window.cpp
index 01bf1f4e0..dc62bac00 100644
--- a/src/openrct2/interface/Window.cpp
+++ b/src/openrct2/interface/Window.cpp
@@ -1361,6 +1361,7 @@ bool tool_set(const rct_window& w, WidgetIndex widgetIndex, Tool tool)
     }
 
     input_set_flag(INPUT_FLAG_TOOL_ACTIVE, true);
+    input_set_flag(INPUT_FLAG_4, false);
     input_set_flag(INPUT_FLAG_6, false);
     gCurrentToolId = tool;
     gCurrentToolWidget.window_classification = w.classification;
```

2022-11-09 10:54 UTC, tupaschoal commented
@raacker can you please adapt the PR following Ted's suggestion?

2022-11-09 17:46 UTC, raacker commented
Oh sorry about that. I will apply the suggested changes tonight. Thanks for reminder

2022-11-09 19:03 UTC, tupaschoal commented
No worries, just a kind reminder :)

2022-11-11 02:18 UTC, IntelOrca approved these changes

2022-11-12 18:46 UTC, tupaschoal commented
Please add a changelog entry

2022-11-13 17:58 UTC, raacker commented
@tupaschoal Just updated the final commit. Thanks for the work

2022-11-15 23:46 UTC, tupaschoal commented on distribution/changelog.txt
> +- Fix: [#17067] Random Staff Patrol Area clicks
```suggestion
- Fix: [#17067] Random Staff Patrol Area clicks.
```

2022-11-15 23:54 UTC, tupaschoal commented
@rik-smeets since the actual fix turned out to be on the UI layer, I think there is no need for plugin and network version bumps, so I removed both labels.

2022-11-16 00:13 UTC, merged