fix bug 18132
OpenRCT2/OpenRCT2 pull request #18350
Opened 2022-10-16 04:12 UTC by 733737

changes left to top and top to left in ride.cpp

before
<img width="1926" alt="before" src="https://user-images.githubusercontent.com/94884086/196017607-2c372942-22a2-4400-b1f6-0ded4c9871b7.png">
after
<img width="1917" alt="after" src="https://user-images.githubusercontent.com/94884086/196017612-6037ddbb-4b5b-449f-be71-04e1333510fe.png">

2022-10-16 04:53 UTC, 733737 commented
not a perfect solution, but still an improvement:
3x scaling before
<img width="1922" alt="before2" src="https://user-images.githubusercontent.com/94884086/196018737-481d545b-32b8-46f4-9701-d7dcd13f49cc.png">
after
<img width="1926" alt="after2" src="https://user-images.githubusercontent.com/94884086/196018742-6a9f69ab-1528-4a9d-894d-ee6532ad3794.png">

2022-10-16 05:55 UTC, 733737 commented
I fixed the offset, while keeping the bugfix 
<img width="1922" alt="2022-10-16 (27)" src="https://user-images.githubusercontent.com/94884086/196020524-b0797083-9f11-4eac-b108-40fa499be43d.png">

2022-10-17 15:32 UTC, IntelOrca commented
Your change doesn't make much sense. Why would you subtract the dropdown top (Y component) from the widget right (X component)? I that would give you unusual behaviour.

2022-10-17 21:18 UTC, 733737 commented
I think it just so happens to be the right integer, so maybe if we calculate the value of the integer at runtime, we can just hardcode the number we want instead

2022-10-25 18:20 UTC, rik-smeets requested changes
This implementation may happen to solve the issue, but that's just coincidental as you said. Could you try to make a more robust solution? Hardcoding a value is not an issue if this resolves the issue, it happens a lot on other screens too. Things like `dropdownWidget->width() - 3` are quite common, perhaps something like that could work here too?

Please also add a changelog entry.

2022-10-26 10:42 UTC, rik-smeets commented
This change breaks off some of the train type's descriptions, it doesn't look good:
![image](https://user-images.githubusercontent.com/30838294/198005398-8c05f2f6-20e7-4e73-a95f-08188110676d.png)

This wasn't the case before. I know the padding seems large on many of the ride types, but I don't think we should cut them off. Maybe you can tweak the amount of padding to make it a bit more efficient than before, whilst ensuring all text remains readable?

2022-10-26 16:25 UTC, 733737 commented
Actually the wooden coaster trains always have been cut off for months

2022-10-26 16:29 UTC, rik-smeets commented
> Actually the wooden coaster trains always have been cut off for months

They aren't. If they're cut off for you, that's because of the screen size (resolution) and scaling on your end. With this change, they'll get cut off for everyone.

2022-10-26 16:50 UTC, 733737 commented
Yeah I checked, and they aren't cut off for me. So I can reduce the amount I drop padding by, but it may not fix the original bug

2022-10-26 16:58 UTC, 733737 commented
this is now reduced, and there's no cut off 
<img width="1646" alt="after4" src="https://user-images.githubusercontent.com/94884086/198088667-d237f932-4121-45ea-98de-1523529911e6.png">

2022-10-26 18:03 UTC, rik-smeets commented
There still should be some padding left so it looks nice. Also, I realized the padding should only be decreased if there are multiple columns in the dropdown - if not, the width should equal the dropdown button itself.

I took the liberty to implement this, meaning I'll ask another team member to review my addition regarding the dynamic dropdown width.

2022-10-26 20:59 UTC, 733737 commented
I agree this window needs reworking, but I don't know if your proposal will fix the cutoff issue

2022-11-02 08:08 UTC, 733737 commented
I have no issue with rik's version being merged as is with dev approval

2022-11-03 18:56 UTC, Gymnasiast commented
> There still should be some padding left so it looks nice. Also, I realized the padding should only be decreased if there are multiple columns in the dropdown - if not, the width should equal the dropdown button itself.
> 
> I took the liberty to implement this, meaning I'll ask another team member to review my addition regarding the dynamic dropdown width.

Could you upload a screenshot?

2022-11-05 07:06 UTC, rik-smeets commented
Sure, if there's only a single column the width will remain the same as before:
![Single column](https://user-images.githubusercontent.com/30838294/200107299-d5a7b8c6-ac87-4535-818c-e30232e5cd6c.png)

If there are multiple columns, the width will be reduced to allow more columns to fit on screen:
![Multiple columns](https://user-images.githubusercontent.com/30838294/200107330-7c7bf377-65bd-444f-924a-6676940c1af7.png)

2022-11-05 11:47 UTC, Gymnasiast commented
Have you tested if this affects other dropdown, especially the ones used for land types or colour pickers?

2022-11-05 11:52 UTC, rik-smeets commented
The changed code in `Ride.cpp` is specific to the vehicle dropdown only. It doesn't effect any other dropdowns.

2022-11-05 11:53 UTC, Gymnasiast approved these changes

2022-11-05 12:43 UTC, rik-smeets approved these changes

2022-11-05 12:43 UTC, merged

2022-11-05 14:39 UTC, IntelOrca commented
This fix is still assuming English localisation, another locale might have issues. A more general fix will require making the dropdown list automatically measure the length of each item and take the longest one as the column width. Further changes could be made to allow each column in the dropdown to have a different width based on what is in that column.

2022-11-05 16:44 UTC, Gymnasiast commented
@IntelOrca Could you create an issue for that?