Fix #1972/11679: Facilities clipping issues
OpenRCT2/OpenRCT2 pull request #18358
Opened 2022-10-16 14:39 UTC by rik-smeets

Adjust the bounding boxes to prevent clipping issues as shown in the issues that will be closed by this PR. I tested both scenarios and all issues are resolved. I also didn't notice any regression when testing in busy parks with facilities.

The changes to the bounding boxes seem large, but they are now actually similar to the stores' which didn't have these issues to begin with. 

Resolves #1972 and resolves #11679.

2022-10-19 10:13 UTC, Gymnasiast requested changes
This breaks drawing peeps that are inside facilities:

![afbeelding](https://user-images.githubusercontent.com/1478678/196663499-0cc042d5-5ceb-4afe-b305-e3121d23e3e1.png)

2022-10-19 10:22 UTC, rik-smeets commented
> This breaks drawing peeps that are inside facilities:
> 
> ![afbeelding](https://user-images.githubusercontent.com/1478678/196663499-0cc042d5-5ceb-4afe-b305-e3121d23e3e1.png)

Good find, I completely forget to test with peeps inside. I'll try to get those guys some privacy back ;-).

2022-11-03 18:51 UTC, Gymnasiast requested changes
This version fixes the peeps, but now the glitch in #1972 is back again:

![afbeelding](https://user-images.githubusercontent.com/1478678/199809169-35dd6563-9bcd-47f5-bc49-1ab07aac7246.png)

2022-11-03 18:59 UTC, rik-smeets commented
> This version fixes the peeps, but now the glitch in #1972 is back again:
> 
> ![afbeelding](https://user-images.githubusercontent.com/1478678/199809169-35dd6563-9bcd-47f5-bc49-1ab07aac7246.png)

Argh! How about changing this PR so it only resolves the other linked issue? #1972 is a lot harder and I could give that a separate go later.

2022-11-05 06:56 UTC, rik-smeets commented
I just changed the scope of this PR to solely resolve #11679. Can this get your approval now, @Gymnasiast ?

2022-11-05 11:08 UTC, Gymnasiast approved these changes

2022-11-05 11:08 UTC, merged

2022-11-05 12:53 UTC, cheweytoo commented
Awesome, that's much improved, thank you! There's just one flicker case left, for scenery _in front of_ a stall:
From test park in #11679, in 4c218ba (a handful of commits ahead of this) on develop:


https://user-images.githubusercontent.com/29800630/200120764-949d225d-7402-4c6a-8c87-c92441bdbe62.mp4

2022-11-05 13:42 UTC, rik-smeets commented
@cheweytoo Yes, I'm quite sure that's the same issue as #1972. It's a tricky one, which I didn't manage to fix yet, unfortunately.

2022-11-05 13:45 UTC, cheweytoo commented
Ah, I see. Well, fingers crossed then. :-)

2022-11-05 19:18 UTC, cheweytoo commented
The privacy screen is directional I'm afraid:

![unprivate_toilet](https://user-images.githubusercontent.com/29800630/200137143-f08e8f62-8be1-432b-a418-ae3fa60a58a3.png)

Doesn't seem to happen with every guest, and seems to happen more often with accessorised guests (hat, balloon), and only from the two "back view" directions, i.e. the directions that see the back of the stall.

[unprivate_toilets.zip](https://github.com/OpenRCT2/OpenRCT2/files/9944561/unprivate_toilets.zip)