Fix no overwrite alert on Windows if there are capitalization differences
OpenRCT2/OpenRCT2 pull request #18375
Opened 2022-10-18 19:06 UTC by jazzysoggy

Fixes #18354

Issue: When saving on Windows, files names with only character capitalization differences, like ``aaa.park`` and ``AAA.park``, would not trigger the overwrite alert, even though Windows will overwrite the original file.

Fix: Entered in the parameter for ``String::Equals`` so that it would ignore capitalization differences if the platform is Windows. Used drive check as well as running in Wine check to make sure the platform in question is in Windows.

2022-10-18 19:55 UTC, CookiePLMonster commented
Is the Wine check required? I'd hope that Wine emulates case insensitive filesystem, else breakage would be common.

2022-10-18 20:40 UTC, IntelOrca commented
> Is the Wine check required? I'd hope that Wine emulates case insensitive filesystem, else breakage would be common.

It really depends on how Wine handles `CreateFileA` / `CreateFileW` when two files with the same name, difference case exists.

2022-10-18 21:51 UTC, jazzysoggy commented
Removed Wine Check, since Wine has case insensitivity

2022-10-19 11:10 UTC, CookiePLMonster commented on src/openrct2-ui/windows/LoadSave.cpp
> +            int32_t lowerCase = Platform::GetDrives();
Personally I think the check should just be done by trying to open an existing file or creating new, and reacting to a possible failure. This transfers the burden of checking the case sensitivity on the OS.

2022-10-19 11:20 UTC, Gymnasiast commented on src/openrct2-ui/windows/LoadSave.cpp
> +            int32_t lowerCase = Platform::GetDrives();
That is true, but always going for case insensitivity (regardless of what the OS or filesystem does) is more user-friendly in my opinion.

2022-10-19 11:28 UTC, CookiePLMonster commented on src/openrct2-ui/windows/LoadSave.cpp
> +            int32_t lowerCase = Platform::GetDrives();
I'm not sure I agree - while I do see your reasoning, I am inclined to believe going for consistency with the user's OS will always be the most user friendly.

2022-10-19 23:00 UTC, jazzysoggy commented on src/openrct2-ui/windows/LoadSave.cpp
> +            int32_t lowerCase = Platform::GetDrives();
Implemented std::filesystem:exists check to replace the old file existence check method. This ensures consistency with underlying OS filesystem.

2022-10-20 08:26 UTC, CookiePLMonster requested changes
`std::filesystem::path` approach was better than this, especially since your solution will break with UTF-8 paths.

Use `File::Exists(path)`.

2022-10-20 12:14 UTC, jazzysoggy commented
> `std::filesystem::path` approach was better than this, especially since your solution will break with UTF-8 paths.
> 
> 
> 
> Use `File::Exists(path)`.

filesystem::exists didn't seem to work with macOS and Ubuntu 18.04, the former complaining about a macOS 10.15 requirement, while the later stated such method doesn't exist.

2022-10-20 12:16 UTC, CookiePLMonster commented
Then use `File::Exists(path)`. I suspect those environments use `ghc` for filesystem, and `File` will abstract it away from you.

2022-10-20 21:41 UTC, CookiePLMonster approved these changes

2022-10-25 18:05 UTC, rik-smeets requested changes
Could you add an entry to the changelog please? Thanks!

2022-10-26 06:18 UTC, rik-smeets approved these changes

2022-10-26 06:19 UTC, merged