Fix #18364: No Too High! or Too Low! error messages when attempting to raise/lower land beyond the limits
OpenRCT2/OpenRCT2 pull request #18385
Opened 2022-10-19 17:11 UTC by HouseholdVTuber

Added missing ErrorMessage line in respective height range-related Error results for LandRaiseAction and LandLowerAction

This is my first contribution so I also appended my user to the Bug Fixes list. Thank you!

2022-10-19 20:06 UTC, Gymnasiast submitted a review, later dismissed
This overwrites several other errors, e.g. “Forbidden by local authority”.

I did some digging and I saw where the problem lies. Do you want me to tell you, or would you prefer to find it out yourself?

2022-10-19 20:15 UTC, HouseholdVTuber commented
If you've already found it then I'd appreciate your answer, thanks! I'd seen the existing check for whether it was outside of the property and figured all else was accounted for.

2022-10-19 21:52 UTC, HouseholdVTuber commented
In the meantime I amended my change to only return that ErrorMessage if the new height was at or above/below the valid range, but it looks like the ride height code handles these GameActions::Status errors differently. I'll spend some more time with it until I hear otherwise. Thanks again.

2022-10-19 21:57 UTC, Broxzier commented
This is not the place to add that check. Have a look at where the result object comes from. `GameActions::ExecuteNested` and `GameActions::QueryNested`.

2022-10-20 02:46 UTC, HouseholdVTuber commented
Okay I'm starting to see it, so the result's ErrorTitle is already being returned as, "Too Low!" from the logic in LandSetHeightAction which already checked against the min/max height. But when we're lowering or raising land we want that to be in the result's ErrorMessage value, after the ErrorTitle which would expectedly say, "Can't Lower/Raise Land Here..."? So the information's just being overwritten.

2022-10-20 16:44 UTC, HouseholdVTuber commented
Alright I'm much happier with this, the other attempts feel comparatively shortsighted. Thank you for your advice Gymnasiast and Broxzier. 

I'm trying to adhere to the code formatting style but it looks like I'm missing something, I'm going to run clang-format locally and figure it out before attempting more commits.

2022-10-21 20:56 UTC, HouseholdVTuber commented
I can also expand on this to account for the other errors like Gymnasiast mentioned if this implementation is acceptable, either now or in a separate issue depending on how you guys like to track things.

2022-10-21 22:50 UTC, Broxzier requested changes

2022-10-21 22:50 UTC, Broxzier commented on src/openrct2/actions/LandSetHeightAction.cpp
> +        }
Have a look at what `errorTitle` holds, and how `LandSetHeightAction::CheckParameters` works.

Not directly related to this PR: both of these identifiers could be renamed to something that makes more sense - `ValidateParameters` for instance. 'Check' is a useless term in programming.

2022-10-21 22:50 UTC, Broxzier commented on src/openrct2/actions/LandLowerAction.cpp
> +
The error message should not be set here.

2022-10-21 22:50 UTC, Broxzier commented on src/openrct2/actions/LandRaiseAction.cpp
> +
Same here

2022-10-22 13:56 UTC, HouseholdVTuber commented
Hah, so I was apprehensive about changing what LandSetHeightAction::CheckParameters returns - but the only actions referencing it seem to be LandLowerAction, LandRaiseAction, and LandSmoothAction. Does this make sense? And... should I make it so that LandSetHeightAction also sets the return error title, and get rid of the lines in LandLowerAction/LandSetHeightAction that set the title? I'm still worried about changing too much.

Thanks again and I appreciate your patience, I made more complicated than it had to be.

2022-11-03 18:21 UTC, Gymnasiast commented on src/openrct2/actions/LandSetHeightAction.cpp
> +        StringId errorTitle = CheckRideSupports();
This also needs to be the error message, rather than the title.

2022-11-03 21:25 UTC, HouseholdVTuber commented
Latest commit returns a Result with the appropriate errorMessage instead of errorTitle in LandSetHeightAction.cpp, per Gymnasiast's review

2022-11-08 21:23 UTC, Broxzier approved these changes
Tested and works as expected.

I'd like to note that the way the parameters are validated and returned as error messages is not very consistent, but cleaning that up is something for another PR.

2022-11-12 14:25 UTC, HouseholdVTuber commented
Thanks Broxzier, I can submit that as an issue and work on it later if that makes sense.

And would it be better for me to re-commit the contributors.md with its latest or just let someone with write access resolve the merge conflict?

2022-11-15 23:45 UTC, tupaschoal commented
> And would it be better for me to re-commit the contributors.md with its latest or just let someone with write access resolve the merge conflict?

If you can solve the merge conflict, that's better. If you don't know how to do it, let us know and we can help

2022-11-19 20:42 UTC, HouseholdVTuber commented
Thanks tupaschoal, I figured I just had to copy the latest and re-append my line for it to go through since it's just a text file

2022-11-19 22:55 UTC, Broxzier commented
Great! That's usually the best approach with simple merge conflicts.

2022-11-20 12:12 UTC, tupaschoal commented
Unfortunately there is still a merge conflict on "contributors.md", can you try again?

This tutorial might help you: https://github.com/OpenRCT2/OpenRCT2/wiki/Rebase-and-Sync-fork-with-OpenRCT2

2022-11-22 21:08 UTC, HouseholdVTuber commented
Thanks for the link, I've got it now!!

2022-11-23 11:12 UTC, tupaschoal approved these changes

2022-12-01 11:10 UTC, tupaschoal commented
@Gymnasiast can you review this one so we can merge it, please?

2022-12-07 02:06 UTC, merged