Fix #18665, #18559: Add API for getting g2 icons by name
OpenRCT2/OpenRCT2 pull request #18675
Opened 2022-11-25 01:07 UTC by spacek531

This PR attempts to solve the issues created by #18497 by automatically substituting new sprite IDs from legacy sprite IDs and creates an API to get the proper sprite ID for plugins going forward.

While both individually work, together they work at odd purposes. Consider the following plugin:

```js
var Widgets = [
    {
        type : "button",
        width : 100,
        height :100,
        image: context.getIcon("placeholder")
    }
]

ui.openWindow({
        classification: "window",
        title: "window",
        x: 100,
        y: 100,
        width: 100,
        height: 100,
        widgets: Widgets,
});

var main = function() {};

registerPlugin({
    name: 'image api test',
    version: '1.0',
    authors: ['Spacek'],
    type: 'local',
    license:'CC-SA 3.0',
    main: main
});
```

The button widget correctly gets the placeholder image index 29358. However, when `CustomWidgetDesc::FromDukValue` is run, it calls `FilterLegacyIconSprites` which interprets 29358 as the legacy OpenRCT2 logotype and replaces it with 29362, the new logotype index.

2022-11-25 03:29 UTC, spacek531 commented on src/openrct2/scripting/G2Names.hpp
> +        { 32248, 29357 }, { 29363, 29358 }, { 29357, 29359 }, { 29358, 29360 }, { 29359, 29361 }, { 29360, 29362 },
I am refactoring this table to use constants like the other one

2022-11-25 03:56 UTC, spacek531 commented
Does anyone know what's going on with the linux build?

2022-11-25 09:17 UTC, karst commented on src/openrct2/sprites.h
> +
I think it's smarter to place this comment down at the icons at line 885

2022-11-26 11:05 UTC, ltsSmitty commented
Since the type in the d.ts isn't an Enum, can you alphabetize the list of icon names for legibility?

2022-11-26 11:19 UTC, Basssiiie approved these changes
Looks good to me. Thank you so much for putting your time into this, much appreciated! 🤩

How it looks ingame:
![image](https://user-images.githubusercontent.com/20048660/204086066-c5ec5166-3176-4b1e-8b9f-55ae42a49558.png)

2022-11-26 11:19 UTC, Basssiiie commented on src/openrct2/sprites.h
> +    // When UI elements to G2, insert them before fonts and give them a name in src/openrct2/scripting/G2Names.hpp
When _adding_ UI elements*

I'm guessing? :)

2022-11-26 16:35 UTC, spacek531 commented
I've added a reverse map when getting the image number since it's theoretically possible a plugin would want that.

2022-11-26 17:14 UTC, Basssiiie commented on distribution/openrct2.d.ts
> +    enum IconName = "empty" | "placeholder" | "logo" | "logo_text" | "fast_forward" | "game_speed_indicator" |
This isn't valid a valid Typescript enum, the `type` was correct. @ltsSmitty just asked for the strings to be alphabetical order. :)

2022-11-27 11:44 UTC, Gymnasiast commented on src/openrct2-ui/scripting/ScWidget.hpp
> +                    widget->image = GetIconByName(value.as_string());
Since the `if` has brackets, please put them around the else block too.

2022-11-27 11:47 UTC, Gymnasiast commented
From a quick glance, the implementation looks sound. Would want to test it, and have @IntelOrca do his own review.

2022-11-30 22:13 UTC, Gymnasiast commented on src/openrct2-ui/scripting/ScWidget.hpp
> +                    if (GetTargetAPIVersion() <= API_VERSION_63_G2_REORDER)
Shouldn’t this be

```suggestion
                    if (GetTargetAPIVersion() < API_VERSION_63_G2_REORDER)
```
?

2022-12-06 18:15 UTC, IntelOrca commented
Is there a reason to allow the enum for anything other than `getIcon`, and just call `getIcon` when populating the window desc.

2022-12-06 18:22 UTC, spacek531 commented
It seemed easier to be able to write a string directly to the widget description than require getIcon. @Basssiiie @ltsSmitty you are the primary users, what do you think?

2022-12-06 18:33 UTC, Basssiiie commented
I'd say the enum is more convenient. Why add additional steps if it can be done in one step? It keeps it easy. :)

2022-12-06 18:46 UTC, spacek531 commented
Should a changelog entry be added that the old plugins were fixed? The change occurred in 0.4.3 development.

2022-12-06 19:37 UTC, karst commented
I think the best location for it would be under Improved

2022-12-07 01:12 UTC, IntelOrca commented
> I'd say the enum as it is currently implemented is more convenient. Why add additional steps if it can be done in one step? It keeps it easy. :)

To reduce maintainance of the code base. Every API that takes an image otherwise needs this special logic.

2022-12-07 07:46 UTC, Basssiiie commented
> To reduce maintainance of the code base. Every API that takes an image otherwise needs this special logic.

Fair point, though you could also reduce the CPP side to a one-liner to get the same amount of maintenance reduction, without the extra bloat on the JS side, e.g.
```cpp
widget->image = GetImageFromDukValue(value);
```
And do the `value.type() == STRING` and `value.type() == INTEGER` in there.

2022-12-07 07:47 UTC, Basssiiie commented
Also note that the current implementation is backwards compatible and forcing usage of `getIcon` is not.

2022-12-07 07:50 UTC, spacek531 commented
> Also note that the current implementation is backwards compatible and forcing usage of `getIcon` is not.

Does that factor in at all? The system uses the old numbers for targetAPI 63 and older.

2022-12-07 08:34 UTC, spacek531 commented
I did my best to implement Basssiiie's suggestion. It's late so it needs a second opinion.

2022-12-07 10:11 UTC, IntelOrca approved these changes

2022-12-07 17:42 UTC, spacek531 commented
I think testing tabs with no sprite defined needs testing. I am unsure if it will make a blank tab properly.

2022-12-07 17:58 UTC, spacek531 commented
I tested it and it does make blank tabs properly when a tab image is undefined. If you give it a garbage value like `true` it shows the small grass sprite (sprite 0) (this also applies to button widgets - if the image field is `true` it will supersede the text field). I changed the default value from 0 to SPR_G2_EMPTY which should display nicer.

2022-12-07 18:16 UTC, spacek531 commented
I changed my mind about the default value. Making the sprite invisible when it encounters an unknown value allows people to intentionally use garbage data, and makes it more difficult to debug when it occurs.

2022-12-07 22:26 UTC, Gymnasiast commented on distribution/changelog.txt
> +- Fix: [#18675] [Plugin] Plugins get incorrect g2 image icons.
```suggestion
```

The issue was introduced after the last release, so shouldn’t be in the changelog.

2022-12-08 18:56 UTC, Gymnasiast commented on src/openrct2-ui/scripting/CustomWindow.cpp
> +            else if (dukImage.type() == DukValue::Type::STRING || dukImage.type() == DukValue::Type::NUMBER)
You swapped the if and else around, which doesn’t change how it works but causes an unnecessarily large diff. Please change the order back.

2022-12-08 18:57 UTC, Gymnasiast commented on src/openrct2/scripting/G2Names.hpp
> +        { "legacy_path", SPR_G2_LEGACY_PATH_TAB },
```suggestion
        { "legacy_paths", SPR_G2_LEGACY_PATH_TAB },
```

2022-12-08 18:57 UTC, Gymnasiast commented on src/openrct2/scripting/G2Names.hpp
> +        { "hide_vegitation", SPR_G2_BUTTON_HIDE_VEGETATION },
```suggestion
        { "hide_vegetation", SPR_G2_BUTTON_HIDE_VEGETATION },
```

2022-12-08 18:58 UTC, Gymnasiast commented on src/openrct2/scripting/G2Names.hpp
> +        { "hide_vegitation", SPR_G2_BUTTON_HIDE_VEGETATION },
Don’t forget to also update these two names in the .d.ts file.

2022-12-08 20:22 UTC, Gymnasiast approved these changes
Re-requested a review from @Basssiiie to be sure, but looks good to me now.

2022-12-09 23:14 UTC, Basssiiie reviewed
Accessing sprites by G2 name:
![Six Flags 2022-12-10 00-09-08](https://user-images.githubusercontent.com/20048660/206810079-515d149b-af68-4493-bbfe-d19c5fb8c00a.png)

Accessing by legacy id for old plugins:
![Six Flags 2022-12-10 00-09-10](https://user-images.githubusercontent.com/20048660/206810105-9e73766f-df27-4327-a34d-d172ad0b0db7.png)

Accessing via getIcon() on newer plugins:
![Six Flags 2022-12-10 00-09-22](https://user-images.githubusercontent.com/20048660/206810148-ff24d96c-be7b-46f5-ae19-82e21dc281d5.png)
<details>
  <summary>Code for test plugin:</summary>

```js
const icons = [
	[ "empty",  32248 ],
	[ "placeholder",  29363 ],
	[ "logo",  29357 ],
	[ "logo_text",  29358 ],
	[ "fast_forward",  29359 ],
	[ "game_speed_indicator",  29360 ],
	[ "game_speed_indicator_double",  29361 ],
	[ "map_gen_land",  29362 ],
	[ "zoom_in",  29364 ],
	[ "zoom_in_background",  29365 ],
	[ "zoom_out",  29366 ],
	[ "zoom_out_background",  29367 ],
	[ "map_gen_trees",  29368 ],
	[ "map_gen_noise",  29369 ],
	[ "large_scenery",  29370 ],
	[ "small_scenery",  29371 ],
	[ "paths",  29372 ],
	[ "rct1_close_off",  29373 ],
	[ "rct1_close_off_pressed",  29374 ],
	[ "rct1_close_on",  29375 ],
	[ "rct1_close_on_pressed",  29376 ],
	[ "rct1_test_off",  29377 ],
	[ "rct1_test_off_pressed",  29378 ],
	[ "rct1_test_on",  29379 ],
	[ "rct1_test_on_pressed",  29380 ],
	[ "rct1_open_off",  29381 ],
	[ "rct1_open_off_pressed",  29382 ],
	[ "rct1_open_on",  29383 ],
	[ "rct1_open_on_pressed",  29384 ],
	[ "title_restart",  29385 ],
	[ "title_stop",  29386 ],
	[ "title_play",  29387 ],
	[ "title_skip",  29388 ],
	[ "cheats",  29389 ],
	[ "news_messages",  29414 ],
	[ "server_password",  29415 ],
	[ "multiplayer",  29416 ],
	[ "sort",  29433 ],
	[ "copy",  29434 ],
	[ "paste",  29435 ],
	[ "mute",  29442 ],
	[ "mute_pressed",  29443 ],
	[ "unmute",  29444 ],
	[ "unmute_pressed",  29445 ],
	[ "search",  29461 ],
	[ "eyedropper",  29467 ],
	[ "chat",  29468 ],
	[ "map_north",  29469 ],
	[ "map_north_pressed",  29470 ],
	[ "map_west",  29471 ],
	[ "map_west_pressed",  29472 ],
	[ "map_south",  29473 ],
	[ "map_south_pressed",  29474 ],
	[ "map_east",  29475 ],
	[ "map_east_pressed",  29476 ],
	[ "multiplayer_toolbar",  29477 ],
	[ "multiplayer_toolbar_pressed",  29478 ],
	[ "multiplayer_sync",  29479 ],
	[ "multiplayer_desync",  29480 ],
	[ "simulate",  29481 ],
	[ "rct1_simulate_off",  29482 ],
	[ "rct1_simulate_off_pressed",  29483 ],
	[ "rct1_simulate_on",  29484 ],
	[ "rct1_simulate_on_pressed",  29485 ],
	[ "normal_selection_6x6",  29486 ],
	[ "mountain_tool_even",  29487 ],
	[ "mountain_tool_odd",  29488 ],
	[ "scenery_scatter_low",  29489 ],
	[ "scenery_scatter_medium",  29490 ],
	[ "scenery_scatter_high",  29491 ],
	[ "view",  29494 ],
	[ "path_railings",  29495 ],
	[ "legacy_paths",  29496 ],
	[ "path_surface",  29497 ],
	[ "ride_station",  29498 ],
	[ "terrain_edge",  29499 ],
	[ "hide_vegetation",  29500 ],
	[ "hide_scenery",  29501 ],
	[ "hide_vehicles",  29502 ],
	[ "hide_supports",  29503 ],
	[ "hide_partial",  29504 ],
	[ "hide_full",  29505 ],
	[ "link_chain",  29506 ],
	[ "sideways_tab",  29507 ],
	[ "sideways_tab_active",  29508 ],
	[ "arrow_up",  29509 ],
	[ "arrow_down",  29510 ],
	[ "reload",  29511 ],
].sort(function(a, b) { return a[0].localeCompare(b[0]) });

registerPlugin({
	name: 'Test G2',
	version: '1',
	authors: ['Basssiiie'],
	type: 'remote',
	licence: 'MIT',
	//targetApiVersion: 65,
	main() {
		ui.registerMenuItem("Test G2 icons", function()
		{
			ui.openWindow({
				classification: "g2-test", title: "G2 test",
				x: 20, y: 50, width: 1800, height: 900,
				tabs: [
					{
						image: "zoom_in",
						widgets: create("new g2 name", icons, function(icon) { return icon[0] })
					},
					{
						image: 29499, // terrain edge shovel
						widgets: create("legacy id", icons, function(icon) { return icon[1] })
					},
					{
						image: context.getIcon("chat"),
						widgets: create("getIcon()", icons, function(icon) { return context.getIcon(icon[0]) })
					}
				]
			});
		});
	},
});


function create(name, icons, getId)
{
	var widgets = [
		{ type: "label", text: name, x: 100, y: 30, width: 200, height: 20 },
	];
	var columns = 14
	var span = 130;

	for (var i = 0; i < icons.length; i++)
	{
		var icon = icons[i];
		var id = getId(icon);
		var x = 20 + (i % columns) * span;
		var y = 50 + Math.floor(i / columns) * span;
		widgets.push({
			type: "button", image: id, x: x, y: y, width: 32, height: 32
		});
		widgets.push({
			type: "label", text: (icon[0] + "\n" + icon[1]), x: x, y: y + 40, width: span, height: 32
		});
	}
	return widgets;
}
```

</details>

So besides the few small issues, LGTM! Thank you all for your time.

2022-12-09 23:14 UTC, Basssiiie commented on src/openrct2/scripting/G2Names.hpp
> +        { "rct1_close_off_pressed", SPR_G2_RCT1_CLOSE_BUTTON_3 },
Should be `"rct1_close_on_pressed"` instead of "off".

2022-12-09 23:14 UTC, Basssiiie commented on src/openrct2/scripting/G2Names.hpp
> +        { "rct1_test_off_pressed", SPR_G2_RCT1_TEST_BUTTON_3 },
Should be `"rct1_test_on_pressed"` instead of "off".

2022-12-09 23:14 UTC, Basssiiie commented on src/openrct2/scripting/G2Names.hpp
> +        { 29442, SPR_G2_TOOLBAR_MUTE_PRESSED },
Should be `29443` instead of `29442` (which is MUTE above it).

2022-12-09 23:14 UTC, Basssiiie commented on distribution/openrct2.d.ts
> +        "rct1_close_off" | "rct1_close_off_pressed" | "rct1_close_on" | "rct1_open_off" | "rct1_open_off_pressed" |
`"rct1_close_on_pressed"` and `"rct1_test_on_pressed"` are missing in this string union.

2022-12-10 10:34 UTC, Gymnasiast commented on distribution/openrct2.d.ts
> +        "normal_selection_6x6" | "paste" | "path_railings" | "path_surface" | "paths" | "placeholder" |
path_surface > path_surfaces

2022-12-10 12:31 UTC, Basssiiie approved these changes

2022-12-11 13:25 UTC, Gymnasiast commented on distribution/openrct2.d.ts
> +        "normal_selection_6x6" | "paste" | "path_railings" | "path_surface" | "paths" | "placeholder" |
No, they are not. All the tab images for objects should use plural - if these two do not, then their file names should be changed (in another PR).

2022-12-11 13:27 UTC, Gymnasiast requested changes
Please fix the icon names as I requested.

Also change `G2Names.hpp` to `IconNames.hpp` - icons from g1 should be added as well (in another PR, preferably).

2022-12-11 13:46 UTC, IntelOrca commented
> Also change G2Names.hpp to IconNames.hpp - icons from g1 should be added as well (in another PR, preferably).

Use `IconNames.h`. `.hpp` is for header-only implementations (i.e. fully implemented classes without a .cpp file).

2022-12-11 18:26 UTC, Gymnasiast commented
> > Also change G2Names.hpp to IconNames.hpp - icons from g1 should be added as well (in another PR, preferably).
> 
> Use `IconNames.h`. `.hpp` is for header-only implementations (i.e. fully implemented classes or functions without a .cpp file).

There are a few functions defined in that file, so doesn’t .hpp make more sense here?

2022-12-11 23:46 UTC, IntelOrca commented
I didn't realise it was in scripting. I originally made most of the scripting code .hpp to reduce code and definition duplicates. But that has since been changed and now scripting files have been changed into .h and .cpp pairs. So I don't know what the plan is now with new stuff.

2022-12-12 22:40 UTC, Gymnasiast approved these changes

2022-12-12 23:03 UTC, merged