Remove gotos in vehicle.cpp
OpenRCT2/OpenRCT2 pull request #18926
Opened 2022-12-24 03:50 UTC by frutiemax

2022-12-24 04:00 UTC, frutiemax commented
Do not merge, there is an infinite loop in one of the commits...

2022-12-25 14:28 UTC, janisozaur commented
This issue is filed as https://github.com/OpenRCT2/OpenRCT2/issues/11394 and there @glaubertadeu made the changes already, long time ago, but never submitted the pr. The code is available in their fork.

I'd like to test this pr, but it will take a bit of time until I'm ready, maybe even few weeks.

2022-12-25 21:08 UTC, frutiemax commented
git.exe bisect bad
80bc70960b949253895fe3fb693ebd3ff1c0141a is the first bad commit
commit 80bc70960b949253895fe3fb693ebd3ff1c0141a
Author: frutiemax <lucas.malo.belanger@gmail.com>
Date:   Fri Dec 23 21:52:52 2022 -0500

Remove goto label loc_6DC985

src/openrct2/ride/Vehicle.cpp | 114 +++++++++++++++++++++++++++++++++---------
1 file changed, 91 insertions(+), 23 deletions(-)

2022-12-27 10:02 UTC, tupaschoal commented
Note even though you force pushed yesterday, it has some merge conflicts with Vehicle

2022-12-31 19:34 UTC, Gymnasiast commented
I checked the commits up to and including "Remove goto label loc_6DC743". The next one is quite a bit more complicated. I might split the PR in two.

2023-02-20 08:14 UTC, duncanspumpkin commented
@frutiemax could you rebase this and split it into two PRs. Just the first 8 or so commits in this one.

2023-02-20 12:17 UTC, Gymnasiast commented
I would recommend putting everything up to and including `loc_6DC743` into the first one - I have already checked these and found them to be correct.

2023-03-04 10:54 UTC, tupaschoal commented
Ping @frutiemax

2023-03-19 09:56 UTC, Gymnasiast commented
Please keep this open, I can take take some things over if needed.

2023-04-03 07:41 UTC, Broxzier requested changes
Code looks mostly good and the replays pass which is promising, but I'd like to verify this with a couple of parks with lots of rides to make ensure that the logic is identical. Recording a 3-minute replay of a park with lots of different rides should cover most of this.

2023-04-03 07:41 UTC, Broxzier commented on src/openrct2/ride/Vehicle.cpp
> +
Accidental blank line

2023-04-03 07:41 UTC, Broxzier commented on src/openrct2/ride/Vehicle.cpp
> +                        Loc6DCDE4(*curRide);
Same as previous comment.

2023-04-03 07:45 UTC, Broxzier commented on src/openrct2/ride/Vehicle.cpp
> +            Loc6DCDE4(curRide);
Same as previous comment.

2023-04-17 19:45 UTC, Broxzier commented
@frutiemax Will you be able to tackle the comments above and get this in a mergable state?

2023-05-19 07:11 UTC, Gymnasiast commented
I might take a stab, please don’t close this just yet.

2023-06-20 06:49 UTC, Gymnasiast commented
Keep this open please.

2023-07-22 13:29 UTC, Gymnasiast commented
Keep this open please.

2023-08-25 07:50 UTC, Gymnasiast commented
Keep this open please.

2023-12-23 16:04 UTC, Gymnasiast commented
I decided to split this PR into two. The first 10 commits (all of which I have been able to check) are here: https://github.com/OpenRCT2/OpenRCT2/pull/21111

After that one is merged, I intend to do the other five.

2024-09-08 10:04 UTC, tupaschoal commented
Superseded by #21111 and #22712, likely too old to reuse anyway, thus closing this.

2024-09-08 10:04 UTC, closed without merging