Ride/rename blockbrake
OpenRCT2/OpenRCT2 pull request #18965
Opened 2022-12-29 07:22 UTC by spacek531

Picked from the speedy block brakes pull request. This PR is focused at removing the "Block" part of "Block Brake" for most references to block brake status, as speedy block brakes PR introduces the concept of brakes being open and closed.

This PR makes the following changes:

- Rename `TrackElement::SetBlockBrakeClosed` to `TrackElement::SetBrakeClosed`
- Rename `TrackElement::BlockBrakeClosed` to `TrackElement::IsBrakeClosed`
- Change the tile inspector to display "Brake Closed" instead of "Block Brake Closed" for the flag, unless a block brake is selected
- Rename `blockBrake` variable in TileModifyAction.cpp/h and openrct2/.../TileInspector.cpp/h to `isClosed` to match use in `SetBrakeClosed`
- Assorted renames of variables with "block brake" in their names

2022-12-29 07:37 UTC, spacek531 commented on src/openrct2/ride/Ride.cpp
> +void Ride::MoveTrainsToBlockBrakes(const CoordsXYZ& firstBlockPosition, TrackElement& firstBlock)
firstBlockPosition is only used in speedy block brakes, it just got included because of interactive commit.

2022-12-30 20:21 UTC, Gymnasiast commented on src/openrct2/localisation/StringIds.h
> +    STR_TILE_INSPECTOR_TRACK_BRAKE = 6539,
```suggestion
    STR_TILE_INSPECTOR_TRACK_BRAKE_CLOSED = 6539,
```

2022-12-30 20:22 UTC, Gymnasiast commented on src/openrct2/ride/Ride.cpp
> +void Ride::MoveTrainsToBlockBrakes(TrackElement& firstBlock)
Please revert the bits here that are not related to the name change.

2022-12-30 20:23 UTC, Gymnasiast requested changes
Looks good, point 2 points to address.

2022-12-30 21:20 UTC, spacek531 commented
Those things are now reverted

2022-12-31 13:06 UTC, Gymnasiast approved these changes

2022-12-31 13:06 UTC, merged