Refactor TopToolbar to class
OpenRCT2/OpenRCT2 pull request #19043
Opened 2023-01-04 07:02 UTC by johnpatek

Closes #18326 

Notes for reviewers:
+ All static functions have been moved to private class members, with the exception of `ScenarioSelectCallback` which is now a static member.
+ I was concerned about the FPS being throttled by repeated calls to `OnPrepareDraw`, so the previous call to `WindowTopToolbarInvalidate` was refactored to be split between `OnOpen` and `OnPrepareDraw`.
+ Some of the local variables have been renamed, most notably `flags` has become `flag`, in an effort to avoid clashing with member variables in the parent class.

2023-01-17 01:00 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    window->widgets = window_top_toolbar_widgets;
This assignmet should be on the `TopToolbar` constructor

2023-01-17 01:01 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    WindowInitScrollWidgets(*window);
Move this to the same constructor mentioned above, where it can become just `InitScrollWidgets()`

2023-01-17 01:02 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        auto range = MapRange(gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y);
```suggestion
        auto range = MapRange(gMapSelectPositionA, gMapSelectPositionB);
```

2023-01-17 01:02 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    ClearAction GetClearAction()
It seems like this function could be a `static` function outside the class, since it doesn't rely on any member variable.

2023-01-17 01:05 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[1] | 0x80, 0,
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[1] | 0x80, 0,
```

2023-01-17 01:09 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[1] | 0x80, 0, i);
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[1] | 0x80, 0, i);
```

2023-01-17 01:10 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[0] | 0x80, 0, num_items);
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[0] | 0x80, 0, num_items);
```

2023-01-17 01:12 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        if (w != nullptr)
```suggestion
        if (auto w = window_get_main(); w != nullptr)
```

2023-01-17 01:13 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[1] | 0x80, 0, 2);
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[1] | 0x80, 0, 2);
```

2023-01-17 01:14 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        if (w != nullptr)
```suggestion
        if (auto* w = window_get_main(); w != nullptr)
```

2023-01-17 01:15 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[0] | 0x80, 0,
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[0] | 0x80, 0,
```

2023-01-17 01:17 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    void CheatsMenuDropdown(int16_t dropdownIndex)
Sounds like this one could be a free function

2023-01-17 01:17 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[0] | 0x80,
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, widget.top }, widget.height() + 1, colours[0] | 0x80,
```

2023-01-17 01:18 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        if (w != nullptr)
```suggestion
       if (auto* w = window_get_main(); w != nullptr)
```

2023-01-17 01:19 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { windowPos.x + widget.left, windowPos.y + widget.top }, widget.height() + 1, colours[0] | 0x80, 0,
```suggestion
            windowPos + ScreenCoordsXY{ widget.left, idget.top }, widget.height() + 1, colours[0] | 0x80, 0,
```

2023-01-17 01:20 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        if (w != nullptr)
```suggestion
        if (auto* w = window_get_main(); w != nullptr)
```

2023-01-17 01:21 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    void NetworkMenuDropdown(int16_t dropdownIndex)
Sounds like it could be a free function

2023-01-17 01:25 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +                { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y }, gMapSelectType,
```suggestion
                { gMapSelectPositionA, gMapSelectPositionB }, gMapSelectType,
```

2023-01-17 01:25 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y }, gMapSelectType);
```suggestion
            { gMapSelectPositionA, gMapSelectPositionB }, gMapSelectType);
```

2023-01-17 01:26 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +                { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y }, gMapSelectType,
```suggestion
                { gMapSelectPositionA, gMapSelectPositionB }, gMapSelectType,
```

2023-01-17 01:26 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +            { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y }, gMapSelectType);
```suggestion
            { gMapSelectPositionA, gMapSelectPositionB }, gMapSelectType);
```

2023-01-17 01:27 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    int16_t _unkF64F0A;
```suggestion
    bool _landToolBlocked {false};
    uint8_t _unkF64F0E {0};
    int16_t _unkF64F0A {0};
```

2023-01-17 01:28 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    static void ScenarioSelectCallback(const utf8* path)
Seems like it could be a free function

2023-01-17 01:30 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    void RepaintSceneryToolDown(const ScreenCoordsXY& screenCoords, WidgetIndex widgetIndex)
Seems like it could be a free function

2023-01-17 01:30 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +    void SceneryEyedropperToolDown(const ScreenCoordsXY& screenCoords, WidgetIndex widgetIndex)
Seems like it could be a free function

2023-01-17 01:35 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +        if (window == nullptr || window->viewport == nullptr)
What happened to these checks?
```
    WidgetIndex widget_index = window_find_widget_from_point(*window, screenPos);
    if (widget_index == -1)
        return;
    const auto& widget = window->widgets[widget_index];
    if (widget.type != WindowWidgetType::Viewport)
        return;
```

2023-01-17 01:36 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +                { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y });
```suggestion
                { gMapSelectPositionA, gMapSelectPositionB });
```

2023-01-17 01:36 UTC, tupaschoal commented on src/openrct2-ui/windows/TopToolbar.cpp
> +                { gMapSelectPositionA.x, gMapSelectPositionA.y, gMapSelectPositionB.x, gMapSelectPositionB.y });
```suggestion
                { gMapSelectPositionA, gMapSelectPositionB });
```

2023-01-17 07:09 UTC, duncanspumpkin commented
Also just a word of warning we are doing a big refactor this week that changes all snake case things so you will need to rebase this after the week is over.

2023-01-27 10:49 UTC, Broxzier commented
The big snake_case refactor is done now, could you rebase this PR?

2023-02-03 21:19 UTC, duncanspumpkin commented
I've rebased this and renamed everything after the snake hunt.

2023-02-05 22:33 UTC, Broxzier requested changes
The land tool seems to be broken, and doesn't give any feedback when it can't perform an action (e.g. land outside the park).  I noticed that when the game is paused, it does give an error, but already as soon as you press the mouse button.

All other tools work as expected, though. I'll give this another look tomorrow.

2023-02-13 22:01 UTC, Broxzier commented
To make the diff clean and keep things from bitrotting, I've rebased and squashed this PR now. Will you let us know if you are going to look into the land tool issue? Also, when you do, please reset your branch, otherwise we may end up with another merge commit that makes rebasing very annoying to do.

2023-02-13 22:19 UTC, Broxzier commented
I've found the issue and pushed a fix. I guess you ran into a compiler warning where a local variable named `viewport` was hiding the class' member with the same name, and resolved this warning by removing the local.

2023-02-13 22:20 UTC, Broxzier approved these changes

2023-02-14 21:18 UTC, duncanspumpkin approved these changes

2023-02-14 21:19 UTC, merged