Hide landscaping tools when scenario disallows landscaping
OpenRCT2/OpenRCT2 pull request #19805
Opened 2023-04-03 01:39 UTC by bitman2049

Fix #18995

2023-04-03 08:48 UTC, ZehMatt commented
This got me thinking a bit, when people enable cheats such as disable clearance checks or sandbox mode the UI would remain inaccessible.

2023-04-03 08:54 UTC, ZehMatt commented
Also people can change the scenario options while playing, I believe this would still keep the buttons hidden even when the user removed the scenario option because the window is created at the very beginning of/after map load.

2023-04-03 08:54 UTC, Broxzier commented
Yeah, I was thinking something similar. I'd expect the buttons to appear when sandbox mode is active, but not when clearance checks are disabled.

Also, when a player disables the scenario option, these two buttons should be enabled again.

2023-04-03 23:10 UTC, bitman2049 commented
> Yeah, I was thinking something similar. I'd expect the buttons to appear when sandbox mode is active, but not when clearance checks are disabled.
> 
> Also, when a player disables the scenario option, these two buttons should be enabled again.

Adding `&& !gCheatsSandboxMode` to the if statement seems to be adequate. Are there any other conditions where it makes sense to override the scenario options?

2023-04-06 14:09 UTC, Broxzier reviewed
I'm not able to test this at the moment, will try to later today. From the looks of it, I suspect the buttons are only disabled but never re-enabled? Some things to test are:
 - Do hotkeys also no longer work?
 - Do the buttons disappear and reappear when the scenario option is toggled, or when sandbox mode is toggled?

2023-04-06 14:09 UTC, Broxzier commented on distribution/changelog.txt
> +- Improved: [#18995] When land changes are disallowed, disable the Land and Water windows
```suggestion
- Improved: [#18995] When land changes are disallowed, the Land and Water tools can no longer be opened.
```

2023-04-13 11:19 UTC, Broxzier requested changes
Gave this a spin, and ran into two issues:

 - When toggling the setting in the Scenario Editor, then the buttons will also be unavailable when the player goes back to the previous steps.
 - When toggling this option from the Scenario Options window during a game, the buttons remain visible, though unusable. Invalidating the top toolbar is likely enough to fix this.

2023-04-13 11:19 UTC, Broxzier commented on src/openrct2-ui/input/Shortcuts.cpp
> +            && (!(gParkFlags & PARK_FLAGS_FORBID_LANDSCAPE_CHANGES) || gCheatsSandboxMode))
Instead of checking `gCheatsSandboxMode`, you'll also need to check if the player is in the scenario editor. This is another screen flag, I believe.

2023-04-13 11:19 UTC, Broxzier commented on src/openrct2-ui/input/Shortcuts.cpp
> +            && (!(gParkFlags & PARK_FLAGS_FORBID_LANDSCAPE_CHANGES) || gCheatsSandboxMode))
This is the same check as before, and since it's quite big already, please move this to a separate function.

2023-06-02 02:05 UTC, closed without merging