SetCheatAction has wrong ID in plugin API
OpenRCT2/OpenRCT2 pull request #19987
Opened 2023-04-18 08:12 UTC by Sadret

Mistake while implementing #19018

Please squash before merge.

2023-04-18 08:23 UTC, Broxzier requested changes

2023-04-18 08:23 UTC, Broxzier commented on distribution/changelog.txt
> +- Fix: [#19987] SetCheatAction has wrong ID in plugin API.
```suggestion
- Fix: [#19987] [Plugin] ‘SetCheatAction’ has wrong ID in plugin API.
```

2023-04-18 11:23 UTC, Broxzier approved these changes

2023-04-18 11:23 UTC, merged

2023-04-22 17:42 UTC, CorySanin commented
I got to be honest, who cares if the action name is "right" or "wrong"? All I know as a consumer of the plugin API is that one of my plugins broke again. I know that's the purpose of the different API versions. But now if someone wants to develop a backwards-compatible plugin that utilizes this action, there are *three* possible action names. Maybe there's something I'm missing here, but in the future I would oppose seemingly arbitrary changes like this.

2023-04-23 08:47 UTC, Broxzier commented
We care. A change for consistency is not arbitrary. The action was not even documented as "setcheat", this change makes it actually match the API.