Fix #20096: Server list window scroll is glitched when server list is empty
OpenRCT2/OpenRCT2 pull request #20099
Opened 2023-04-30 09:30 UTC by beam41

Scroll widget have incorrect size set, plus cast to uint16_t makes it underflow.

Actually there are some more scrollbar with incorrect size. like one in select scenario which update when you reopen.
![image](https://user-images.githubusercontent.com/1791353/235345918-cf892b8e-2703-4ba8-9b3b-ff4339cabf10.png)
![image](https://user-images.githubusercontent.com/1791353/235345933-bdaec67f-724c-4760-843e-f321f16d5fe6.png)

Fix #20096

2023-05-05 20:58 UTC, ZehMatt requested changes
I've tested it and it all seems fine, left a comment otherwise all good.

2023-05-05 20:58 UTC, ZehMatt commented on src/openrct2/interface/Window.cpp
> +            double barPosition = ((scroll.v_thumb_bottom * 1.0) / view_size);
Unrelated change, please revert this.

2023-05-05 21:37 UTC, frutiemax commented on src/openrct2/interface/Window.cpp
> +            double barPosition = ((scroll.v_thumb_bottom * 1.0) / view_size);
Why use double over float?

2023-05-06 10:52 UTC, ZehMatt approved these changes
Thanks, all good. Could you add a changelog entry as this bug was introduced in 0.4.4

2023-05-06 12:56 UTC, beam41 commented
> Thanks, all good. Could you add a changelog entry as this bug was introduced in 0.4.4

Done

2023-05-06 12:57 UTC, ZehMatt commented
Sorry but could you rebase the PR, we just merged a few things that changed changelog.txt

2023-05-06 14:01 UTC, merged