Rework Object Identifier callers
OpenRCT2/OpenRCT2 pull request #20271
Opened 2023-05-22 07:59 UTC by duncanspumpkin

`FindObjectLegacy` is a broken function that can cause incorrect objects to be returned. I've replaced 2 callers with FindObject. (FindObject is also broken but at least we pass that the correct fields to fix it {follow on pr hopefully}). GetObjectOverrideStringId is how we originally overrode the language strings for official objects. It is no longer used.

2023-05-26 16:15 UTC, Gymnasiast commented
Is it okay if I test this before it’s merged?

2023-05-26 18:05 UTC, ZehMatt commented
> Is it okay if I test this before it’s merged?

Would be generally good if more people tested PR's and would leave feedback on what they find, you don't have to ask for permissions really.

2023-05-31 07:33 UTC, Gymnasiast commented
Sure, but I’d like to test it _before_ it gets merged, and I can’t exactly demand that - hence why I prefer to ask.

Sorry for the delay, btw, I have been busy. I’ll try to test this tonight or tomorrow.

2023-06-09 07:34 UTC, duncanspumpkin commented on data/language/en-GB.txt
> -
Yes we should not be overriding the non official objects. If its an official object its overriden by the json file we shouldn't have multiple locations that can override things.

Also `(note that other language have more of these)` no they don't every language is currently only overriding this one object.
https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/data/language/ar-EG.txt#L4083
https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/data/language/tr-TR.txt#L3846
https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/data/language/de-DE.txt#L4136

2023-06-09 16:21 UTC, Gymnasiast commented on data/language/en-GB.txt
> -
> Yes we should not be overriding the non official objects. 

I cannot say I agree. We’re talking about _very_ common objects with broken/messy descriptions. Also, the overrides provide a way to add translations that RCT2 did not support.

> no they don't every language is currently only overriding this one object

That is simply untrue. Check Dutch for example, it overrides 11 objects: https://github.com/OpenRCT2/Localisation/blob/master/data/language/nl-NL.txt#L4542

2023-06-19 20:07 UTC, ZehMatt approved these changes
LGTM, tested this and everything seems fine.

2023-06-19 21:05 UTC, Gymnasiast requested changes
I would _really_ prefer if the object localisation removal was reversed. There seems to be no technical reason for it, it works as intended and has a use.

2023-06-26 11:48 UTC, Broxzier approved these changes
This is quite a clean up. I find it odd we have these "fixes" for unofficial objects in the codebase. If you look at where `GetLegacyIdentifier` is used, there are a couple more:

https://github.com/OpenRCT2/OpenRCT2/blob/fb1b531d597c376d1dfc7ba81108651f409309ee/src/openrct2/object/WallObject.cpp#L47

https://github.com/OpenRCT2/OpenRCT2/blob/fb1b531d597c376d1dfc7ba81108651f409309ee/src/openrct2/object/SmallSceneryObject.cpp#L161-L172

I agree that these fixes - even if made on the fly - shouldn't be made to existing objects. Only official objects should be fixed, and then in the data itself instead of on the fly.

2023-06-26 13:06 UTC, ZehMatt commented
> This is quite a clean up. I find it odd we have these "fixes" for unofficial objects in the codebase. If you look at where `GetLegacyIdentifier` is used, there are a couple more:
> 
> https://github.com/OpenRCT2/OpenRCT2/blob/fb1b531d597c376d1dfc7ba81108651f409309ee/src/openrct2/object/WallObject.cpp#L47
> 
> https://github.com/OpenRCT2/OpenRCT2/blob/fb1b531d597c376d1dfc7ba81108651f409309ee/src/openrct2/object/SmallSceneryObject.cpp#L161-L172
> 
> I agree that these fixes - even if made on the fly - shouldn't be made to existing objects. Only official objects should be fixed, and then in the data itself instead of on the fly.

Yeah I agree, fixing content with code should never be a thing in my opinion, if the authors are not willing to fix those objects I'm sure that the community can just re-create them and also use the new object format.

2023-06-26 13:11 UTC, merged