Fix #19822: Copied banners animate properly and no longer refer to original
OpenRCT2/OpenRCT2 pull request #20313
Opened 2023-05-30 14:46 UTC by mrmbernardi

This is a fix for #19822. 

The original code does a deep copy, but then uses the ID of the original on the tile anyway. I've fixed that bug and also fixed another where the map animation doesn't get added.

I haven't fixed it so that you're allowed to copy a banner, delete the original, and then paste it. It seems like a complicated change for questionable benefit. Perhaps instead we can give a real message for "original banner deleted".

2023-06-04 21:02 UTC, Broxzier requested changes
I don't think these changes really fix anything. It still relies on the existence of the original element.

```cpp
if (bannerIndex != BannerIndex::GetNull() && GetBanner(bannerIndex) == nullptr)
```

The map animation fix is nice though, this should actually also be done for other elements that animate, like scenery, park entrances, and ride entrances. Changes like that should be separated into their own commit, since they are not related.

2023-06-05 15:21 UTC, mrmbernardi commented
> I don't think these changes really fix anything. It still relies on the existence of the original element.

Before this fix, the code would do a deep copy but then not use it, so if you were to do anything to the original banner the pasted one would be affected. This fix makes the tile where the banner is pasted refer to the copied banner, not the original, so things work as expected after you paste a banner.

At paste time, yes the original needs to exist as that's when the deep copy occurs. Fixing this would be a bit more involved. I said "It seems like a complicated change for questionable benefit." because I don't think pasting deleted banners is so useful. But if it's a requirement, I'd imagine we'd need to make a new action to duplicate an entry in the banner array on copy time (and paste time so subsequent pastes work as expected), and another action to delete the entry when the user copies something else or closes the window. Behaviour would also be a bit weird when pasting a banner a number of times and running up against the banner limit as you would get the error after the last successful paste, not when trying to paste beyond the banner limit.

2023-06-05 22:55 UTC, mrmbernardi commented
I've updated the code to serialise a banner object in the `TileModifyAction` object. To me, it seems a bit wasteful as most of the time the banner struct will just be zeros unless you're copying a banner, but you avoid having to create different actions just for copying banners. 

The downside of not having the copied banner data in the banner array is that if you copy a banner linked to a ride, and someone deletes the ride and then builds another that gets the same index, pasted banners will be linked to the new ride. But this is a minor issue so maybe it's still acceptable.

2023-06-06 09:41 UTC, Broxzier reviewed
Changes LGTM. Haven't tested it in-game yet. Please update the network version and plug-in API version, since this touches the game logic and game actions.

2023-06-06 17:17 UTC, mrmbernardi commented on src/openrct2/world/TileInspector.cpp
> +                // The element to be pasted refers has a banner - make a copy of it from the banner provided
Changed

2023-06-06 17:18 UTC, mrmbernardi commented
> Changes LGTM. Haven't tested it in-game yet. Please update the network version and plug-in API version, since this touches the game logic and game actions.

I have updated the network version but I'm not sure if the plug-in API needs to be updated. As far as I can tell, `pasteElement` was never visible to the plugin and `pasteBanner` is not visible either.

2023-06-28 09:55 UTC, mrmbernardi commented
I've rebased and added the changelog entry

2023-06-30 22:15 UTC, Broxzier approved these changes
Tested, and everything seems to work fine.

2023-07-02 17:00 UTC, ZehMatt approved these changes
Briefly tested this and code looks good, this needs a rebase.

2023-07-02 19:35 UTC, mrmbernardi commented
rebased

2023-07-02 21:32 UTC, merged