Fix #20364: Money cheat no longer overflows
OpenRCT2/OpenRCT2 pull request #20475
Opened 2023-06-25 23:31 UTC by mrmbernardi

This is a fix for #20364

I have simply changed the types in the game action parameters to int64_t and updated the limit to match.

2023-06-26 15:01 UTC, mrmbernardi commented
@ZehMatt I've done the rebase here

2023-06-26 15:54 UTC, ZehMatt approved these changes

2023-06-27 11:53 UTC, Broxzier requested changes
Thanks for your PR! Could you add a changelog entry for this fix? The [changelog is located in the distribution folder](https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/changelog.txt).

Since this is your first PR, you may also add yourself to the list in [contributors.md](https://github.com/OpenRCT2/OpenRCT2/blob/develop/contributors.md).

For any future commits, please reword the commit message so that it describes the problem, e.g. "Fix #XXXX: Adding too much money with cheats causes an overflow.".

2023-06-27 13:05 UTC, Broxzier approved these changes

2023-06-27 13:07 UTC, Broxzier commented
> I've made the changes. FYI this is my 6th PR and I've had a PR merged before.

Thanks! And I noticed after my review, GitHub still lists you as "First-time contributor", despite already having a PR merged. There is now a merge conflict with the changelog, could you rebase this PR?

2023-06-27 13:12 UTC, mrmbernardi commented
Oops, should be resolved now.

2023-06-27 13:29 UTC, merged