Fix #20496: Relax requirements for compact inverted coasters
OpenRCT2/OpenRCT2 pull request #20505
Opened 2023-06-28 04:40 UTC by aramk-hub

Fixed #20496 where compact inverted coasters did not get the relaxed requirements when there were inversions since the boolean for it was originally set to false.

2023-06-28 07:14 UTC, duncanspumpkin commented
Are you able to work out when it was changed?

2023-06-28 13:24 UTC, aramk-hub commented
Seems like it was introduced with fe219281ec6b66e3a47c67125c939bc1f01d1274 as false, and wasn't in the file before this

2023-06-28 13:28 UTC, ZehMatt approved these changes
This needs a changelog entry.

Note to @OpenRCT2/developers, Given that all tests pass we probably have no park that covers this case currently, we should update the EverythingPark to include this.

2023-06-28 14:38 UTC, Broxzier commented
> Given that all tests pass we probably have no park that covers this case currently, we should update the EverythingPark to include this.

The original issue has a track design already provided, so it should be as simple as just placing this. Do replays recalculate all ride stats, though? Otherwise it's pointless since it's just checking cached data.

2023-06-28 17:42 UTC, ZehMatt commented
> > Given that all tests pass we probably have no park that covers this case currently, we should update the EverythingPark to include this.
> 
> The original issue has a track design already provided, so it should be as simple as just placing this. Do replays recalculate all ride stats, though? Otherwise it's pointless since it's just checking cached data.

We have separate tests for ride ratings

2023-07-02 09:28 UTC, ZehMatt commented
Also forgot that this needs a network version bump.

2023-07-09 13:58 UTC, ZehMatt commented
@aramk-hub could you raise the network version? Then it would be good to go.

2023-08-12 15:43 UTC, SpartanFrederic104 commented
Please keep this open if it's still being worked on

2023-08-23 19:17 UTC, ZehMatt approved these changes

2023-08-23 19:19 UTC, Broxzier requested changes

2023-08-23 19:19 UTC, Broxzier commented on distribution/changelog.txt
> +- Fix: [#20496] Relax ride rating requirements for compact inverted coasters.
This should say what was broken, not what has changed.

```suggestion
- Fix: [#20496] Ride rating requirements for compact inverted coasters is no longer relaxed.
```

2023-08-23 19:23 UTC, Broxzier approved these changes

2023-08-23 19:50 UTC, merged