Set default ride price to free if park entrance fee has been set
OpenRCT2/OpenRCT2 pull request #20790
Opened 2023-09-15 07:06 UTC by krrg

In RCT1, if a park entrance fee was set, then the ride prices would default to 0 (you could still charge for rides, but the default would be to have free rides in these parks).
In RCT2, one could only charge for rides _or_ for park entrance, but not both.
OpenRCT2 brought back the ability to charge for both the park entrance and for rides, but the default ride prices are still being left as their defaults. Because guests are only willing to pay 1/4 as much for rides if they paid an entrance fee for the park, the default ride prices are generally much too high. In my view, the RCT1 behavior of defaulting rides to free in a pay-for-entrance park was a useful behavior.

This simple change brings back the RCT1 behavior. If a park entrance fee is in effect, then the rides will default to free (you can still change it to whatever you want if you desire). This only affects "rides" not shops.

Would love to have discussion on whether this is the behavior we think is best.

2023-09-15 13:30 UTC, ZehMatt commented
Wouldn't it be better to change the default price to 1/4 rather than making it free? OpenRCT2 targets primarily RCT2 behavior, what is the default ride price in RCT2 if the there is an entrance fee for the park?

2023-09-15 14:09 UTC, MASHzj commented
Then it's free because RCT2 doesn't allow both charging for entry and rides.

2023-09-15 18:05 UTC, ZehMatt commented
Makes sense then. The code change looks good to me. This needs a network version bump and a changelog entry.

2023-09-17 11:59 UTC, ZehMatt requested changes
One small thing otherwise looking good

2023-09-17 11:59 UTC, ZehMatt commented on distribution/changelog.txt
> +- Change: [#20790] Default ride price set to free if park charges for entry
```suggestion
- Change: [#20790] Default ride price set to free if park charges for entry.
```

2023-09-18 03:47 UTC, ZehMatt approved these changes

2023-09-18 07:18 UTC, merged