Disable creating money effect when paused
OpenRCT2/OpenRCT2 pull request #20796
Opened 2023-09-18 20:28 UTC by KatieZeldaKat

Previously when building in pause mode, money effects would clutter the screen and not go away unless a player resumed the game for the animation to take place. This pull request makes it so that the money effect is no longer created when the game is paused. This is also a re-implementation of former functionality, as this used to be the case after v0.1.0 and before v0.2.3 (more info below).

---

In #5733, the money effect was disabled when building in pause mode to prevent a crash when too many sprites were being animated at once (#3479). This used to be implemented as such:

```
// Create a +/- money text effect
if (cost != 0 && game_is_not_paused())
    money_effect_create(cost);
```

While this code still existed in v0.2.3, for whatever reason, the money effect started to be created even when the game was paused. Multiple users have since mentioned that it would be beneficial to not have these sprites generate when paused, though some have also mentioned the alternative of animating the sprites when paused instead:

- [Reddit: How to disable money animations from building?](https://www.reddit.com/r/openrct2/comments/uy418t/how_to_disable_money_animations_from_building/)
- #17036

Through intensive digging, I don't believe this functionality was removed intentionally, especially as the changelog makes no mention of reverting this functionality in v0.2.3 after describing its introduction in v0.1.0. As such, this pull request adds back the logic of the above code block, now inside of `MoneyEffect::CreateAt()`.

Although it could be argued that the true solution to the sprite problem when building in pause mode is to animate them when paused, this solution to re-implement the former functionality is simpler and ensures players can build in pause mode without as much screen clutter. At a future date the more complex solution may be considered.

2023-09-19 07:04 UTC, janisozaur commented
This requires network version bump

2023-09-19 14:07 UTC, KatieZeldaKat commented
Bumped the network version

2023-09-19 14:11 UTC, ZehMatt commented
Also add a changelog entry please.

2023-09-19 14:27 UTC, KatieZeldaKat commented
Changelog entry added

2023-09-20 08:03 UTC, ZehMatt approved these changes

2023-09-20 11:57 UTC, Broxzier commented
I always kinda liked the money effects all moving in sync when you u pause after having built a whole lot.

2023-09-20 13:26 UTC, ZehMatt commented
We could turn this into an option also, we can apply the same thing I did to ensure multiplayer stays in sync by simply not drawing them rather than disabling the creation.

2023-10-02 18:37 UTC, KatieZeldaKat commented
Just updated the branch to no longer conflict with `develop`.

Is there substantial reason to go with a different solution? Personally, I am fine with the current implementation and would love this change to improve visibility when building in pause mode. Although I can admit to my bias in that.

2023-10-02 22:04 UTC, ZehMatt requested changes
Gave it some more thought, this will probably cause desyncs when the host paused the game and performs game actions, since other clients don't have this setting synchronized this would create money entities where the host wouldn't. It might be best to simply not draw the money when paused for clients that have this setting enabled keeping the entities in sync and just hide it visually.

2023-11-27 23:41 UTC, KatieZeldaKat commented
Money effects are now always created, and their rendering is what is affected by this change. A new option has been added to the menu which specifies whether building costs should be shown when paused. This is disabled by default:

![Options screen showing a new option that says "Show building costs when paused"](https://github.com/OpenRCT2/OpenRCT2/assets/42878595/6df5e7be-35d0-4fe0-8750-bed4071f6c61)

[The second implementation listed here](https://github.com/OpenRCT2/OpenRCT2/pull/20796#issuecomment-1728247219) is what I ended up going for in the new changes. It makes it so that in default gameplay, nothing changes in how the game renders the money effects. It's when people enable the cheat for building in pause mode in which people will notice the money effects will no longer clutter the screen.

When resuming the game, the money effects will display, even after pausing the game once again.

2023-11-28 00:39 UTC, ZehMatt commented on data/language/en-GB.txt
> +STR_6595    :Show building costs when paused
I'm not sure if that is the best description, the money effect can appear for removing things as well. I think a better description could be something like "Show money effect when paused"

2023-11-28 00:40 UTC, ZehMatt commented on src/openrct2/config/Config.h
> +    bool ShowBuildCostIfPaused;
I would go for `ShowMoneyEffectIfPaused`, see my comment on the strings.

2023-11-28 01:20 UTC, karst commented
I think it makes sense for the animation to play when you unpause the game if the cheat is activated and have the animation not show up yet while paused. You see the money go down. I don't think an option would be necessary for that, it'd just be quality of life improvement for the build in pause mode cheat.

2023-12-05 03:19 UTC, ZehMatt commented
Well I'm personally a bit split on this, while its handy to not have the money show up initially it however adds two problems.
1. It will pollute the entity registry with invisible entities basically, if you do a lot of construction while paused it will be relatively easy to have hundreds of even thousands of money entities just wasting away resources.
2. If you did a lot of things while paused and accumulated hundreds if not thousands of money entities it will be quite the show once you unpause the game.

As for the option to just not create the money is not feasible for multiplayer as that will cause desyncs, we had this issue before with the show guest purchases option which I changed to simply not render those when the option is enabled which keeps all clients in sync still.

I think the middle ground is to always animate the money regardless if its paused or not but also additionally have the option to  hide the money as long the game is paused and not just for the time when they are created, that would be also not too difficult to implement without having a ton of new complex logic.

2023-12-21 16:34 UTC, KatieZeldaKat commented
Closing in favor of #21102.

It doesn't have the suggested setting to hide all money effects when the game is paused, but I also wouldn't be surprised if it's not needed. I have changed my opinion to say that preserving the functionality of animating all money effects created when paused at the same time when resuming is probably not worth it.

2023-12-21 16:34 UTC, closed without merging