Paint/remove two colours
OpenRCT2/OpenRCT2 pull request #20972
Opened 2023-11-13 20:56 UTC by spacek531

The purpose of this PR was to add the additional colour to the supports colour scheme, but I identified where two ImageIds can be removed from PaintSessionCore. My understanding is that the smaller the size of PaintSessionCore, the faster the game can paint.

I get a 1fps boost when running debug

2023-11-14 20:49 UTC, spacek531 commented
marking as draft until https://github.com/OpenRCT2/OpenRCT2/pull/20969 is merged

2023-11-17 23:18 UTC, Gymnasiast commented
I did a quick test, making sure to include both the Classic Wooden and regular Wooden RC, as well as abstract station entrances. This all seems to work correctly.

I do wonder if this PR isn’t a bit too big, though. Maybe it would be better if it was instead split into a PR that just introduces the new constants for `TrackPaintScheme::Track` and `TrackPaintScheme::Supports` (lots of touched lines, but just a find-and-replace job that can be merged very quickly) and one or more PRs for the rest.

However, since I am not a team member, it’s better not to do this until one of them asks you to.

2023-11-18 06:11 UTC, spacek531 commented
For reviewability I will probably interactive rebase and put the changes to Misc and Scheme_3 into one commit and the changes to Track and Supports into the preceding commit, then the commits can be reviewed separately.

2023-11-24 03:10 UTC, spacek531 commented on src/openrct2/paint/Paint.h
> -constexpr ImageId TrackGhost = ImageId(0, FilterPaletteID::PaletteNull);
TrackGhost and TrackStationColour evaluate identically.

2023-11-24 06:33 UTC, spacek531 commented
I have removed the changes that convert the C-type enum to a namespace constexpr-type enum for reviewability. I will make those changes in a follow-up PR because it is all find-and-replace renaming.

2023-11-24 21:51 UTC, Gymnasiast commented
I took a look at the code and it looked all right to me. I will now proceed to test it.

2023-11-24 22:05 UTC, Gymnasiast requested changes
I found one bug during testing. Glass is not correctly rendering when in a ghost:

![afbeelding](https://github.com/OpenRCT2/OpenRCT2/assets/1478678/b8dab755-259b-454a-b0c2-83330af2aef6)

2023-11-27 04:38 UTC, spacek531 commented
Can you test in develop?

OpenRCT2, v0.4.6-140-g3ab33d3 (3ab33d3 on develop) provided by GitHub:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/3454156/fbd64747-cd54-4ecf-8829-25a8508cd6a7)

2023-11-27 09:52 UTC, Gymnasiast commented
I’ll check. Regardless of whether vanilla does it, though, I would personally argue it is a bug. But since `develop` has the same behaviour, it shouldn’t block this PR.

2023-11-27 21:12 UTC, Gymnasiast commented
Tested it in vanilla. It shows the glass as a ghost too.

![afbeelding](https://github.com/OpenRCT2/OpenRCT2/assets/1478678/33348c5c-6542-40ed-a0a2-43ac4959f1c3)

2023-12-21 14:23 UTC, karst commented
> marking as draft until https://github.com/OpenRCT2/OpenRCT2/pull/20969 is merged

You may always say "Depends on #20969" in your main post and the bot will add "requires dependency".

2023-12-23 13:22 UTC, tupaschoal commented
That PR was merged already, btw, so this can be resumed if you will :)

2023-12-23 15:34 UTC, tupaschoal approved these changes
I tested according to @Gymnasiast 's instructions and didn't find any change, Didn't look at the code

2023-12-23 15:42 UTC, merged