Update support drawing for shops, thrill rides and water rides
OpenRCT2/OpenRCT2 pull request #21007
Opened 2023-11-24 23:57 UTC by Gymnasiast

Another chunk that should be easy to test.

2023-11-25 23:08 UTC, karst approved these changes
Seems all to be in working order
![image](https://github.com/OpenRCT2/OpenRCT2/assets/1516893/174e30a0-2deb-4e8b-b715-b2f41706f7dc)

2023-11-28 19:13 UTC, ZehMatt requested changes
See comments

2023-11-28 19:13 UTC, ZehMatt commented on src/openrct2/ride/water/SplashBoats.cpp
> +        static constexpr std::optional<WoodenSupportSubType> supportTypes[NumOrthogonalDirections][7] = {
This is a bit of an odd one as it never asks if it holds a value or not, it's probably better to have a `None/Invalid` value for the gaps.

2023-11-28 19:13 UTC, ZehMatt commented on src/openrct2/ride/water/SplashBoats.cpp
> +        static constexpr std::optional<WoodenSupportSubType> supportTypes[][7] = {
Same as above.

2023-12-14 20:40 UTC, ZehMatt approved these changes
LGTM, thanks.

2023-12-18 10:38 UTC, merged

2023-12-18 10:38 UTC, tupaschoal commented
Argh, I squashed instead of merging, sorry!

2023-12-18 11:15 UTC, Gymnasiast commented
Ah well, shit happens. Don’t worry too much about it.