Regarding Issue #20196, climates set and saved in scenario editor wil…
OpenRCT2/OpenRCT2 pull request #21055
Opened 2023-12-05 01:16 UTC by tanzimchowdh

Climates set and saved in scenario editor will now be correct upon first loading of scenario. Previously, a double save in the scenario editor was necessary to see the climate change in effect.

2023-12-06 10:30 UTC, ZehMatt requested changes

2023-12-06 10:30 UTC, ZehMatt commented on src/openrct2/actions/ClimateSetAction.cpp
> +    //gClimate = ClimateType{ _climate };'
Delete the code if its not used

2024-01-06 16:23 UTC, Gymnasiast commented
@ SpartanFrederic104 Could you test this PR and let us know if it solves the issue?

2024-01-06 19:52 UTC, SpartanFrederic104 commented
Sure thing. Just one question: how would I test this?

2024-01-06 20:00 UTC, Gymnasiast commented
You can download a CI from this page: https://github.com/OpenRCT2/OpenRCT2/actions/runs/7431878773

2024-01-15 21:10 UTC, SpartanFrederic104 commented
Sorry for the late response due to IRL complications, but I can happily confirm this PR fixes the issue. I made four dummy scenarios, each one using one of the four default climate settings, starting from Cool and wet to Cold, then Hot and dry, and finally Warm.

![CoolWet test 2024-01-15 13-07-33](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/10b8a3ef-9178-4a39-b8e1-41da7ecd38ed)
![Cold Climate Test 2024-01-15 12-58-16](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/fee0c6c5-fca7-4d25-a745-d88715f91147)
![HotDry test 2024-01-15 13-01-35](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/603085f2-8816-487e-a712-b761b9ef74ce)
![Warm test 2024-01-15 13-05-01](https://github.com/OpenRCT2/OpenRCT2/assets/61885939/061c801b-a1e7-48ba-9b1f-63638c5ee45d)

With this PR, Cool and wet still starts at 55℉ (13℃), but Warm and Hot and dry now start at 62℉ (17℃), and Cold now starts at 48℉ (9℃).

2024-01-16 00:46 UTC, tupaschoal reviewed
I haven't tested, but code-wise it seems to make a lot of sense since, among other things, `gClimate` would only be read from on calling `ClearMapForEditing` on the Editor file.

Can you add a changelog entry please @tanzimchowdh ? Also thanks @SpartanFrederic104 for testing and the thorough reporting :)

2024-01-22 18:59 UTC, Gymnasiast approved these changes

2024-01-22 19:16 UTC, tupaschoal approved these changes

2024-01-22 19:18 UTC, merged