Fix #2109
OpenRCT2/OpenRCT2 pull request #21325
Opened 2024-02-04 00:29 UTC by Opi-Txm

Should fix [#21039 ](https://github.com/OpenRCT2/OpenRCT2/issues/21039).

As it is explained in the issue, the outline and inset code would not respect the DPI bounds in the drawing process by accessing e.g. `*(dst + 1)` to draw an outline, in this case to the right.
#### Approach
I approached this issue by creating a function `GetPixel()`  in `TTFSurface` that would return a value if the given x and y coordinates is a part of a TTF text, else 0. 

In the for loop, iterating through the TTF text, the if condition
```
if (surface->GetPixel(xx + srcX_start + 1, yy + srcY_start)
                        || surface->GetPixel(xx + srcX_start - 1, yy + srcY_start)
                        || surface->GetPixel(xx + srcX_start, yy + srcY_start + 1)
                        || surface->GetPixel(xx + srcX_start, yy + srcY_start - 1))
```
checks if the coordinates **(xx, yy)** is an outline of a text. the writing bounds. Adding `srcX_start`, which is 0 or `-skipX` if `skipX < 0`, when calling `GetPixel()`, would shift the pixel access to the correct position, where the text begins on the surface. The same is done for the Y axis. (Not having this would lead to the outlines/insets not moving with the text when the window with the TTF text moves)

2024-02-04 00:56 UTC, mrmbernardi requested changes

2024-02-04 00:56 UTC, mrmbernardi commented on src/openrct2/drawing/Drawing.String.cpp
>      const uint8_t* src_orig = src;
These two pointers don't need to exist anymore

2024-02-04 01:03 UTC, mrmbernardi commented on src/openrct2/drawing/Drawing.String.cpp
>      const uint8_t* src_orig = src;
`src_orig` is no longer needed

2024-02-04 07:36 UTC, Opi-Txm commented on src/openrct2/drawing/Drawing.String.cpp
>      const uint8_t* src_orig = src;
makes sense! updated it

2024-02-17 16:57 UTC, ZehMatt commented
The code seems fine, however I also feel like this is a bit in-efficient to do it this way, the more reasonable approach would be to typically clamp the values which minimizes the iterations and avoids the bounds check each iteration, I didn't look at the entire function so maybe you can elaborate a bit on your thought process on this?

2024-02-17 18:18 UTC, Opi-Txm commented
Well, what the new method does is, it checks if the coordinates (xx, yy) is an outline of a text, checking the top/bottom/left/right side of the pixel (xx, yy) by incrementing/decrementing the coordinates by 1, as explained in the PR.

If you would clamp the coordinates to avoid having the coordinates of GetPixel() be of bounds, you would also need to have to care for the edges of each offset as well and would complicate the code. 
E.g. a text-pixel at the right edge of a dpi won't be able to draw it's right outline and it would never get drawn, as it is in a different dpi.

2024-02-17 19:33 UTC, ZehMatt commented
> Well, what the new method does is, it checks if the coordinates (xx, yy) is an outline of a text, checking the top/bottom/left/right side of the pixel (xx, yy) by incrementing/decrementing the coordinates by 1, as explained in the PR.
> 
> If you would clamp the coordinates to avoid having the coordinates of GetPixel() be of bounds, you would also need to have to care for the edges of each offset as well and would complicate the code. E.g. a text-pixel at the right edge of a dpi won't be able to draw it's right outline and it would never get drawn, as it is in a different dpi.

I see, well as I said I didn't look at the function too close and I guess this will do, I was just wondering to how you got to this solution.

2024-02-17 19:35 UTC, ZehMatt approved these changes
Seems fine, this however needs some proper testing before it gets merged.

2024-02-17 22:30 UTC, Gymnasiast approved these changes
Tested it with both software rendering and OpenGL, using Dutch, Arabic, Japanese and Korean.

2024-02-17 22:31 UTC, merged