Part of #21421: replace define with constexpr
OpenRCT2/OpenRCT2 pull request #21760
Opened 2024-04-09 13:09 UTC by janclod

Part of #21421 

Different refactor (mostly few lines of code per replaced `define`), some unused `#define` deleted, one define (`ADD_CLAMP_BODY`) replaced with a template function.

~I realize that this PR may be too big to review at once, please let me know if I should split it.~
Since this PR is a duplicate of #21705 and it incorporates all the feedback given there, I am leaving as is.

2024-04-09 13:49 UTC, ZehMatt commented
Please don't close PRs if you start over, instead force push.

2024-04-09 15:43 UTC, janclod commented
> Please don't close PRs if you start over, instead force push.

That was my initial idea, but I failed :pensive: after a rebase, I did delete the upstream branch, this automatically closed the PR and I could not reopen. What is a good workflow, rebase and then force push? I am not familiar with force-push, can I do this after a rebase?

2024-04-09 15:59 UTC, ZehMatt commented
> > Please don't close PRs if you start over, instead force push.
> 
> That was my initial idea, but I failed 😔 after a rebase, I did delete the upstream branch, this automatically closed the PR and I could not reopen. What is a good workflow, rebase and then force push? I am not familiar with force-push, can I do this after a rebase?

Force push just means it will overwrite the branch forcefully which means also its rewriting its history. You can always reset a branch to its base by using `git reset --hard upstream/develop` and then force push, then you can start adding commits again.

2024-04-09 19:14 UTC, Broxzier commented
Push only after you've already made a new commit, because otherwise your branch will be the same as develop (or even behind) and GitHub will automatically close the PR.

2024-04-11 18:49 UTC, janclod commented
Yeeey :D this time I forced pushed... Thanks for teaching me!

2024-04-29 16:12 UTC, ZehMatt commented on src/openrct2/util/Util.cpp
> +template<typename T> constexpr T kAddClampBody(T value, T value_to_add, T min_cap, T max_cap)
I think it definitely beats the macro use. Also you are correct, we can obtain the limits with numeric_limits<T>, no need to pass them as arguments.

2024-04-29 19:52 UTC, janclod commented on src/openrct2/util/Util.cpp
> +template<typename T> constexpr T kAddClampBody(T value, T value_to_add, T min_cap, T max_cap)
Happy to see the template approach appreciated :) I will improve based on feedback, until the next push ;)

2024-04-30 11:58 UTC, tupaschoal approved these changes
This LGTM. Should definitely be squash merged due to the confusion on some merges.

Might require a few rebases still due to network version changing (for #21850 and maybe more by the time you see it)

2024-04-30 14:01 UTC, ZehMatt requested changes
Left a few remarks, we don't do snake_case, the rest seems fine to me.

2024-04-30 14:01 UTC, ZehMatt commented on src/openrct2/util/Util.cpp
> +    auto max_cap = std::numeric_limits<T>::max();
```suggestion
    auto maxCap = std::numeric_limits<T>::max();
```

2024-04-30 14:01 UTC, ZehMatt commented on src/openrct2/util/Util.cpp
> +    auto min_cap = std::numeric_limits<T>::lowest();
```suggestion
    auto minCap = std::numeric_limits<T>::lowest();
```

2024-04-30 14:01 UTC, ZehMatt commented on src/openrct2/util/Util.cpp
> +template<typename T> constexpr T kAddClampBody(T value, T value_to_add)
```suggestion
template<typename T> constexpr T kAddClampBody(T value, T valueToAdd)
```

2024-05-06 14:41 UTC, janclod commented
@ZehMatt thanks for catching the camel cases, incorporated suggestions.

Also improved further the template function `AddClamp` in `Util.h`, please have a last look, do not expect big surprises.

@tupaschoal also rebased on `develop` to with correct network versioning.

2024-05-06 14:49 UTC, janclod reviewed
Incorporated changes.

2024-05-09 01:10 UTC, tupaschoal approved these changes

2024-05-09 01:11 UTC, tupaschoal commented
@Gymnasiast or @ZehMatt this looks ready to go (before another merge conflict)

2024-05-09 11:53 UTC, ZehMatt approved these changes
LGTM, Thanks.

2024-05-09 11:59 UTC, merged