Fix #2287: Sound not disabled when starting without focus
OpenRCT2/OpenRCT2 pull request #21777
Opened 2024-04-13 06:14 UTC by Daniel-Lightbourn

For #2287
Defer calling `PlayTitleMusic()` the first time when OpenRCT2 starts until after SDL events have been polled. This allows the code to process focus events to mute the audio before the title music starts playing.

This slightly changes the current behavior in that the music no longer starts right when the window is created but about when the game starts rendering (about 1 second later on my machine).

2024-04-14 21:20 UTC, ZehMatt requested changes
This unfortunately a bad approach to go about this issue, this would also only work if people have the Uncap FPS disabled, this is also not the proper place to have logic like this.

2024-04-14 22:44 UTC, Daniel-Lightbourn commented
I had not noticed there were two `Run*Frame` functions; I can hoist the check up to cover them, but you seem to not like how I did this.

I can do something more complicated like having a `Context::PostFirstFrame` function that unpauses the SDL audio device and change `AudioMixer::Init` to not unpause it. I'd change the do while loop in `Context::RunGameLoop` to something like:
```c++
RunFrame();
PostFirstFrame();
while(!_finished) {
    RunFrame();
}
```

2024-04-23 00:02 UTC, Daniel-Lightbourn commented
@ZehMatt?

2024-04-23 19:42 UTC, ZehMatt commented
I don't like that idea, the music should start playing post-load of a save file, we can probably just add a check for which screen flags are set after a save is loaded and call `PlayTitleMusic()`, we have quite a lot of code scattered regarding load/save so its best to delay this until we cleaned that up. Perhaps there is a suitable spot for such new code but adding more complexity at the moment is unfortunately out of the question, sorry.

2024-04-24 00:30 UTC, Daniel-Lightbourn commented
@ZehMatt What about moving the `PlayTitleMusic()` inside of `TitleScreen::Tick()`? I experimented with having it get called after loading a park in a sequence, but unfortunately, that still happens ever so slightly too early; if the main thread were to stall, a couple audio samples could go through before OpenRCT2 realizes it's not in focus.

If you find this acceptably, I'll squash and fix up the commit message.

2024-05-18 10:27 UTC, AaronVanGeffen commented
Sorry, it shouldn't go in the tick logic either. I appreciate that you're trying to solve an issue, but as @ZehMatt said, it would be better to refactor the loading code instead of hacking in a fix.

Considering the approach, and the emerged merge conflict, I think it's best to close this.

2024-05-18 10:27 UTC, closed without merging