Fix #21837: Formatter being overwritten - RideConstruction.cpp
OpenRCT2/OpenRCT2 pull request #21841
Opened 2024-04-19 10:01 UTC by Harry-Hopkinson

Fix https://github.com/OpenRCT2/OpenRCT2/issues/21837 - remove unnecessary lines as the value in the Formatter is overwritten.

2024-04-19 10:05 UTC, janisozaur approved these changes

2024-04-19 10:40 UTC, Gymnasiast requested changes
This is probably not going to work and break the display of that window. It uses the common formatter, which means that overwriting it will not erase the data, it will only reset the internal counter.

2024-04-19 15:46 UTC, Gymnasiast commented on src/openrct2-ui/windows/RideConstruction.cpp
> -            ft = Formatter::Common();
Again, have you tested this?

2024-04-19 16:02 UTC, Harry-Hopkinson commented
After further investigation - it removes the name of the ride at the top of the RideConstructionWindow.

2024-04-19 17:44 UTC, Harry-Hopkinson commented
@Gymnasiast After testing - using ```ft.Rewind()``` does work. Thanks and sorry that I did not pick up the change removing the ride title when I was testing.

2024-04-19 17:57 UTC, Gymnasiast approved these changes

2024-04-19 21:04 UTC, Gymnasiast requested changes
I’d like to check a thing - I think there is a more elegant solution here.

2024-04-20 13:40 UTC, Gymnasiast approved these changes

2024-04-20 13:49 UTC, merged