Fix #21696: Mac not remembering fullscreen window option
OpenRCT2/OpenRCT2 pull request #21873
Opened 2024-04-21 23:33 UTC by ayvaak

Removes a previously implemented workaround that was forcing Mac to open the program in windowed mode. This was implemented to keep a cursor issue from happening, but this cursor issue no longer occurs.

2024-04-22 08:17 UTC, AaronVanGeffen commented
Both comments can be removed if the issue has been resolved, imo. 

Could you add a changelog entry?

2024-04-22 15:44 UTC, Harry-Hopkinson commented
I have tested this and everything works as expected.

2024-04-23 18:18 UTC, Gymnasiast requested changes
Please address @AaronVanGeffen ’s requests. The PR otherwise looks good to me.

2024-04-23 20:49 UTC, Gymnasiast commented
You still need to amend the changelog:
```
Fix: [#21696] Fullscreen window option not correctly applied on macOS.
```

2024-04-23 20:57 UTC, ayvaak commented
Added the line! Apologies, this is my first contribution so I hadn't known about that part.

2024-04-23 21:19 UTC, Gymnasiast approved these changes

2024-04-23 21:20 UTC, merged