Working on issue #21421 on file Window.h
OpenRCT2/OpenRCT2 pull request #21906
Opened 2024-04-26 20:45 UTC by katerid

Replacing SCROLLABLE_ROW_HEIGHT with constexpr and kScrollableRowHeight

2024-04-26 23:17 UTC, katerid commented
I believe that this should be ready for review, the only issue is that one of my commits had too short of a name.

2024-04-27 12:25 UTC, Gymnasiast requested changes
There are a number of changes in this PR that shouldn’t be there, like one deleted file, two instances where the trailing newline was removed, and one case of an extra newline. Please fix these. The actual meat of the PR does look good, though.

2024-04-27 12:25 UTC, Gymnasiast commented on src/openrct2/network/NetworkBase.cpp
> +
Unrelated change, please revert.

2024-04-27 12:25 UTC, Gymnasiast commented on src/openrct2/command_line/RootCommands.cpp
> +}
Unrelated change, please revert.

2024-04-27 12:25 UTC, Gymnasiast commented on src/openrct2/Version.h
> +NewVersionInfo GetLatestVersion();
Unrelated change, please revert.

2024-04-27 12:25 UTC, Gymnasiast commented on .vscode/c_cpp_properties.json
> -{
Unrelated change, please revert.

2024-04-28 20:15 UTC, katerid commented
> There are a number of changes in this PR that shouldn’t be there, like one deleted file, two instances where the trailing newline was removed, and one case of an extra newline. Please fix these. The actual meat of the PR does look good, though.
> 
> Also, please do not close PRs only to recreate them - just update your existing one.

Sorry about the closed PR, I was just changing which file I was working on and I'm still newer to github. I didn't know how to take out some of my old commits and only include the new ones that were relevant to this PR which was my goal with creating a new one.

2024-04-28 20:56 UTC, Gymnasiast commented
No worries, we have all had to learn it.

Removing unwanted commits can be done using a rebase. It is an advanced operation though.

A tip for future PRs: make you make your changes on a branch, rather than the `master` branch. This keeps things cleaner and avoids unrelated commits stacking up.

2024-05-09 13:43 UTC, Gymnasiast commented
@katerid Could you address the line notes?

2024-05-18 10:08 UTC, AaronVanGeffen commented
I intended to rebase this PR, but it looks like the `SCROLLABLE_ROW_HEIGHT` define has already been replaced with a constexpr `kScrollableRowHeight` in #21760. Therefore closing this PR.

2024-05-18 10:08 UTC, closed without merging