Move UI exclusive string ids to UiStringIds.h
OpenRCT2/OpenRCT2 pull request #22016
Opened 2024-05-10 22:33 UTC by AaronVanGeffen

This moves string ids that are only used in UI context to a new file, UiStringIds.h.

2024-05-12 20:20 UTC, Gymnasiast commented on src/openrct2-ui/scripting/CustomWindow.cpp
> +                        gDropdownItems[i].Format = STR_OPTIONS_DROPDOWN_ITEM;
This seems unrelated.

2024-05-12 20:20 UTC, Gymnasiast commented on src/openrct2-ui/windows/Park.cpp
> +            StringId stringId = STR_BOTTOM_TOOLBAR_CASH;
also unrelated

2024-05-12 20:21 UTC, Gymnasiast requested changes
Would like to see the unrelated changes taken out.

2024-05-12 20:27 UTC, AaronVanGeffen commented
> Would like to see the unrelated changes taken out.

These changes are the result of `-Wdeprecated-anon-enum-enum-conversion` triggering, being the result of there now being two enums. The changes dealing with this are all contained in the second commit, fwiw.

2024-05-17 19:32 UTC, Gymnasiast commented
> > Would like to see the unrelated changes taken out.
> 
> These changes are the result of `-Wdeprecated-anon-enum-enum-conversion` triggering, being the result of there now being two enums. The changes dealing with this are all contained in the second commit, fwiw.

Maybe they shouldn’t be in an enum at all, but be declared as regular constants. But that might be a step too far for this PR?

2024-05-17 19:42 UTC, AaronVanGeffen commented
> Maybe they shouldn’t be in an enum at all, but be declared as regular constants. But that might be a step too far for this PR?

It's worth exploring alternatives, such as making them namespaced instead (e.g. `OpenRCT2::StringIds::not_enough_funds`). But yeah, that's something for another PR, I agree. 

Thankfully, there are only 11 ternaries affected in the entire codebase, so it is easy enough to address the `-Wdeprecated-anon-enum-enum-conversion warnings` that have surfaced.

2024-05-17 21:26 UTC, Gymnasiast approved these changes
Not really a fan of some of the changes, but I’m not dying on Ternary Hill tonight.

2024-05-17 22:04 UTC, merged