Use kDefaultGeneralSupportHeight throughout
OpenRCT2/OpenRCT2 pull request #22036
Opened 2024-05-14 16:39 UTC by Gymnasiast

Split off from #22035

2024-05-14 16:59 UTC, spacek531 commented on src/openrct2/ride/coaster/InvertedRollerCoaster.cpp
> +#include "../../paint/track/Support.h"
This file doesn't seem to use the new constant.

2024-05-14 17:16 UTC, spacek531 commented on src/openrct2/ride/coaster/SuspendedSwingingCoaster.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:16 UTC, spacek531 commented on src/openrct2/ride/coaster/WoodenRollerCoaster.h
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:17 UTC, AaronVanGeffen reviewed
The `Support.h` include seems to have been added to quite a few files that don't appear to use it, e.g. the gentle rides. That should probably be corrected.

2024-05-14 17:17 UTC, spacek531 commented on src/openrct2/ride/gentle/Circus.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:18 UTC, spacek531 commented on src/openrct2/ride/gentle/CrookedHouse.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:18 UTC, spacek531 commented on src/openrct2/ride/gentle/Dodgems.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:18 UTC, spacek531 commented on src/openrct2/ride/gentle/FerrisWheel.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:19 UTC, spacek531 commented on src/openrct2/ride/gentle/FlyingSaucers.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:19 UTC, spacek531 commented on src/openrct2/ride/gentle/HauntedHouse.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:20 UTC, spacek531 commented on src/openrct2/ride/gentle/MerryGoRound.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:20 UTC, spacek531 commented on src/openrct2/ride/gentle/SpaceRings.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:21 UTC, spacek531 commented on src/openrct2/ride/gentle/SpiralSlide.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:22 UTC, spacek531 commented on src/openrct2/ride/thrill/3dCinema.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:22 UTC, spacek531 commented on src/openrct2/ride/thrill/Enterprise.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:23 UTC, spacek531 commented on src/openrct2/ride/thrill/MagicCarpet.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:23 UTC, spacek531 commented on src/openrct2/ride/thrill/MotionSimulator.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:24 UTC, spacek531 commented on src/openrct2/ride/thrill/SwingingInverterShip.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:24 UTC, spacek531 commented on src/openrct2/ride/thrill/SwingingShip.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:25 UTC, spacek531 commented on src/openrct2/ride/thrill/TopSpin.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:25 UTC, spacek531 commented on src/openrct2/ride/thrill/Twist.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:26 UTC, spacek531 commented on src/openrct2/ride/transport/SuspendedMonorail.cpp
> +#include "../../paint/track/Support.h"
Default support height not used in this file

2024-05-14 17:27 UTC, spacek531 requested changes
Everything looks good. A few files received the include which don't need it. When the extra includes are removed, this is good 👍

2024-05-15 19:24 UTC, AaronVanGeffen approved these changes

2024-05-15 19:25 UTC, merged