[Plugin API] feat: expose monthly expenditure history
OpenRCT2/OpenRCT2 pull request #22150
Opened 2024-06-05 03:58 UTC by mrmagic2020

Expose monthly expenditure history to the plugin API.

<details>
<summary> Click here for test plugin </summary>

```js
registerPlugin({
  name: "Expenditure Table Test",
  authors: ["mrmagic2020"],
  version: "0.0.1",
  licence: "MIT",
  type: "local",
  minApiVersion: 93,
  main: function () {
    var selectedMonth = 0;
    var selectedType = 0;
    const expTypes = [
      "ride_construction",
      "ride_runningcosts",
      "land_purchase",
      "landscaping",
      "park_entrance_tickets",
      "park_ride_tickets",
      "shop_sales",
      "shop_stock",
      "food_drink_sales",
      "food_drink_stock",
      "wages",
      "marketing",
      "research",
      "interest"
    ];

    var result = 0;
    var str = "";

    ui.registerMenuItem("Expenditure Table Test", function () {
      var wdw = ui.openWindow({
        classification: "expenditure_table_test",
        title: "Expenditure Table Test",
        width: 360,
        height: 80,
        widgets: [
          {
            type: "spinner",
            name: "spinner-choose-month",
            x: 5,
            y: 20,
            width: 100,
            height: 14,
            text: selectedMonth + " months ago",
            onDecrement: function () {
              selectedMonth--;
              if (selectedMonth < 0) {
                selectedMonth = 0;
              }
            },
            onIncrement: function () {
              selectedMonth++;
              if (selectedMonth > 15) {
                selectedMonth = 15;
              }
            }
          },
          {
            type: "dropdown",
            name: "dropdown-choose-type",
            x: 110,
            y: 20,
            width: 120,
            height: 14,
            items: expTypes,
            onChange: function (idx) {
              selectedType = idx;
            }
          },
          {
            type: "button",
            name: "button-fetch",
            x: 235,
            y: 20,
            width: 50,
            height: 14,
            text: "Fetch",
            onClick: function () {
              result = park.getMonthlyExpenditure(expTypes[selectedType])[
                selectedMonth
              ];
              str =
                "Expenditure for " +
                expTypes[selectedType] +
                " is $" +
                result / 10 +
                " (" +
                selectedMonth +
                " months ago).";
              console.log(str);
            }
          },
          {
            type: "label",
            name: "label-result",
            x: 5,
            y: 40,
            width: 350,
            height: 14,
            text: str
          }
        ],
        onUpdate: function () {
          wdw.findWidget("spinner-choose-month").text =
            selectedMonth + " months ago";
          wdw.findWidget("dropdown-choose-type").selectedIndex = selectedType;
          wdw.findWidget("label-result").text = str;
        }
      });
      wdw.open();
    });
  }
});
```

</details>

2024-06-05 04:01 UTC, mrmagic2020 commented on src/openrct2/scripting/ScriptEngine.h
> +        static std::string_view ExpenditureTypeToString(ExpenditureType expenditureType);
I moved these two functions to public scope for access in `ScPark.cpp`.

2024-06-14 20:38 UTC, janisozaur requested changes

2024-06-14 20:38 UTC, janisozaur commented on src/openrct2/scripting/bindings/world/ScPark.cpp
> +        std::vector<int32_t> result(kExpenditureTableMonthCount, 0);
Documentation suggests this vector will be up to 16 entries long, but here you always create is 16-long and only fill in partially, suggesting some months may have passed with no expenditures. Please align both. I'd prefer to return properly sized vector here.

2024-06-16 14:35 UTC, janisozaur approved these changes

2024-06-22 19:20 UTC, Basssiiie approved these changes
Tested it and found no issues. API looks good as well. Nice work! 🙂

2024-06-23 20:49 UTC, merged