Refactor SPR_NONE
OpenRCT2/OpenRCT2 pull request #22517
Opened 2024-08-09 12:30 UTC by scaryghosty

2024-08-09 12:32 UTC, scaryghosty commented
Not ready yet.

2024-08-09 13:23 UTC, AaronVanGeffen commented on src/openrct2-ui/interface/Widget.cpp
> +        if (static_cast<int32_t>(widget.image.ToUInt32()) == kSpriteIdNull)
The cast should be removed, i.e.:
```suggestion
        if (widget.image.ToUInt32() == kSpriteIdNull)
```
Similar in other such cases. Look at compiler output ('checks' on GitHub) for all similar cases.

2024-08-09 13:23 UTC, AaronVanGeffen commented on src/openrct2-ui/windows/EditorParkEntrance.cpp
> +        ImageIndex imageId = static_cast<ImageIndex>(kSpriteIdNull);
Cast is no longer needed, as `kSpriteIdNull` is already of the correct type.

2024-08-09 13:24 UTC, AaronVanGeffen commented on src/openrct2/drawing/ImageIndexType.h
> +constexpr ImageIndex kSpriteIdNull = -1; // 0x7FFFF
ImageIndex is `uint32_t`, so it can't be -1. Instead, use `std::limits<ImageIndex>::max()`. Don't forget to add `#include <limits>`.

2024-08-09 13:24 UTC, AaronVanGeffen commented on src/openrct2/sprites.h
>  enum
```suggestion
enum : ImageIndex
```

2024-08-09 13:26 UTC, AaronVanGeffen requested changes
As you said, this definitely needs more work still. Are you able to compile this locally yet? A lot of the errors would be pointed out by a compiler, and a good IDE might even be able to suggest fixes.

2024-08-09 13:29 UTC, scaryghosty commented
> As you said, this definitely needs more work still. Are you able to compile this locally yet? A lot of the errors would be pointed out by a compiler, and a good IDE might even be able to suggest fixes.

all the things you mentioned above I know I have to do, I just wanted to go to bed and now I'm working lol... can tackle more tonight when i'm home. removing casts and changing the value from -1 to something else was my next course of action, then looking at the final item in the issue :)

2024-08-09 23:33 UTC, scaryghosty commented
couple of places now where it doesnt like the comparison between an int and 'unnamed enum' (which is now type ImageIndex, or uint32_t).

- Drawing.Sprite.cpp
- Font.cpp
- ScrollingText.cpp

for Drawing.Sprite.cpp and Font.cpp, i _think_ the fix is as easy as changing the counter (**i** or **glyphIndex**, respectively) to uint32_t type? for ScrollingText.cpp i'm not sure

2024-08-10 08:54 UTC, AaronVanGeffen commented
> for Drawing.Sprite.cpp and Font.cpp, i _think_ the fix is as easy as changing the counter (**i** or **glyphIndex**, respectively) to uint32_t type? for ScrollingText.cpp i'm not sure

Yes, changing the type for the loop counter will suffice. You could also change it to `auto i = 0u` to declare it unsigned, while leaving the type inferred.

2024-08-10 16:54 UTC, scaryghosty commented
tests are still running while i write this but i think the build is good now? also sorry, my local dev environment leaves a lot to be desired if you couldn't tell, so i will rectify that before tackling any more tickets

2024-08-10 20:52 UTC, AaronVanGeffen commented
The changeset as-is looks good to me. I'm wondering, though, if there's any files including `sprites.h` while they could make do with the new `ImageIndexType.h` file. That would be preferable, of course. I'll do some quick checks on my end.

2024-08-10 21:06 UTC, AaronVanGeffen approved these changes
Quick inspection revealed we can remove the `sprites.h` include from `LandTool.h` and `RideData.h`, which should lead to less recompilations whenever `sprites.h` is changed. Instead, we'll need to manually include the header in a couple more window unit files, but that's fine.

Rebased on top of current develop. LGTM.

2024-08-11 08:53 UTC, Gymnasiast commented on src/openrct2/drawing/ImageIndexType.h
> +constexpr ImageIndex kSpriteIdNull = std::numeric_limits<ImageIndex>::max();
Files should end with a newline.

```suggestion
constexpr ImageIndex kSpriteIdNull = std::numeric_limits<ImageIndex>::max();

```

2024-08-11 09:38 UTC, Gymnasiast approved these changes

2024-08-11 09:58 UTC, merged