Prototype for ctrl/shift modifiers in footpath tool
OpenRCT2/OpenRCT2 pull request #22569
Opened 2024-08-14 18:55 UTC by AaronVanGeffen

2024-08-14 19:06 UTC, fidwell commented
Very cool! One thing I noticed is that in your video, you're placing paths at invalid heights. Is the cheat on? If not, that'll need to be addressed, assuming it isn't already on your list.

2024-08-14 19:14 UTC, AaronVanGeffen commented
> Very cool! One thing I noticed is that in your video, you're placing paths at invalid heights. Is the cheat on? If not, that'll need to be addressed, assuming it isn't already on your list.

You're right, it currently allows placing at invalid heights, owing to basing the height code on that of the ride and scenery windows, which do allow building at those heights.

I'd like to clean up the code and integrate the existing code paths more into the one introduced in this PR, such that only full heights are allowed again.

Another problem with the current implementation is that the 'modifier' baseZ is used even if the modifier key isn't being held, haha.

2024-08-18 19:18 UTC, AaronVanGeffen commented on src/openrct2-ui/windows/Footpath.cpp
> +            // TODO: integrate code path below
Outdated comment; can be removed.

2024-08-20 23:33 UTC, karst requested changes
It feels great! 
Issues I have found:
- The Ctrl option doesn't snap to scenery. Scenery does snap to the height of paths and this is an inconsistency.
- There's a bug happening when you have a path in the foreground on a higher level, it will bring the path in the background to that level, on the background tile, without holding shift or ctrl. 
![image](https://github.com/user-attachments/assets/c8d01caa-0278-4f33-9003-604814a08bae)
- The level grid you get when holding shift is offset by a unit, when the "construct bridge or tunnel footpath" is set to upwards.
- Tooltip for this mode is called "Construct footpath on land" should probably be changed to something like "Draw footpath". And the other one should be renamed too for consistency sake.

2024-08-21 13:23 UTC, AaronVanGeffen commented
Thanks for testing, @karst!

> The Ctrl option doesn't snap to scenery. Scenery does snap to the height of paths and this is an inconsistency.

This should now be fixed. I was using the interaction flags used by the ride construction window, but I have switched to the ones from the scenery window.

> There's a bug happening when you have a path in the foreground on a higher level, it will bring the path in the background to that level, on the background tile, without holding shift or ctrl.

Not sure why this is happening yet. Will investigate.

> The level grid you get when holding shift is offset by a unit, when the "construct bridge or tunnel footpath" is set to upwards.

I'm not sure why that is the case, but the virtual floor code is also not touched by this PR. If you believe this is a bug, could you file an issue for it?

> Tooltip for this mode is called "Construct footpath on land" should probably be changed to something like "Draw footpath". And the other one should be renamed too for consistency sake.

Personally, I'd like to leave the tooltips as-is. The new behaviour is additive for advanced players. Both modes still work as they used to without the modifier keys. I'd rather avoid confusing new players.

2024-08-21 13:39 UTC, karst commented
> I'm not sure why that is the case, but the virtual floor code is also not touched by this PR. If you believe this is a bug, could you file an issue for it?

Ah yes, this seems to be present in develop, too.

2024-08-21 14:17 UTC, AaronVanGeffen commented
> There's a bug happening when you have a path in the foreground on a higher level, it will bring the path in the background to that level, on the background tile, without holding shift or ctrl.

This should be fixed as of the latest commit.

2024-08-21 14:21 UTC, AaronVanGeffen commented on src/openrct2-ui/windows/RideConstruction.cpp
> +                // TODO: use ViewportInteractionItem flags?
#22607

2024-08-22 14:58 UTC, karst approved these changes
All previously mentioned issues (except for the bug in develop) have been tackled. All seems to work correctly. Nice work!

2024-08-22 20:15 UTC, duncanspumpkin approved these changes
Code looks sensible. Trusting @karst  on the playability.

2024-08-22 20:15 UTC, merged