Change: #22494 Reorder themes window
OpenRCT2/OpenRCT2 pull request #22588
Opened 2024-08-18 17:12 UTC by lewyche

![image](https://github.com/user-attachments/assets/99e60fa9-a699-49d9-96d2-7f0d713600f9)
![image](https://github.com/user-attachments/assets/acd00d92-c03d-4709-a24b-12ca9f139b3c)

Address: #22494

2024-08-18 17:50 UTC, AaronVanGeffen commented
Nice work. Going by the screenshots, I see labels from the first column can bleed into the second column, though. I think this should be mitigated by replacing `DrawTextBasic` with `DrawTextEllipsised`.

To prevent label cutoff, I think we should consider increasing the window dimensions slightly. Alternatively, the 'Palette' column could be shrunk a little, but I think that will look unbalanced with the 'Transparency' column.

2024-08-19 13:06 UTC, Gymnasiast commented
I think it might be better to just employ the "wrapped" text drawing function. Especially as other languages tend to result in longer strings.

2024-08-19 13:50 UTC, AaronVanGeffen commented
> I think it is better to just employ the "wrapped" text drawing function. Especially as other languages tend to result in longer strings.

That would work for entries with more than one colour 'row', but would likely complicate things for single-row entries, like in the second screenshot 🤔

2024-08-19 21:07 UTC, Gymnasiast commented
Would it, really? Isn’t it just a matter of saving the highest `y` coordinate?

2024-08-19 21:12 UTC, AaronVanGeffen commented
You're right that it won't be a problem for drawing. It does complicate mouse events, though, as row heights would suddenly be affected by the label height. Similarly, getting the height of the scrollview would no longer be trivial.

2024-08-19 21:17 UTC, lewyche commented
I've already delt with problems such as the mouse events and the height of the scroll view when I made the rows adapt to the number of colours, but making the text wrap and having an empty row might not look the prettiest.

2024-08-19 21:22 UTC, Gymnasiast commented
I cannot accept lots of cut off titles in other languages, sorry. This game is not just made for people who play in English.

2024-08-19 21:36 UTC, AaronVanGeffen commented
That is why I suggested the following before:

> To prevent label cutoff, I think we should consider increasing the window dimensions slightly. Alternatively, the 'Palette' column could be shrunk a little, but I think that will look unbalanced with the 'Transparency' column.

2024-08-20 21:50 UTC, lewyche commented
I think extending the window so that it can fit most languages comfortably, and wrapping the text for languages with longer strings is a good comprise.

2024-08-23 21:45 UTC, Gymnasiast commented
Ok, that would work for me.

2024-08-29 00:49 UTC, lewyche commented
Testing in Russian:
<img width="238" alt="wrap2" src="https://github.com/user-attachments/assets/e6677708-946f-48dc-949a-bfab97cfbbb5">
<img width="239" alt="wrap1" src="https://github.com/user-attachments/assets/f5f79246-62ba-413e-8375-7852175566c0">
I didn't end up increasing the window dimensions, since in most languages we don't need to make an empty row anyways.

2024-08-30 06:16 UTC, Gymnasiast requested changes
Looking through the code, I found a few things. Make sure to pay special attention to the line notes that apply to multiple places.

2024-08-30 06:16 UTC, Gymnasiast commented on data/language/en-GB.txt
> +STR_6671    :Transparency
```suggestion
STR_6671    :Transparent
```

2024-08-30 06:16 UTC, Gymnasiast commented on src/openrct2-ui/windows/Themes.cpp
> +                // add colour to account for text wrapping
```suggestion
                // If the window description wraps, make sure the row is high enough.
```

2024-08-30 06:16 UTC, Gymnasiast commented on src/openrct2-ui/windows/Themes.cpp
> +                bool empty_row = false;
Change this to camelCase: `emptyRow`. This apply to any variable you specify.

2024-08-30 06:16 UTC, Gymnasiast commented on src/openrct2-ui/windows/Themes.cpp
> +                // add colour to account for text wrapping
Also, I see this pattern multiple times in you changes. To me, it seems you could extract that out into a (static) function.

2024-08-30 06:16 UTC, Gymnasiast commented on src/openrct2-ui/windows/Themes.cpp
> +            int8_t total = 0;
This seems to count the number of rows (occupied or not). In that case, `numRows` seems like a more appropriate name. This comment also applies to other cases where you count the number of rows.

2024-09-07 10:27 UTC, Gymnasiast commented
@lewyche Did you address all the points? If so, please say so and I’ll re-review.

2024-09-08 03:33 UTC, lewyche commented
The PR should be ready to review now.

2024-09-11 07:46 UTC, AaronVanGeffen commented on src/openrct2-ui/windows/Themes.cpp
> +    const uint16_t _window_header_size = 152;
```suggestion
    const uint16_t kWindowHeaderWidth = 152;
```

2024-09-11 07:50 UTC, AaronVanGeffen commented
The colour dropdowns are offset a bit strangely:
![Screenshot 2024-09-11 at 09 49 03](https://github.com/user-attachments/assets/68e2780d-eb63-4dc9-885d-79ccd3f875fe)

Normally, we show dropdowns directly underneath the widget that called them, i.e. horizontally aligned. If you don't want to obstruct the elements underneath, I suggest we align them vertically with the start of the caller element.

2024-09-11 18:36 UTC, lewyche commented
The dropdowns are now vertically aligned with the button, and changed _window_header_size to kWindowHeaderWidth
<img width="131" alt="image" src="https://github.com/user-attachments/assets/535a35af-159c-4a6a-8d1b-e134e04a8efd">

2024-09-13 14:50 UTC, lewyche commented on src/openrct2-ui/windows/Themes.cpp
> +        MakeWidget({236, 46}, { 80,  15}, WindowWidgetType::TableHeader, WindowColour::Secondary, STR_THEMES_HEADER_TRANSPARENCY                                                          ), // Transpa
Would this be better?
![image](https://github.com/user-attachments/assets/c2428231-ece8-4bf3-972a-14ba4838bf6b)

2024-09-14 01:11 UTC, tupaschoal commented on src/openrct2-ui/windows/Themes.cpp
> +        MakeWidget({236, 46}, { 80,  15}, WindowWidgetType::TableHeader, WindowColour::Secondary, STR_THEMES_HEADER_TRANSPARENCY                                                          ), // Transpa
We typically let the line become long, but make sure the commas of all subsequent entries are aligned. That's real nitpick though, let us go through other concerns on the PR first.

2024-09-14 23:01 UTC, lewyche commented on src/openrct2-ui/windows/Themes.cpp
>          int8_t _colour_index_2 = -1;
I'm thinking something like `_class_index` and `_button_index`. Of course, I'll have to rename `GetColourIndex()` as well.

2024-09-15 10:08 UTC, AaronVanGeffen commented on src/openrct2-ui/windows/Themes.cpp
>          int8_t _colour_index_2 = -1;
Sounds good, though please use lowerCamelCase for variables. Here, that would mean `_classIndex`, `_buttonIndex`.

2024-09-16 02:21 UTC, lewyche commented on src/openrct2-ui/windows/Themes.cpp
> +        MakeWidget({236, 46}, { 80,  15}, WindowWidgetType::TableHeader, WindowColour::Secondary, STR_THEMES_HEADER_TRANSPARENCY                                                          ), // Transpa
Do you mean something like this?
![image](https://github.com/user-attachments/assets/fcaf7464-e1f0-40d9-bb66-e722c86998b2)

2024-09-20 23:59 UTC, lewyche commented
The rebase is broken right now, but I have to go. I will fix it later.

2024-09-28 10:12 UTC, tupaschoal commented on src/openrct2-ui/windows/Themes.cpp
> +        MakeWidget({236, 46}, { 80,  15}, WindowWidgetType::TableHeader, WindowColour::Secondary, STR_THEMES_HEADER_TRANSPARENCY                                                          ), // Transpa
Almost, I fixed it on my commit.

2024-09-28 10:15 UTC, tupaschoal approved these changes
I tested this for a bit and it seems to be working fine. Also fixed the formatting I mentioned and the changelog entry

2024-09-28 13:14 UTC, Gymnasiast approved these changes

2024-09-28 13:22 UTC, merged