Move SC6 specific code from ScenarioRepository to S6Importer
OpenRCT2/OpenRCT2 pull request #22644
Opened 2024-08-29 13:23 UTC by AaronVanGeffen

While working on extending the scenario index, I noticed there was quite a bit of code specific to handling SC6 files in `ScenarioRepository.cpp`. This PR moves this code to `S6Importer.cpp` instead, making it analogous to the S4Importer and ParkImporter.

2024-08-29 14:28 UTC, AaronVanGeffen commented on src/openrct2/scenario/ScenarioRepository.cpp
> +                    */
Looks like code for this is present in `S5Importer::Import`, but it will still need to be added to `::GetDetails` as well.

2024-08-29 21:27 UTC, Gymnasiast commented on src/openrct2/scenario/ScenarioRepository.cpp
> +                    */
It is still needed, yes.

2024-08-29 21:32 UTC, AaronVanGeffen commented on src/openrct2/scenario/ScenarioRepository.cpp
> +                    */
I ended up moving the code in question to `::GetDetails` in 7d07225fb07add92ad661b3a4a90096ec9196218 🙂

2024-09-02 20:31 UTC, Gymnasiast requested changes
RCT2-encoding to UTF-8 is not correct:

![Schermafdruk van 2024-09-02 22-26-17](https://github.com/user-attachments/assets/7df7a35d-7c2a-4abc-acb6-cedbc5c05bcd)

2024-09-02 21:55 UTC, AaronVanGeffen commented
Thanks for testing! The issue should be solved now.

2024-09-03 19:11 UTC, Gymnasiast approved these changes

2024-09-03 19:24 UTC, merged