Replaced #define to contexpr on Colour.h
OpenRCT2/OpenRCT2 pull request #23039
Opened 2024-10-21 23:37 UTC by hnsdeveloper

Following #21241, I replaced a #define with a constexpr on the file Colour.h.

2024-10-22 11:33 UTC, tupaschoal commented
Not sure I get the relationship between this PR and the aforementioned issue, can you elaborate?

Also the variable name should be updated to our guidelines.

2024-10-26 20:17 UTC, hnsdeveloper commented
> Not sure I get the relationship between this PR and the aforementioned issue, can you elaborate?
> 
> Also the variable name should be updated to our guidelines.

Sorry, wrong issue. The correct issue is #21421.

2024-10-27 20:01 UTC, Gymnasiast requested changes

2024-10-27 20:01 UTC, Gymnasiast commented on src/openrct2/interface/Colour.h
> +constexpr int TEXT_COLOUR_255 = 255;
Please apply these two changes as well:
- Change type from `int` to `colour_t`
- Rename to `kTextColour254` and `kTextColour255`

(Of course, make sure it compiles locally before pushing, this requires changes in a few files.)

2024-11-02 12:46 UTC, tupaschoal approved these changes

2024-11-02 12:54 UTC, merged