Fix #23238: Guest ride favourite mistake
OpenRCT2/OpenRCT2 pull request #23239
Opened 2024-11-20 15:50 UTC by duncanspumpkin

Fix #23238  Guest ride favourite mistake

Mistake made during implementation

2024-11-20 22:58 UTC, LordMarcel reviewed
Based on my limited tests it seems to behave the same as in vanilla now

2024-11-21 10:01 UTC, Gymnasiast commented on src/openrct2/entity/Guest.cpp
> +static void PeepUpdateFavouriteRide(Guest& peep, const Ride& ride, const uint8_t satisfaction);
It’s optional, but since we’re modifying the function anyway, I think it’s a good idea to rename it to `GuestUpdateFavouriteRide`.

2024-11-21 10:01 UTC, Gymnasiast requested changes
This needs a changelog entry.

Optionally, I’d like the function to be renamed. See the line note.

Looks good otherwise.

2024-11-23 10:30 UTC, Gymnasiast approved these changes

2024-11-23 10:39 UTC, merged